/*
* Descent 3 
* Copyright (C) 2024 Parallax Software
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by D3Launch.rc
//
#define IDS_UPDATEDLG_USERMSG1          1
#define IDS_UPDATEDLG_USERMSG2          2
#define IDS_D3LAUNCH_DLGTITLE           3
#define IDS_D3LAUNCH_URL_ERR1           4
#define IDS_D3LAUNCH_URL_ERR2           5
#define IDS_D3LAUNCH_URL_ERR3           6
#define IDS_D3LAUNCH_URL_ERR4           7
#define IDS_D3LAUNCH_URL_ERR5           8
#define IDS_D3LAUNCH_URL_ERR6           9
#define IDS_D3LAUNCH_URL_ERR7           10
#define IDS_D3LAUNCH_URL_ERR8           11
#define IDS_D3LAUNCH_URL_ERR9           12
#define IDS_D3LAUNCH_URL_ERR10          13
#define IDS_D3LAUNCH_URL_ERR11          14
#define IDS_D3LAUNCH_URL_ERR12          15
#define IDS_D3LAUNCHDLG_NODD            16
#define IDS_D3LAUNCHDLG_NODDT           17
#define IDS_D3LAUNCHDLG_SETUP           18
#define IDS_D3LAUNCHDLG_RM_ERR          19
#define IDS_D3LAUNCHDLG_LNCH_ERR        20
#define IDS_3D_DETECT_NO3D              21
#define IDS_AUDIOTAB_A3D1               22
#define IDS_AUDIOTAB_A3D2               23
#define IDS_AUDIOTAB_NO_SOUND           24
#define IDS_JOYSTICKTAB_ERR1            25
#define IDS_JOYSTICKTAB_NONE            26
#define IDS_UPDATEDLG_GVN_MSG1          27
#define IDS_UPDATEDLG_NO_CON            28
#define IDS_UPDATEDLG_ERROR             29
#define IDS_UPDATEDLG_GVN_MSG2          30
#define IDS_UPDATEDLG_NO_DL             31
#define IDS_UPDATEDLG_NO_FIND           32
#define IDS_UPDATEDLG_WAIT              33
#define IDS_UPDATEDLG_SRV               34
#define IDS_UPDATEDLG_UTD               35
#define IDS_UPDATEDLG_UTDT              36
#define IDS_UPDATEDLG_YES_ERR1          37
#define IDS_UPDATEDLG_PF_ERR1           38
#define IDS_UPDATEDLG_PATCHING          39
#define IDS_UPDATEDLG_GET_FILE          40
#define IDS_UPDATEDLG_CANT_PATCH        41
#define IDS_UPDATEDLG_SKIPPING          42
#define IDS_UPDATEDLG_PATCH_OK          43
#define IDS_UPDATEDLG_SUCCESS           44
#define IDS_UPDATEDLG_NO_PATCH_LIB      45
#define IDS_UPDATEDLG_DL_FILE           46
#define IDS_UPDATEDLG_INIT_CON          47
#define IDS_UPDATEDLG_WS_ERR            48
#define IDS_UPDATEDLG_CON_OK            49
#define IDS_UPDATEDLG_CON_SHUTDOWN      50
#define IDS_UPDATEDLG_WAITING           51
#define IDS_SPEEDTAB_LOW                52
#define IDS_SPEEDTAB_MEDIUM             53
#define IDS_SPEEDTAB_HIGH               54
#define IDS_SPEEDTAB_VERY_HIGH          55
#define IDS_UPDATEDLG_LNCH_UPD1         56
#define IDS_UPDATEDLG_LNCH_UPD2         57
#define IDS_UPDATEDLG_LNCH_UPD3         58
#define IDS_UPDATEDLG_LNCH_UPD_TITLE    59
#define IDS_UPDATEDLG_BEG_PATCH         60
#define IDS_UPDATEDLG_PATCH_COMPLETE    61
#define IDS_UPDATEDLG_PATCH_FAILED      62
#define IDS_UPDATEDLG_PATCH_ERROR       63
#define IDS_UPDATEDLG_PROCESSING        64
#define IDS_UPDATEDLG_FILE_COMPLETE     65
#define IDS_UPDATEDLG_SEARCHING         66
#define IDS_UPDATEDLG_WNDMSG_MAIN       67
#define IDS_UPDATEDLG_WNDMSG_STATUS     68
#define IDS_UPDATEDLG_USERMSG3          69
#define IDS_SITESELECTDLG_SITE_NAME     70
#define IDS_SITESELECTDLG_SITE_ADDRESS  71
#define IDS_SITESELECTDLG_SITE_LOCATION 72
#define IDS_SITESELECTDLG_MUST_SELECT   73
#define IDS_SITESELECTDLG_SELECT_TITLE  74
#define IDS_UPDATEDLG_BADPARMS          75
#define IDS_UPDATEDLG_CANT_WRITE_FILE   76
#define IDS_UPDATEDLG_CANT_PARSE_URL    77
#define IDS_UPDATEDLG_BAD_FILE_OR_DIR   78
#define IDS_UPDATEDLG_HOST_NOT_FOUND    79
#define IDS_UPDATEDLG_NO_MEMORY         80
#define IDS_UPDATEDLG_CANCELLED         81
#define IDS_UPDATEDLG_UNKNOWN_ERROR     82
#define IDS_UPDATEDLG_DOWNLOAD_ERROR    83
#define IDS_SITESELECTDLG_PARSE_ERROR   84
#define IDS_UPDATEDLG_DONE_UPDATING     85
#define IDS_UPDATEDLG_CONTINUE_MSG      86
#define IDS_UPDATEDLG_NO_MOTD           87
#define IDS_UPDATEDLG_DL_MOTD           88
#define IDS_UPDATEDLG_GOT_MOTD          89
#define IDS_UPDATEDLG_NODL_MOTD         90
#define IDS_AUDIOTAB_CARD_MISSING       91
#define IDS_AUDIOTAB_WARNING            92
#define IDS_DIRECTXTAB_OK               93
#define IDS_D3LAUNCH_NO_CD              94
#define IDS_D3LAUNCH_CD_ERROR           95
#define IDS_DIRECTXTAB_NTMSG            96
#define IDS_DIRECTXTAB_NTNOTICE         97
#define IDS_DIRECTXTAB_LOAD_ERROR       98
#define IDS_D3LAUNCHDLG_NO_UNINSTALL    99
#define IDS_D3LAUNCHDLG_COULDNT_UNINSTALL 100
#define IDS_D3LAUNCHDLG_WARNING_PROMPT  101
#define IDD_D3LAUNCH_DIALOG             102
#define IDS_D3LAUNCHDLG_WARNING_TITLE   102
#define IDS_D3LAUNCHDLG_UNINSTALL_ERROR 103
#define IDS_D3LAUNCHDLG_PLAY            104
#define IDS_D3LAUNCHDLG_PLAY_BTN        104
#define IDS_D3LAUNCHDLG_SETUP_BTN       105
#define IDS_D3LAUNCHDLG_UPDATE_BTN      106
#define IDS_D3LAUNCHDLG_README_BTN      107
#define IDS_D3LAUNCHDLG_DIRECTX_BTN     108
#define IDS_D3LAUNCHDLG_UNINSTALL_BTN   109
#define IDS_D3LAUNCHDLG_INSTALL_BTN     110
#define IDS_D3LAUNCHDLG_STRAIGHTTOSETUP_MSG 111
#define IDS_D3LAUNCHDLG_STRAIGHTTOSETUP_TITLE 112
#define IDS_D3LAUNCHDLG_PLAY_WARNING_MSG 113
#define IDS_D3LAUNCHDLG_FILE_NOT_FOUND  114
#define IDS_D3LAUNCH_NO_HELP            115
#define IDS_SPEEDTAB_SPEED_PROMPT       116
#define IDS_SPEEDTAB_SPEED_TITLE        117
#define IDS_D3LAUNCHDLG_WEBPAGE_BTN     118
#define IDS_D3LAUNCHDLG_PXO_BTN         119
#define IDS_D3LAUNCHDLG_NO_RENDERER_MSG 120
#define IDS_D3LAUNCHDLG_NO_RENDERER_TITLE 121
#define IDS_D3LAUNCHDLG_DEMO_ONLY_MSG   122
#define IDS_D3LAUNCHDLG_DEMO_ONLY_TITLE 123
#define IDS_D3LAUNCH_DEMO_DLGTITLE      124
#define IDS_VIDEOTAB_DXVERSION_TITLE    125
#define IDS_VIDEOTAB_DXVERSION_MSG      126
#define IDS_D3LAUNCHDLG_DXVERSION_TITLE 127
#define IDR_MAINFRAME                   128
#define IDS_D3LAUNCHDLG_DXVERSION_MSG   128
#define IDD_UPDATE_DIALOG               129
#define IDS_D3LAUNCHDLG_NOMEM_TITLE     129
#define IDS_D3LAUNCHDLG_NOMEM_MSG       130
#define IDS_PLEASE_WAIT_MSG             131
#define IDS_VIDEOTAB_SCANNING           132
#define IDS_AUDIOTAB_SCANNING           133
#define IDB_D3LAUNCH_BG                 134
#define IDS_JOYSTICKTAB_SCANNING        134
#define IDD_PROPPAGE_JOYSTICK           135
#define IDS_VIDEOTAB_MTOD_MSG           135
#define IDD_PROPPAGE_VIDEO              136
#define IDS_VIDEOTAB_MTOD_TITLE         136
#define IDD_PROPPAGE_AUDIO              137
#define IDS_SPEEDTAB_NOT_DETECTED       137
#define IDD_PROPPAGE_SPEED              138
#define IDS_UPDATEDLG_NOREGVER_MSG      138
#define IDD_PROPPAGE_NETWORK            139
#define IDS_UPDATEDLG_NOREGVER_TITLE    139
#define IDD_WAIT_DIALOG                 140
#define IDS_DIRECTXTAB_UPD_REC          140
#define IDS_SPEEDTAB_CUSTOM             141
#define IDS_D3LAUNCHDLG_SPD_MSG         142
#define IDS_D3LAUNCHDLG_SPD_TITLE       143
#define IDS_D3LAUNCHDLG_LAUNCH_ERRMSG   144
#define IDS_D3LAUNCHDLG_CONTEST_MSG     145
#define IDS_D3LAUNCHDLG_CONTEST_TITLE   146
#define IDS_D3LAUNCHDLG_DXERR_SUCCESS   147
#define IDS_D3LAUNCHDLG_DXERR_SUCCESS_RESTART 148
#define IDS_D3LAUNCHDLG_DXERR_BADSOURCESIZE 149
#define IDS_D3LAUNCHDLG_DXERR_BADSOURCETIME 150
#define IDS_D3LAUNCHDLG_DXERR_BADWINDOWSVERSION 151
#define IDS_D3LAUNCHDLG_DXERR_CANTFINDDIR 152
#define IDS_D3LAUNCHDLG_DXERR_CANTFINDINF 153
#define IDS_D3LAUNCHDLG_DXERR_INTERNAL  154
#define IDS_D3LAUNCHDLG_DXERR_NOCOPY    155
#define IDS_D3LAUNCHDLG_DXERR_NOTPREINSTALLEDONNT 156
#define IDS_D3LAUNCHDLG_DXERR_OUTOFDISKSPACE 157
#define IDS_D3LAUNCHDLG_DXERR_SOURCEFILENOTFOUND 158
#define IDS_D3LAUNCHDLG_DXERR_UNKNOWNOS 159
#define IDS_D3LAUNCHDLG_DXERR_USERHITCANCEL 160
#define IDS_D3LAUNCHDLG_DXERR_TITLE     161
#define IDD_PROPPAGE_KEYBOARD           162
#define IDS_D3LAUNCHDLG_DSETUP_ERR_MSG1 162
#define IDD_MESSAGE_WINDOW              163
#define IDS_D3LAUNCHDLG_DSETUP_ERR_MSG2 163
#define IDD_SITE_SELECTION_DIALOG       164
#define IDS_D3LAUNCHDLG_DSETUP_ERR_TITLE 164
#define IDD_MOTD_DIALOG                 165
#define IDS_GLSETUP_ERROR               165
#define IDD_PROPPAGE_DIRECTX            166
#define IDS_LANG_ENGLISH                166
#define IDB_PALETTE_BITMAP              167
#define IDS_LANG_FRENCH                 167
#define IDS_LANG_GERMAN                 168
#define IDS_LANG_ITALIAN                169
#define IDS_LANG_SPANISH                170
#define IDS_D3LAUNCH_OEMV3_DLGTITLE     171
#define IDS_D3LAUNCH_OEMA2_DLGTITLE     172
#define IDS_D3LAUNCH_OEMKM_DLGTITLE     173
#define IDS_D3LAUNCHDLG_UPDPRMT_MSG     174
#define IDS_D3LAUNCHDLG_UPDPRMT_TITLE   175
#define IDS_D3LAUNCH_OEM_DLGTITLE       176
#define IDS_D3LAUNCH_DEMO2_DLGTITLE     177
#define IDS_OPENGL_WARNING_MSG          178
#define IDS_OPENGL_WARNING_TITLE        179
#define IDS_NOTGLIDE_TITLE              180
#define IDS_NOTGLIDE_MSG                181
#define IDS_PROFANITY_MSG               182
#define IDS_PROFANITY_TITLE             183
#define IDS_GLSETUP_EXPIRED_MSG         184
#define IDS_FINDFAST_MSG                185
#define IDS_FINDFAST_TITLE              186
#define IDS_OK                          187
#define IDS_CANCEL                      188
#define IDS_HELP                        189
#define IDD_MSG_DLG                     205
#define IDD_VIDEODETECT_DLG             206
#define IDD_DRIVERS_DIALOG              215
#define IDD_GLSETUP_DIALOG              216
#define IDD_FINDFASTDLG                 218
#define IDC_BTN_QUIT                    1001
#define IDC_PROGRESS1                   1001
#define IDC_BTN_SETUP                   1002
#define IDC_LIST1                       1002
#define IDC_BTN_README                  1003
#define IDC_BTN_WEBPAGE                 1004
#define IDC_BTN_DETECT                  1005
#define IDC_BTN_CALIBRATE               1006
#define IDC_JOYSTICK_LIST               1008
#define IDC_FF_ENABLED                  1009
#define IDC_FF_HIT_EFFECT               1010
#define IDC_VIDEOCARD_LIST              1011
#define IDC_VIDEOCARD_DETECT            1012
#define IDC_BTN_PLAY                    1013
#define IDC_AUDIO_LIST                  1014
#define IDC_BTN_AUDIO_DETECT            1015
#define IDC_SPEED_LIST                  1016
#define IDC_BTN_UPDATE                  1017
#define IDC_BTN_SPEED_DETECT            1018
#define IDC_USERMSG                     1018
#define IDC_CONNECT_TYPE_GROUP          1019
#define IDC_CONNECT_SPEED_GROUP         1020
#define IDC_BTN_LIGHT                   1021
#define IDC_CPU_TYPE                    1024
#define IDC_US_KEYBOARD                 1024
#define IDC_VRAM_SPEED                  1025
#define IDC_FRENCH_KEYBOARD             1025
#define IDC_TOTAL_RAM                   1026
#define IDC_DX_VERSION                  1026
#define IDC_GERMAN_KEYBOARD             1026
#define IDC_RAM_SPEED                   1027
#define IDC_GET_DX                      1027
#define IDC_WND_MSG_MAIN                1027
#define IDC_CPU_SPEED                   1028
#define IDC_MSG1                        1028
#define IDC_WND_MSG_STATUS              1028
#define IDC_DX_STATUS                   1028
#define IDC_3D_GRAPHICS_ACCELERATOR     1029
#define IDC_MSG2                        1029
#define IDC_SITE_LIST                   1029
#define IDC_MSG3                        1030
#define IDC_MOTD_EDIT                   1030
#define IDC_YOUR_VERSION_EDIT           1032
#define IDC_LATEST_VERSION_EDIT         1033
#define IDC_MIXER_SOFTWARE              1034
#define IDC_NONE                        1035
#define IDC_MIXER_DS8BIT                1035
#define IDC_DIALUP                      1036
#define IDC_STATUSBAR                   1036
#define IDC_MIXER_DS16BIT               1036
#define IDC_LAN                         1037
#define IDC_MIXER_DS3D                  1037
#define IDC_SLOW_CONNECTION             1038
#define IDC_33K_CONNECTION              1038
#define IDC_MIXER_AUREAL                1038  // Unused
#define IDC_56K_CONNECTION              1039
#define IDC_BTN_PXO                     1039
#define IDC_CABLE_CONNECTION            1040
#define IDC_BTN_UNINSTALL               1040
#define IDC_BTN_DIRECTX                 1041
#define IDC_NO_CONNECTION               1043
#define IDC_28K_CONNECTION              1043
#define IDC_ANIM_BUTTON                 1043
#define IDC_FAST_CONNECTION             1044
#define IDC_BTN_CANCEL                  1044
#define IDC_SINGLE_ISDN_CONNECTION      1045
#define IDC_PRIMARY_JOYSTICK_TEXT       1045
#define IDC_SCANNING_TEXT               1046
#define IDC_WAIT_TEXT                   1047
#define IDC_DIRECT3D_CHECK              1049
#define IDC_GLIDE_CHECK                 1050
#define IDC_OPENGL_CHECK                1051
#define IDC_COMMANDLINE_EDIT            1052
#define IDC_LAUNCHER_SND_CHECK          1053
#define IDC_CUSTOM1                     1057
#define IDC_LANGUAGE_COMBO              1058
#define IDC_DIRECTX_BUTTON              1059
#define IDC_GLSETUP_BUTTON              1060
#define IDC_INSTALL_BUTTON              1063
#define IDC_VISIT_BUTTON                1064
#define IDC_INFO_STATIC                 1065
#define IDC_INFO2_STATIC                1066
#define IDC_INFO3_STATIC                1067
#define IDC_MIXER_EAX                   1068
#define IDC_CHFLIGHT_CHECK              1069
#define IDC_MOUSEMAN_CHECK              1070
#define IDC_FINDFASTCHKBOX              1071
#define IDC_FINDFAST_CHECK              1072

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1073
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
