//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     19

// Message List
Andy=Andy Crosby & The Outrage Testers' Lab
Chris=Chris Pfieffer's Office
Claflin=Chris Claflin's Office
Doug=Doug Brooks' Office
Hayes=Chris Hayes' Office
Interplay=Darrell Jones & The Interplay Testers' Lab
Jay=Jay Chrispen's Office
JeffNate=Jeff Slutter & Nate Goudie's Office
Jerry=Jerry Berlongieri's Office
Kevin=Kevin Bentley's Office
Long=Matt Long's Office
LukeJosh=Luke Schnieder & Josh Foreman's Office
Mark=Mark Dinse's Office
Matt=Matt Toschlog's Office
Mea=Mea Konopasek's Office
Samir=Samir Sinha's Office
Sean=Sean Lynn's Office
