//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     7

// Message List
DisableMatcen=Centro de materialización desactivado.
Intro=Ten precaución.| Nos encontramos en alerta de seguridad de nivel 3.
WeatherControl=Centro de control de iluminación activado.
WindThing=Núcleo del generador magnético destruido.
