//////////////////////////////////////////////
//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////
//////////////////////////////////////////////


NEXT_MESSAGE_ID_NUMBER     7
NEXT_MESSAGE_ID_NUMBER     7


// Message List
// Message List
DisableMatcen=Materialization Center disabled!
DisableMatcen=Robogène désactivé !
Intro=Proceed with caution.|  Security alert level 3 in effect!
Intro=Faites bien attention.|  Alerte de sécurité au niveau 3 !
WeatherControl=Lightning control system activated.
WeatherControl=Système anti-foudre désactivé.
WindThing=Magnetic generator core destroyed!
WindThing=Coeur du générateur magnétique détruit !

