
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     7



// Message List

DisableMatcen=Centro di Materializzazione disattivato!

Intro=Procedere con precauzione!  Attivato livello di Sicurezza 3!

WeatherControl=Attivato sistema di controllo lampi.

WindThing=Distrutto nucleo del generatore magnetico!

