
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     37



// Message List

AllDone=GUIDEBOT: "Objectifs réussis ! Echappez-vous de l'usine pour achever votre mission! "

AllStabsDone=GUIDEBOT: "Les quatre stabilisateurs ont été débrayés !"

Blank=

CovDamaged=TRANSPORTEUR: Aidez-nous SVP !  Nous sommes sérieusement touchés !

CovDanger=TRANSPORTEUR: Nous sommes en danger !

CovDropOff=TRANSPORTEUR: Largage composant pour ramassage !

CovEntering=TRANSPORTEUR: Nous entrons dans l'Usine de Vaisseaux Spatiaux.

CovFFHelp=TRANSPORTEUR: Nous avons besoin de votre aide pour passer ces champs de forces dans la zone de stockage. Vite !

CovGettingPummeled=TRANSPORTEUR: Les forces de la PTMC nous assaillent ! A l'aide !

CovInClear=TRANSPORTEUR: Pas de problème pour l'instant !

CovLeaveMeAlone=TRANSPORTEUR: Regardez où vous visez !

CovLeaving=TRANSPORTEUR: Notre boulot est fini !  Merci de votre aide !

CovPickup=TRANSPORTEUR: Ramassage composant vaisseau.

CovRepaired=TRANSPORTEUR: Réparation terminée.  Nous reprenons la mission !

CovShutDown=TRANSPORTEUR: Trop de dégâts ! Arrêt moteurs pour réparation !

CovStillStuckFF=TRANSPORTEUR: Nous ne pouvons toujours pas passer ce champ de force !  Demandons assistance !

CovThanksFF=TRANSPORTEUR: Merci de votre aide !

DestroyedAnt=GUIDEBOT: "Antenne de transmission détruite !"

DestroyedRadar=GUIDEBOT: "Radar de surveillance détruit !"

Disruptor=Disrupteur sismique

DoStabs=GUIDEBOT: "Débrayez les stabilisateurs pour terminer votre mission !"

EndLevel=

IntroCam=Mercure - Usine de Vaisseaux Spatiaux de la PTMC

StabAssemblyDone=Stabilisateur Sismique de l'usine| d'assemblage débrayé !


StabAssemblyPower=GUIDEBOT "Passage du stabilisateur de l'usine d'assemblage au  mode passif !"

StabControlDone=Stabilisateur Sismique du Centre| de Contrôle débrayé !

StabControlPower=GUIDEBOT: "Passage du stabilisateur du Centre de Contrôle au mode passif !"

StabFactoryDone=Stabilisateur Sismique de l'Usine| Principale débrayé!

StabFactoryPower=GUIDEBOT: "Passage du  stabilisateur de l'usine principale au mode passif !"

StabStoreDone=Stabilisateur sismique du Centre de Stockage| débrayé!

StabStorePower=GUIDEBOT: "Passage du stabilisateur du Centre de Stockage au mode passif!"



TempGoal=GUIDEBOT: "Débrayez les stabilisateurs pour créer une diversion pendant que le transporteur récupère les composants!"

Testing=Niveau de Distraction: %f

Testing2=Niveau de Bouclier: %f

Transmitter=Réception d'une transmission encodée...

TransmitterHave=GUIDEBOT: "Pour recevoir une transmission vidéo du transporteur, utilisez votre Transmetteur Espion!"

