
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     73



// Message List
BaseAlertDisplay=Niveau d'alerte : %d
BaseAlertStatus=GUIDEBOT: "Le Centre de Commande est maintenant au Niveau d'Alerte %d."
CannonHitPlayer=GUIDEBOT: "Tir du canon de surface !"
CrashedShipGame=Pilote Eclaireur T.Murphy S.O.S ! Mon vaisseau est en feu. Tous systèmes en panne. Je vais m'écraser... La base est bien gardée. Attention aux gardes qui alertent les tours... J'aurais dû rester occulté pour ne pas être repéré ! Trop tard.
CrashedShipHud=Vous avez trouvé le journal de bord d'un pilote (SHIFT -  F8)
D1GuardSpotted=GUIDEBOT: "Le gardien de la mine vous a repéré !"
DataUplinkActivated=GUIDEBOT: "commande commande d'amarrage au dispositif de transfert des données activé."
Empty=
GuardTowerAlertedGG=GUIDEBOT: "Le gardien de la mine a alerté la tour !"
GuardTowerAlertedHG=GUIDEBOT: " Le gardien du hangar a alerté la tour !"
HangerCamSawPlayer=GUIDEBOT: "La caméra de sécurité du hangar vous a repéré !"
HangerDoorUnlocked=GUIDEBOT: "La porte du Hangar a été déverrouillée."
HangerGuardSpotted=GUIDEBOT: " Le gardien du hangar vous a repéré !"
HangerMsgGame=JOURNAL: Hier la caméra de sécurité a mal fonctionné et mal identifié un vaisseau de livraison de données. Les tourelles de défense ont ouvert le feu et le vaisseau est irréparable. Les restes du vaisseau ont été jetés dans la vieille mine.
HangerMsgHUD=Journal de la Sécurité du Hangar téléchargé... (SHIFT-F8)
InitInterfaceCin=GUIDEBOT: "Initialisation Interface de Données..."
InterfaceAcquired=GUIDEBOT: "Vous avez obtenu une Interface de Données, modèle P103Z."
InterfaceHasNoPower=GUIDEBOT: "Le panneau de Contrôle du dispositif de transfert de données n'est pas alimenté."
InterfaceInitialized=GUIDEBOT: "Initialisation de l'interface de données de votre vaisseau réussie."
InterfacePowerOff=GUIDEBOT: "Le panneau de Contrôle de Transfert est arrêté."
InterfacePowerOn=GUIDEBOT: "Le panneau de contrôle de transfert est actif."
InterfacePrepDenied=GUIDEBOT: "Erreur: L'interface de données est incompatible ou absente."
InterfacePrepInstHUD=Instructions de préparation de l'interface téléchargées... (SHIFT-F8)
InterfacePrepInstrGame=INSTRUCTIONS: Bienvenue dans la salle de préparation de l'interface de données. Avant de transférer des informations au Centre de Transfert de Données, l'interface de données de votre vaisseau doit être initialisée. Pour préparer votre vaisseau, entrez dans le centre d'initialisation au milieu de la pièce.
IntroText=La Lune - Centre de Commande Lunaire de la CDT
JuggAlertedBase=GUIDEBOT: "Le Mastodonte a alerté la base de Communication!"
JuggAlertWarning=GUIDEBOT: "Le Mastodonte se dirige vers la base de Communication... Arrêtez-le avant qu'il n'y arrive !"
JuggSawPlayer=GUIDEBOT: "Le Mastodonte vous a repéré !"
MatcenActivated=GUIDEBOT: "Ce robogène est maintenant actif."
MatcenDeactivated=GUIDEBOT: "Ce robogène a été désactivé."
MemPlasmaGame=INFO:Certaines interfaces de données peuvent avoir besoin d'une charge de plasma à mémoire pour se connecter au Centre de Transfert Principal. Le dispositif en dessous générera continuellement des charges à cet effet (à moins que la génération ne soit désactivée).
MemPlasmaHUD=Info Charge de Plasma à Mémoire... (SHIFT - F8)
MemPlasmaLost=GUIDEBOT: "Votre charge de Plasma à Mémoire a expiré !"
MemPlasmaObtained=GUIDEBOT: "Charge de Plasma à Mémoire obtenue (dure %d secondes)"
MemPlasmaOff=GUIDEBOT: "Génération de Plasma à Mémoire désactivée."
MemPlasmaOn=GUIDEBOT: " Génération de Plasma à Mémoire activée."
NanoPlasmaDefOff=GUIDEBOT: "Les systèmes de défense à nanoplasma du système de transfert ont été désactivés."
NanoPlasmaDefOn=GUIDEBOT: "Les systèmes de défense à nanoplasma du système de transfert sont maintenant actifs."
NoEntry=Entrée interdite au-delà de cet endroit !
Secret1=Vous avez trouvé une zone secrète!
UplinkCenterGame=INFO:Bienvenue au Centre de Transfert de Données. Une fois que le Contrôle des Données a autorisé votre téléchargement, vous pouvez vous amarrer au dispositif de transfert de données en positionnant votre vaisseau directement entre les noeuds à plasma. Si tout ce passe bien, le transfert commence automatiquement.
UplinkCenterHUD=Instructions au Pilote pour le Téléchargement reçues... (SHIFT - F8)
UplinkControlGame=DIRECTIVES:Les Agents du Contrôle des Transferts imposent un contrôle de sécurité à tous les vaisseaux avant d'autoriser tout transfert. Une fois qu'un vaisseau est jugé acceptable, la commande d'amarrage au dispositif de transfert des données peut être activée sur le panneau arrière.
UplinkControlHUD=Directives de Contrôle de Transfert reçues... (SHIFT - F8)
UplinkDocking=GUIDEBOT: "Connexion au dispositif de transfert de données..."
UplinkErrorNano=GUIDEBOT: "Erreur: systèmes de défense à nanoplasma actifs. Transfert annulé."
UplinkErrorNoChg=GUIDEBOT: "Erreur: charge plasma à mémoire insuffisante sur le vaisseau source."
UplinkErrorNoInit=GUIDEBOT: "Erreur: interface de données du vaisseau source non initialisée."
UplinkErrorNoInt=GUIDEBOT: "Erreur: Le vaisseau source n'est pas équipé d'une Interface de Données compatible."
UplinkErrorNoPlasma=GUIDEBOT: "Erreur: l'alimention en plasma du dispositif de transfert de données principal n'est est coupée."
UplinkErrorNotAct=GUIDEBOT: "Erreur: la commande d'amarrage au dispositif de transfert des données n'est pas activé."
UplinkPlasmaOff=GUIDEBOT: "L'alimention en plasma du dispositif de transfert de données principal n'est est coupée."
UplinkPlasmaOn=GUIDEBOT: "L'Alimentation en plasma du dispositif de transfert de données est activée."
UploadingVirus=
VaultKeyAcquired=Clé Entrée Chambre Forte Données
ZcamMonitorOff=Caméra de Sécurité allumée
ZcamMonitorOn=Caméra de Sécurité éteinte
ZcamSpotted=GUIDEBOT: "Les tourelles de défense locale ont été activées !"
ZcanyonAmbush=GUIDEBOT: "Je n'aime pas du tout ça..."
ZcanyonRun=GUIDEBOT: "Le Garde du Canyon s'enfuit ! Attrapez-le !"
ZCBAlerted=GUIDEBOT: "La Base de Commandement a été alertée !"
ZCBNoticed=GUIDEBOT: "Le Garde de la Base de Commandement vous a repéré !"
ZDVAlerted=GUIDEBOT: "La Chambre des Données est en état d'alerte !"
ZDVSpotted=GUIDEBOT: "Le Garde de la Chambre des données vous a repéré!"
ZGotCamMonitor=GUIDEBOT: "Vous avez trouvé un moniteur de caméra de sécurité !"
ZMegaTrap=GUIDEBOT: "Ce Méga était câblé... Attention !"
ZTurretHit=GUIDEBOT: "Les tourelles de défenses locales ont été activées !"

