
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     30



// Message List

CameraActivation=ROBOT-GUIDA: "Trasmissione segnale della telecamera di sicurezza in corso..."

ContainmentDoorUnlocked=Porta di contenimento sbloccata.

Controller=ROBOT-GUIDA: "Instradamento delle difese di superficie ausiliarie verso il sistema primario!"

ControlVulnerable=ROBOT-GUIDA: "Il controller primario del sistema di superficie è ora vulnerabile!"

CoolersAllGone=ROBOT-GUIDA: "Avaria del sistema centrale di raffreddamento. Attivare condizionamento d'emergenza."

DoThis=ROBOT-GUIDA: "Trova i campioni di virus ed esci di lì il più rapidamente possibile!"

FFDisable1=ROBOT-GUIDA: "Blocco dell'alimentazione ausiliaria ai campi di forza di contenimento!"

FFDisabled=ROBOT-GUIDA: "Campi di forza disattivati! Autorizzato l'accesso alla sala di contenimento dei virus."

FFKeyPickup=ROBOT-GUIDA: "Concessa autorizzazione per i controlli di sicurezza."

Finished=

IntroMessage=Asteroide Cerere - Bunker C4 per| le ricerche segrete del PTMC

MagnetActivated=ROBOT-GUIDA: "Attivato acceleratore per la discesa magnetica. Porte di sicurezza sbloccate"

MagnetTube1=ROBOT-GUIDA: "Disattivate serrature 1 e 2 della sala di controllo!"

MagnetTubeDoorUnlock=ROBOT-GUIDA: "Autorizzato accesso alla sala di controllo!  Porta sbloccata!"

ManualActivation=ROBOT-GUIDA: "Questo dispositivo richiede l'attivazione diretta."

NeedFFKey=ROBOT-GUIDA: "Non sei autorizzato a usare questi comandi."

PathEnd=EndLevel

SecretArea=Hai trovato un'area segreta!

SteamRelease=ROBOT-GUIDA: "Fuoriuscita di vapore attivata."

SuperHeaterShutdown=ROBOT-GUIDA: "Dispositivo di contenimento dei virus ad alta temperatura disattivato."

TurretsDeactivated=ROBOT-GUIDA: "Distrutti comandi principali! Sistemi di difesa di superficie disattivati!"

TurretsInvuln=ROBOT-GUIDA: "Le torrette grandi sono troppo resistenti per farle saltare! Occorre trovare un'altra soluzione!"

UpperTubeActivate=ROBOT-GUIDA: "Tubo acceleratore della discesa attivato."

Virus1Collected=Hai trovato un virus!

Virus2Collected=Bel lavoro! Hai raccolto entrambi i campioni di virus.

VirusDescription=ROBOT-GUIDA: "Raccogli entrambi i campioni e scappa!"

