
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     14



// Message List

Area1=GUIDEBOT: "Zone 1"

Area2=GUIDEBOT: "Zone 2"

Area3=GUIDEBOT: "Zone 3"

EndLevelMessage=BEAGLE: Défenseur de la Matière... Nous perdons votre signal ! Que se passe-t'il en bas ?

EntranceDoorMessage=GUIDEBOT: "Protocole de Test Actif !"

IntroBriefingMessage=BEAGLE: Qui sait ce que vous trouverez là-dedans... Explorez la zone et revenez à la base. Nous attendons votre rapport.

IntroHUDmessage=Transmission en provenance du Beagle... (SHIFT-F8)

Nothing=

