//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     30

// Message List
CameraActivation=GUIDEBOT: "Transmission du signal des caméras de sécurité..."
ContainmentDoorUnlocked=Porte de confinement déverrouillée.
Controller=GUIDEBOT: "Routage secours des systèmes de défenses de surface de soutien sur système primaire !"
ControlVulnerable=GUIDEBOT: "Le contrôleur primaire due système de surface est désormais vulnérable !"
CoolersAllGone=GUIDEBOT: "Défaillance du système de refroidissement principal.  Activation contrôle commande de secours manuelle d'urgence due refroidissement."
DoThis=GUIDEBOT: "Trouvez les échantillons de virus et sortez d'ici le plus vite possible !"
FFDisable1=GUIDEBOT: "Extinction Coupure de l'alimentation auxiliaire des champs de confinementforce !"
FFDisabled=GUIDEBOT: "Champs de forces force désactivés ! Accès à la chambre de confinement du virus autorisé."
FFKeyPickup=GUIDEBOT: "Autorisation Cpour les contrôles de sécurité accordése."
Finished=
IntroMessage=Asteroïde Cérès - Bunker de Bunker PTMC Secret | PTMC Bunker de Recherches C4 de la PTMC 
MagnetActivated=GUIDEBOT: "Accélérateur magnétique de descente activé.  Portes de sécurité activéesdéverrouillées."
MagnetTube1=GUIDEBOT: "Verrou 1 sur 2 de la salle de contrôle désactivés !"
MagnetTubeDoorUnlock=GUIDEBOT: "Accès à la salle de contrôle accordé !  Porte déverrouillée !"
ManualActivation=GUIDEBOT: "Ce dispositif doit être activé directement."
NeedFFKey=GUIDEBOT: "Vous n'êtes pas autorisé à utiliser ces commandes."
PathEnd=EndLevel
SecretArea=Vous Avez Trouvé Une Zone Secrète !
SteamRelease=GUIDEBOT: "Soupape de Vapeur activée."
SuperHeaterShutdown=GUIDEBOT: "Dispositif à haute température de confinement à super chaleur de confinement du virus désactivé."
TurretsDeactivated=GUIDEBOT: Commandes primaires désactivéesdétruites !  Systèmes de défenses de surface désactivés !"
TurretsInvuln=GUIDEBOT: "Ces grosses tourelles sont trop puissantes massives pour être exploséessoufflées !  Trouvez une autre manièreautre chose pour vous en débarrasser !"
UpperTubeActivate=GUIDEBOT: "Tube d'accélérateur vertical activé."
Virus1Collected=Vous avez un virus !
Virus2Collected=Excellent travailSuper !  Vous avez recueilli les deux échantillons de virus.
VirusDescription=GUIDEBOT: "Recueillez les deux échantillons et partez sortez rapidement !"

