
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     52



// Message List

ActivatedMatcen=GUIDEBOT: "Robogène Activé !"

Arena1Defeated=GUIDEBOT: "Arène Niveau 1 vaincue. Vous pouvez passer au Niveau 2 !"

Arena1Enter=Arène Niveau 1| Préparez-vous au combat!

Arena2Defeated=GUIDEBOT: "Arène Niveau 2 vaincue. Vous pouvez passer au Niveau 3 !"

Arena2Enter= Arène Niveau 2| Préparez-vous au combat !

Arena3Defeated=GUIDEBOT: "Arène Niveau 3 vaincue. Vous pouvez passer au niveau 4 !"

Arena3Enter= Arène Niveau 3| Préparez-vous au combat !

Arena4Defeated=GUIDEBOT: "Arène Niveau 4 vaincue. Vous pouvez passer à l'Arène du Championnat !"

Arena4Defeated2=GUIDEBOT: Accès accordé à toutes les zones !"

Arena4Enter= Arène Niveau 4| Préparez-vous au combat !

Arena4Enter2= Arène Niveau 2 Partie 2| Préparez-vous au combat !

ArenaChamp=GUIDEBOT: "Le champion des champ des défis est vaincu !  Accès à la surface accordé !"

CowFFDisable=GUIDEBOT: "Séquence de champ de force terminée !"

CowPipeActive=GUIDEBOT: "Générateur de contrôle actif !"

DoorUnlocked=Porte déverrouillée !

EmergencyOverride=GUIDEBOT: "Coupure d'urgence activée. Tous les champs de force de sécurité sont désactivés."

EndBossBegin=Arène Championnat| Préparez-vous au combat !

EndLevel=

EscapedDestroyed=GUIDEBOT: "Il reste un générateur à détruire !"

EscapedDestroyed2=GUIDEBOT: "Vous vous êtes échappé du mécanisme de retenue !"

EscapedTorture=GUIDEBOT: "Mécanisme de torture détruit !"

EscapeTorture2=GUIDEBOT: "Les générateurs de champ de force devraient être vulnérables maintenant !"

Forcefield=Champs de force désactivés !

GonnaClean=ATTENTION: Générateurs de contrôle détruits ! Activation système de nettoyage à chaud !

Guards1=Un concurrent éliminé !

Guards2=Il reste deux concurrents à éliminer !

Guards3=Il reste un concurrent à éliminer !

IntroMessage=Charon - Champ des défis de la PTMC 

L1Door=Clé Niveau 1 Nécessaire !

L2Door=Clé Niveau 2 Nécessaire !

L3Door=Clé Niveau 3 Nécessaire !

L4Door=Clé Niveau 4 Nécessaire !

Level1Key=Clé Niveau 1

Level2Key=Clé Niveau 2

Level3Key=Clé Niveau 3

Level4Key=Clé Niveau 4

LevelStarted=GUIDEBOT: "Rendez-vous au plus vite au champ des défis ! C'est votre seule chance de vous en sortir ! Battez-vous pour rejoindre la surface !"

MainFFDeactivated=GUIDEBOT: "Concurrents de l'arène principale éliminés.  L'adversaire final peut maintenant entrer dans l'arène du championnat !"

MainGuards=GUIDEBOT: "Vous allez devoir éliminer tous les concurrents avant de vous qualifier pour l'Arène du Championnat !"

RecoveredSecret=RECUPEREE: Vieille cartouche de données. Guidebot en recherche d'informations...

RedUnitsArmed=GUIDEBOT: "Unités de Contrôle armées et prêtes pour l'explosion !"

RepairActivated=GUIDEBOT: "Installations de réparation réactivées !"

RepairDeactivated=GUIDEBOT: Installations de réparation désactivées !"

RepairingShip=Réparation des boucliers de votre vaisseau| Retour à un niveau de protection maximal !

SecretData=Cette cartouche est vraiment usée et complètement rouillée, mais votre Guidebot arrive à en extraire des données qui pourraient être utiles. Elles font état d'une sorte de Complexe Industriel Secret qui n'apparaît pas sur vos cartes de navigation. Ca vaudrait le coup de vérifier ça plus tard.

SRepairInit=GUIDEBOT: "Unité de Réparation décalibrée. Veuillez réinitialiser !"

