//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     54

// Message List
AftMatcenCheck=GUIDEBOT: "Inspecting Aft Matcen Trigger."
AftSwCinema=Disable Aft Matcen
AuxCoreDoor=GUIDEBOT: "Auxillary Engine Core Access Denied.  Find another way!"
Bay62Door=GUIDEBOT: "Bay 62 Access Door has been jammed.  Find another way!"
Bay62Fuse=GUIDEBOT: "Bay 62 Matcen Disabled."
Bay62Game=11:37.04.04.3750 EVENT LOG BADGE ID FIGHTER WING 62 M. KELLY COMMANDING: "We were unsuccessful in our efforts here.  We know they now have control of at least two StarHawk Fighters! Infection has spread to worker drones.   I am evacuating my men."
Bay62Hud=Bay 62 Event Log Downloaded... (SHIFT - F8)
Bay62Lance=GUIDEBOT: "Turrets Disabled."
BayInfoGame=07:02.04.04.3750: PTMC DeepSpace Delivery 432178: "Matcen Parts Order Logged aboard."
BayInfoHud=Downloaded Bay 36 Event Log... (SHIFT - F8)
Cleanup=CED COMMANDER: "Cleanup any remaining Stormtroopers."
CoreAccFF=GUIDEBOT: "Access to Core Shielded. Find another way in."
CoreInfo1=11:11:04.04.3750 Event Log Downloaded... (SHIFT - F8)
CoreInfo2=11:11.04.04.3750  INTRUDER ALERT! "Engine Core Access Door NO. 79.287  Disabled by User ID BADGE NO. 80-84."
CoreRads=GUIDEBOT: "Critical Mass Interference!"
DangerEngine=GUIDEBOT: "WARNING  -- Engine Surge Area!"
EndCine=
EndMission=CED COMMANDER: "You have cleared all Stormtroopers.  Good Job!"
EngineDown=GUIDEBOT: "Tertiary Objective Completed!  Engine Core Shutdown."
EngineMisfire=GUIDEBOT: "WARNING -- ENGINE MISFIRE!!"
EngineTakover=CED COMMANDER: "Stormtroopers have seized Engine Control..."
GotReconInterface=Recon Interface
IntroText=Mars orbit - CED| Expediator Flagship Carrier
JeffriesID=GUIDEBOT: "Aft Jeffries Tube.  There is a way to get through to the Stern Section from here."
LeaderTaunt1=CED RADIO: "This is the Victorious Legion Troop Commander..."
LeaderTaunt2=CED RADIO: "We are assuming control of the Expediator."
LeaderTaunt3=CED RADIO: "We will terminate any units who do not surrender immediately."
LeaderTaunt4=CED RADIO: "We do not bleed.  Therefore we do not empathize."
LeaderTaunt5=CED RADIO: "Stop....!"
LevelObjA=GUIDEBOT: "You have successfully disabled the Aft Matcen!"
LevelObjtives1=Primary Objectives: | 1. DISABLE AFT MATCEN | Destroy Manual Override Switch.
LevelObjtives2=2. Search and Destroy: | Victorious Legion | Troop Commander.
LevelObjtives3=Neutralize Threat of Hostile Takeover: | REDUCE | Red, Green, and White | STORMTROOPER DEFENSE LEGION.
MainDeckGame=11:22.04.04.3750 SHIP STATUS  LOG C.E.D. EXPEDIATOR DREADNAUGHT: "Unknown Virus contaminated Ship Defense Systems including ST-Units.  We have isolated entire Aft Section of the Ship.  Hopefully, everyone got out in time! Investigating viable solutions."
MainDeckHud=Ship Status Event Log Downloaded... (SHIFT - F8)
NoEntry=QUARANTINED  -- No Entry Beyond This Point.
NoEntry62=This Hangar Bay Access Door has been welded shut.  Find another way.
PplDoors1=Personnel Access is Quarantined.
PrimaryObjB=CED COMMAND: "Congratulations!  You have completed your  secondary objective."
PrimerDamage=GUIDEBOT: "Plasma Field!!   Ship has taken Damage."
RobotCount=You still have %d Infected Stormtroopers remaining!
SecondaryObjective=EMERGENCY!!! | ENGINE MALFUNCTION...|
ShipInfo1=Ship Event Log Downloaded... (SHIFT - F8)
ShipInfo2=10:59.04.04.3750: "This is an emergency voice log of Aft Master Engineer Kalmer. After attaching replacement parts with new shipment order 47632-09. Matcen was committed.  It is producing infected Stormers! No way to overide!!! Evacuating repair crew."
SpyPlead=HUNTER DRONE: "Please -- I won't do anything if you don't shoot me -  I'm not like the others!"
StormtroopersCine=Get these guys...| Before they get you!
