
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     39



// Message List

1Switch=GUIDEBOT: "Pour contourner les champs de force primaires, trouvez et actionnez les neuf interrupteurs pour déverrouiller la porte de l'ascenseur !"

2Switch=GUIDEBOT: "Deux interrupteurs secondaires actionnés !"

3Switch=GUIDEBOT: "Trois interrupteurs secondaires actionnés !"

4Switch=GUIDEBOT: "Quatre interrupteurs secondaires actionnés !"

5Switch=GUIDEBOT: "Quatre interrupteurs secondaires de plus à trouver!"

6Switch=GUIDEBOT: "Plus que trois interrupteurs secondaires à trouver!"

7Switch=GUIDEBOT: "Encore deux interrupteurs secondaires pour déverrouiller la porte de l'ascenseur!"

8Switch=GUIDEBOT: "1 dernier interrupteur secondaire dans la série!"

9Switch=GUIDEBOT: "Séquence secondaire terminée ! Porte de l'ascenseur abandonné déverrouillée !"

All6Deactive=GUIDEBOT: "Les six routeurs d'énergie sont désactivés !  Les générateurs de champ de force de secours sont activés !"

DestroyThese=Trouvez un moyen de mettre en| route les générateurs de secours avant| de les détruire et de réduire les champs de force !

DoorUnlocked=Porte déverrouillée!

DoThis=

ExitAbort=Le vaisseau capturé étant retenu aux portes, ce niveau s'achèvera automatiquement dans cinq secondes !

FirstCamera=Ils sont peut-être petits, mais même| leurs amis prennent leurs jambes à leur cou !|  Restez hors de leur vue si vous tenez à la vie.

ForcefieldDisabled=Champ de force désactivé !

ForcefieldFirst=GUIDEBOT: "Champ de force primaire désactivé. Activation du générateur de secours !"

ForcefieldsDisabled=Champs de force désactivé !

FreeAtLast=PILOT: "Merci pour le sauvetage, Défenseur de la Matière !  Allons-nous en ! Suivez-moi !"

GoalComplete=Objectif réussi !

GotHim=Merci d'être tombé droit dans notre| piège, Défenseur de la Matière !

GoUpLeft=PILOT: "Ces tubes d'évacuation sont synchro-verrouillés.  Prenez par la gauche et moi par la droite ! Rendez-vous dehors!"

MainDestroyed=GUIDEBOT: "Générateurs de champs de force primaires détruits."

NextGoal=En Patrouille 3

PathCaptured=Capturé

PathIntroCam=IntroCam

PathIntroShip=IntroShip

PickupKey=GUIDEBOT: "Accès au centre secondaire accordé !  Toutes portes du centre primaire déveouillées !"

PipeDemo=Les conduits sont vulnérables quand ils| sont actifs. Sinon, ne gâchez pas vos munitions.

Reroute=GUIDEBOT: "Routeur d'énergie désactivé !"

SecretArea=Vous avez trouvé une zone secrète !

Spotted=WARNING: Alerte à l'envahisseur !  Tourelle de défense activée !

Work=Titan - Installation de Stockage de la PTMC

