//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     47

// Message List
1ReactorOn=GUIDEBOT: "1 of 5 Reactors restored. Energy Converters available."
30SecondsLeft=GUIDEBOT: "Only 30 seconds left to evacuate!  Hurry!"
BLANK=
Critical=Shield Level Critical!
DefendReactorsShort=GUIDEBOT: "Defend the reactors for 12 minutes, then evacuate!"
DefendThoseReactors2=RED ACROPOLIS: "We're under attack!  Defend three of the five reactors until we give our signal.  All personnel should reach the Evacuation Shuttles within the next 12 minutes.  We'll blow the reactors from orbit to destroy any evidence!"
Destroyed=GUIDEBOT: "Reactor Disabled!"
EnergyConvertedToShields=GUIDEBOT: "Transferring Energy to Reactor's Shields!"
EnergytoShield=RED ACROPOLIS: "You'll find an energy to shield converter hooked into each reactor.  Fire your energy weapons at it to boost a reactor's shields if it gets attacked.  If you need more energy, there's an energy center midway through tunnel 3."
EntranceDoorMessage=GUIDEBOT: "Red Acropolis Emergency Security Lockdown is in effect!"
ExitOnly=GUIDEBOT: "Emergency Exit only!"
Health25=25 Percent Shield Level...
Health50=50 Percent Shield Level...
Health75=75 Percent Shield Level...
HITPOINTS=reactor hitpoints : %f
IncomingMessage=Incoming message from Red Acropolis... (SHIFT - F8)
IntroMessage=Mars - Red Acropolis Research Facility|
OOPS=RED ACROPOLIS: "We're losing power across the grid!  Emergency evacuation systems are failing!   I'm afraid there's nothing more we can do... but surrender."
Reactor1Started=GUIDEBOT: "Reactor 1 is now operational."
Reactor1Status=Reactor 1 Status :
Reactor2Started=GUIDEBOT: "Reactor 2 is now operational."
Reactor2Status=Reactor 2 Status :
Reactor3Started=GUIDEBOT: "Reactor 3 is now operational."
Reactor3Status=Reactor 3 Status :
Reactor4Started=GUIDEBOT: "Reactor 4 is now operational."
Reactor4Status=Reactor 4 Status :
Reactor5Started=GUIDEBOT: "Reactor 5 is now operational."
Reactor5Status=Reactor 5 Status :
ReactorDisabled=GUIDEBOT: "Reactor is Disabled!"
ReactorHUDLabel=Reactors:
SelfDestruct=GUIDEBOT: "They've made it out safely.  Get to the exit before the self-destruct sequences activates!"
Shake=Shake the Mine!
ShieldsAtMax=GUIDEBOT: "Maximum Shield Level Attained!"
StartTimer=Start Timer here!
Testing=Test!
WereGettinOut=RED ACROPOLIS: "Good work!  All personnel have been accounted for, and the shuttles are cleared for take-off.  We've set the reactors to self-destruct in 90 seconds, so get out of there now!  Head back to the main hub to find the exit!"
