//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     14

// Message List
Area1=GUIDEBOT: "Area 1"
Area2=GUIDEBOT: "Area 2"
Area3=GUIDEBOT: "Area 3"
EndLevelMessage=BEAGLE: Material Defender... We're losing your signal! Anything strange down there?
EntranceDoorMessage=GUIDEBOT: "Testing Protocol Active!"
IntroBriefingMessage=BEAGLE: I'm not sure what you'll find in this place. Explore the area and report back to base.
IntroHUDmessage=Incoming Transmission from the Beagle... (SHIFT - F8)
Nothing=
