//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     8

// Message List
BlackPyroKey=ROBOGUÍA: "El último Pyro negro ha dejado caer una llave."
Empty=
EndGameHud=
EndGameMess=Has facilitado la información.
EndLevelText=
GotSuzukiKey=Llave del edificio Suzuki
IntroMsg=Vete al edificio Suzuki| y entrega el expediente sobre la conspiración al señor Suzuki

NEXT_MESSAGE_ID_NUMBER     11

// Message List
BPDefeated=GUIDEBOT: "¡Mercenarios de la PTMC vencidos!"
CartridgeError=GUIDEBOT: "No puedes soltar aquí el cartucho de datos."
CinematicAmbush=Mercenarios de la PTMC
CinematicDataCart=Transmitiendo datos a Suzuki
CinematicEndCam=
CinematicIntroCam=Tierra - Seúl, Corea
Debug1=Ajuste de dificultad: %f
Debug2=¡Esto es fuerte!
GetOut=ROBOGUÍA: "¡Transmisión correcta! Ahora Suzuki debe tener los datos."
PutTheCartridge=ROBOGUÍA: "Coloca el cartucho de datos en el centro de la sala de transmisiones."

