
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     33



// Message List

All4Radio=ROBOT-GUIDA: "Trasmissione comunicatore trasferimento dati attivata!"

All4Radio2=ROBOT-GUIDA: "Ora sembra possibile accedere all'armeria!"

DataFinal=ROBOT-GUIDA: "La cartuccia contiene i dati che ci servono! Ritorna in superficie per completare la missione!"

DataNodes=ROBOT-GUIDA: "Inserisci la cartuccia dati tra i nodi di trasferimento!"

DataOriginal=ROBOT-GUIDA: "La cartuccia è vuota! Cerca i nodi di trasferimento dati e inserisci la cartuccia tra di loro!"

DestroyedSuper=ROBOT-GUIDA: "Super Ladro distrutto! Ora la cartuccia dovrebbe contenere i dati!"

DestroyedThief=ROBOT-GUIDA: "Ladro distrutto! Recupera la cartuccia dati!"

EndLevel=Recuperati i dati delle ricerche Sweitzer

FalseTransfer=ROBOT-GUIDA: "Manca la cartuccia su cui trasferire i dati!"

ForceFieldDeactivated=Campo di forza disattivato!

IntroMessage=Tiris - Centro Stazione PTMC Piccu | & Laboratorio SRAD Beta Ceti

KillSuper=ROBOT-GUIDA: "Distruggi il Super Ladro per recuperare la cartuccia dati!"

LTSelfDestruct=ROBOT-GUIDA: "La torre di illuminazione non può scaricarsi e si sta audistruggendo!"

MainKeyCard=Chiave di sicurezza

PlaceCartridge=ROBOT-GUIDA: "La cartuccia dati è pronta per il trasferimento dati! Cerca i comandi per i dati!"

RadioRoomFirst=ROBOT-GUIDA: "Accoppiamento primario energia funzionante!"

RadioRoomUnlock=ROBOT-GUIDA: "Energia ausiliaria dirottata verso il sistema trasferimento dati."

SecretArea=Hai trovato un'area segreta!

SecurityDoor=Accesso Sicurezza negato!

SuperIntro=Super Ladro

TempGetData=ROBOT-GUIDA: La cartuccia dati si trova in questo laboratorio!"

ThiefGotIt=ROBOT-GUIDA: "Il ladro ha rubato la cartuccia dati! Uccidilo e recuperala!"

Uploading=ROBOT-GUIDA: "Carico sulla cartuccia i dati relativi al virus!"

UploadNode=GUIDEBOT: "Questi nodi di caricamento trasferiranno i dati a qualsiasi dispositivo collocato tra di loro"

