//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     30

// Message List
CameraActivation=GUIDEBOT: "Transmitting security camera signal..."
ContainmentDoorUnlocked=Containment door unlocked.
Controller=GUIDEBOT: "Routing backup surface defenses to primary system!"
ControlVulnerable=GUIDEBOT: "The surface system primary controller is now vulnerable!"
CoolersAllGone=GUIDEBOT: "Main cooling system failure.  Activating emergency override cooling control."
DoThis=GUIDEBOT: "Find the virus samples and get out as quickly as possible!"
FFDisable1=GUIDEBOT: "Containment forcefields auxilary power shutdown!"
FFDisabled=GUIDEBOT: "Forcefields disabled!  Access to virus containment room granted."
FFKeyPickup=GUIDEBOT: "Authorization for security controls granted."
Finished=
IntroMessage=Asteroid Ceres - PTMC Secret | Research Bunker C4
MagnetActivated=GUIDEBOT: "Descending magnetic accelerator activated.  Security doors unlocked."
MagnetTube1=GUIDEBOT: "Control room lock 1 of 2 deactivated!"
MagnetTubeDoorUnlock=GUIDEBOT: "Control room access granted!  Door unlocked!"
ManualActivation=GUIDEBOT: "This device requires direct activation."
NeedFFKey=GUIDEBOT: "You are not authorized to use these controls."
PathEnd=EndLevel
SecretArea=You Found A Secret Area!
SteamRelease=GUIDEBOT: "Steam release activated."
SuperHeaterShutdown=GUIDEBOT: "Super heating virus containment device disabled."
TurretsDeactivated=GUIDEBOT: "Primary controls destroyed!  Surface defense systems disabled!"
TurretsInvuln=GUIDEBOT: "The large turrets are too tough to be blown away!  Find an alternate way to defeat them!"
UpperTubeActivate=GUIDEBOT: "Ascending accelerator tube activated."
Virus1Collected=You've got one virus!
Virus2Collected=Great work!  You've collected both virus samples.
VirusDescription=GUIDEBOT: "Collect both samples and get out quickly!"
