
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     51



// Message List

AftMatcenCheck=ROBOT-GUIDA: "Sto ispezionando la sezione di poppa del Matcen."

AftSwCinema=Disattivare la sezione di poppa del Matcen

AuxCoreDoor=ROBOT-GUIDA: "Accesso negato a blocco motore ausiliario. Trovare un'altra via!"

Bay62Door=ROBOT-GUIDA: "Porta d'accesso ad attracco 62 bloccata.  Trovare un'altra via!"

Bay62Fuse=ROBOT-GUIDA: "Attracco 62 Matcen disattivato."

Bay62Game=11:37.04.04.3750 LIBRO DI BORDO BADGE ID COMANDANTE M. KELLY 62 STORMO COMBATTIMENTO: "I nostri sforzi sono inutili. Sappiamo che hanno il controllo di almeno due caccia StarHawk! L'infezione si è diffusa ai meccanoidi operai... procedo all'evacuazione dei miei uomini."

Bay62Hud= Libro di bordo Attracco 62 scaricato... (MAIUSC-F8)

Bay62Lance=ROBOT-GUIDA: "Torrette disattivate."

BayInfoGame=07:02.04.04.3750: Consegna 432178a PTMC DeepSpace: "Ordine parti Matcen registrato a bordo."

BayInfoHud=Libro di bordo Attracco 36 scaricato... (MAIUSC-F8)

Cleanup=COMANDANTE CDT: "Eliminare assaltatori superstiti."

CoreAccFF=ROBOT-GUIDA: "Accesso al Nucleo protetto. Trovare un'altra via per entrare."

CoreInfo1=11:11:04.04.3750 Libro di bordo scaricato... (MAIUSC-F8)

CoreInfo2=11:11.04.04.3750  ALLARME INTRUSIONE! "Porta d'accesso N. 79.287 a nucleo motore disattivata da utente con Badge ID n. 80-84."

CoreRads=ROBOT-GUIDA: "Interferenza massa critica!"

DangerEngine=ROBOT-GUIDA: "ATTENZIONE! Area Carico Motore!"

EndCine=

EndMission=COMANDANTE CDT: "Avete annientato tutti gli assaltatori. Bel lavoro!"

EngineDown=ROBOT-GUIDA: "Obiettivo terziario completato! Esclusione nucleo motore."

EngineMisfire=ROBOT-GUIDA: "ATTENZIONE! ERRATO AZIONAMENTO MOTORE!"

EngineTakover=COMANDANTE CDT: "Gli assaltatori si sono impadroniti del Controllo Motori..."

GotReconInterface=Interfaccia ricognizione

IntroText=Orbita di Marte - Portanavi| ammiraglia Expediator del CDT

JeffriesID=ROBOT-GUIDA: "Tubo Jeffries di poppa. Da qui si può arrivare alla sezione di poppa."

LandingDoor62=ROBOT-GUIDA: "La porta principale di accesso all'attracco 62 è bloccata. Trovare un'altra via!"

LeaderCinema=Cercare e distruggere il comandante della Legione Vittoriosa

LeaderTaunt1=RADIO CDT: "Qui il comandante della Legione Vittoriosa..."

LeaderTaunt2=RADIO CDT: "Stiamo assumendo il controllo dell'Expediator."

LeaderTaunt3=CED RADIO: "Annienteremo qualsiasi unità che non si arrenda immediatamente."

LeaderTaunt4=RADIO CDT: "Non siamo feriti quindi con enfatizziamo."

LeaderTaunt5=CED RADIO: "Fermi....!"

LevelObjA=ROBOT-GUIDA: "Sei riuscito a disattivare il Matcen di poppa!"

LevelObjtives1=Obiettivi primari: | 1. DISATTIVARE MATCEN DI POPPA | Distruggere interruttore di rilevamento manuale

LevelObjtives2=2. Cerca e distruggi il| Comandante della Legione Vittoriosa.

LevelObjtives3=Neutralizzare minaccia di conquista ostile: | RIDURRE | Rosso, Verde, Bianco | LEGIONE TRUPPE D'ASSALTO DIFESA.

MainDeckGame=11:22.04.04.3750 STATO DELLA NAVE LIBRO DI BORDO CORAZZATA EXPEDIATOR DEL CDT: "Virus sconosciuto ha contaminato i sistemi difensivi della nave comprese unità TA. Abbiamo isolato tutta la sezione di poppa. Fortunatamente tutti hanno abbandonato la nave in tempo! Stiamo studiando le possibili soluzioni."

MainDeckHud= Libro di bordo astronave scaricato... (MAIUSC-F8)

NoEntry=QUARANTENA! Vietato procedere oltre questo punto.
NoEntry62=Questa Porta di Accesso all'Hangar è stata sigillata. Devi trovare un'altra via.
PplDoors1=L'accesso al personale è momentaneamente precluso.

PrimaryObjB=Comando CDT: "Congratulazioni! Hai portato a termine l'obiettivo secondario."

PrimerDamage=ROBOT-GUIDA: "Campo al plasma!! La nave ha subito danni."

RobotCount=Rimanangono ancora %d Assaltatori infetti!

SecondaryObjective=EMERGENZA!!! | MOTORE IN AVARIA...|

ShipInfo1=Libro di bordo astronave scaricato... 
(MAIUSC-F8)

ShipInfo2=10:59.04.04.3750: "Questa è una registrazione d'emergenza del macchinista capo di poppa Kalmer. Dopo avere montato le parti di ricambio ricevute con l'ordine 47632-09 il Matcen è condannato. Ora produce Assaltatori infetti! Impossibile escluderli!!! Stiamo facendo evacuare gli addetti alla riparazione."

SpyPlead=MECCANOIDE CACCIATORE: "Vi prego, se non mi uccidete non farò nulla. Io non sono come gli altri!"

StormtroopersCine=Fateli fuori...| Prima che loro facciano fuori voi!

