//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     52

// Message List
ActivatedMatcen=ROBOGUÍA: "Centro de materialización activado"
Arena1Defeated=ROBOGUÍA: "Combate de nivel 1 superado. Estás autorizado a pasar al nivel 2."
Arena1Enter=Combate de nivel 1| Prepárate para la lucha.
Arena2Defeated=ROBOGUÍA: "Combate de nivel 2 superado. Estás autorizado a pasar al nivel 3."
Arena2Enter=Combate de nivel 2| Prepárate para la lucha.
Arena3Defeated=ROBOGUÍA: "Combate de nivel 3 superado. Estás autorizado a pasar al nivel 4."
Arena3Enter=Combate de nivel 3| Prepárate para la lucha.
Arena4Defeated=ROBOGUÍA: "Combate de nivel 4 superado. Estás autorizado a pasar al campeonato."
Arena4Defeated2=ROBOGUÍA: "Es posible acceder a todas las zonas."
Arena4Enter=Combate de nivel 4| Prepárate para la lucha.
Arena4Enter2=2ª parte de combate de nivel 4| ¡Te espera una bonificación!
ArenaChamp=ROBOGUÍA: "Campeón del terreno de pruebas derrotado.  "Es posible acceder a la superficie."
CowFFDisable=ROBOGUÍA: "¡Secuencia de campo de fuerza completa!
CowPipeActive=ROBOGUÍA: "Generador de control activado."
DoorUnlocked=Puerta desbloqueada.
EmergencyOverride=ROBOGUÍA: "Anulación de emergencia activado. Todos los campos de fuerza de seguridad están desactivados."
EndBossBegin=Combate de campeonato| Prepárate para la lucha.
EndLevel=
EscapedDestroyed=ROBOGUÍA: "Aún falta un generador por destruir."
EscapedDestroyed2=ROBOGUÍA: "Has conseguido huir del mecanismo de retención."
EscapedTorture=ROBOGUÍA: "Mecanismo de tortura destruido."
EscapeTorture2=ROBOGUÍA: "Los generadores del campo de fuerza son ahora vulnerables."
Forcefield=Campos de fuerza desactivados.
GonnaClean=ADVERTENCIA: Generadores de control destruidos. Activando sistema de limpieza por calor.
Guards1=Un contendiente eliminado.
Guards2=Aún quedan dos contendientes por eliminar.
Guards3=Aún quedan un contendiente por eliminar.
IntroMessage=Charon: Terreno de pruebas del PTMC 
L1Door=Se necesita la llave del nivel 1.
L2Door=Se necesita la llave del nivel 2.
L3Door=Se necesita la llave del nivel 3.
L4Door=Se necesita la llave del nivel 4.
Level1Key=Llave del nivel 1
Level2Key=Llave del nivel 2
Level3Key=Llave del nivel 3
Level4Key=Llave del nivel 4
LevelStarted=ROBOGUÍA: "Ve al terreno de pruebas tan pronto como sea posible."  Es tu única posibilidad de escapatoria. Lucha para abrirte camino a la superficie."
MainFFDeactivated=ROBOGUÍA: "Principales competidores eliminados. El último competidor puede entrar en el campo de combate del campeonato."
MainGuards=ROBOGUÍA: "Tienes que eliminar a los contendientes para poder entrar en el campeonato."
RecoveredSecret=RECUPERADO: Cartucho de datos antiguo.  El Roboguía está buscando información...
RedUnitsArmed=ROBOGUÍA: "Unidades de control armadas y listas para la detonación."
RepairActivated=ROBOGUÍA: "Instalaciones de reparación reactivadas."
RepairDeactivated=ROBOGUÍA: "Instalaciones de reparación desactivadas."
RepairingShip=Reparando los escudos de la nave| energía restaurada al máximo.
SecretData=Este cartucho está bastante desgastado y muy oxidado, pero tu Roboguía consigue recuperar varios datos que pueden ser útiles. Están relacionados con una especie de complejo industrial secreto que no aparece en ninguna de tus cartas de navegación. Tal vez convenga comprobarlo más adelante.
SRepairInit=ROBOGUÍA: "Calibración de la unidad de reparación desactivada. Es necesario reinicializarla."
