
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     45



// Message List

1ReactorOn=GUIDEBOT: "Un réacteur sur cinq réactivé. Convertisseurs d'énergie disponibles."

BLANK=

Critical=Niveau Bouclier Critique !

DefendThoseReactors2=ACROPOLE ROUGE: "On nous attaque ! Protégez trois des cinq réacteurs jusqu'à notre signal.  Tous les personnels doivent rejoindre les navettes d'évacuation dans les douze prochaines minutes. Nous détruirons les réacteurs depuis l'orbite  dès que tout le monde sera à l'abri."

Destroyed=GUIDEBOT: "Réacteur Désactivé !"

EnergyConvertedToShields=GUIDEBOT: "Transfert d'énergie aux boucliers du réacteur !"

EnergytoShield=ACROPOLE ROUGE: "Vous trouverez un convertisseur d'énergie en bouclier sur chaque réacteur. Tirez dessus avec vos armes à énergie pour renforcer le bouclier d'un réacteur s'il est attaqué. Si vous avez besoin de plus d'énergie, il y a un centre d'énergie au milieu du tunnel 3."

EntranceDoorMessage=GUIDEBOT: "Verrouillage Sécurité de Secours de l'Acropole Rouge actif !"

ExitOnly=GUIDEBOT: "Sortie de Secours uniquement !"

GetThoseReactorsMore=ACROPOLE ROUGE: "Ici Harper.  Vous devez redémarrer les réacteurs. Touchez les pompes à Fusion à la base de chaque réacteur.  Il nous faut au moins 3 réacteurs en ligne pour pouvoir partir.  L'évacuation complète nous prendra à peu près 12 minutes - Donnez-nous du temps !"

Health25=Niveau Bouclier 25 %

Health50=Niveau Bouclier 50 %

Health75=Niveau Bouclier 70 %

HITPOINTS=Points Réacteur : %f

IncomingMessage=Message en provenance de l'Acropole Rouge... (SHIFT-F8)

IntroMessage=Mars - Centre de Recherches de l'Acropole Rouge|

OOPS=ACROPOLE ROUGE: "Nous perdons de la l'énergie sur tout le réseau ! Les systèmes d'évacuation de secours sont en panne ! Je crois qu'il n'y a plus rien à faire... sinon se rendre."

Reactor1Started=GUIDEBOT: "Le Réacteur 1 est maintenant opérationnel."

Reactor1Status=Statut Réacteur 1:

Reactor2Started=GUIDEBOT: "Le Réacteur 2 est maintenant opérationnel."

Reactor2Status=Statut Réacteur 2:

Reactor3Started=GUIDEBOT: Le Réacteur 3 est maintenant opérationnel."

Reactor3Status=Statut Réacteur 3:

Reactor4Started=GUIDEBOT: "Le Réacteur 4 est maintenant opérationnel."

Reactor4Status=Statut Réacteur 4:

Reactor5Started=GUIDEBOT: "Le Réacteur 5 est maintenant opérationnel."

Reactor5Status=Statut Réacteur 5 :

ReactorDisabled=GUIDEBOT: "Réacteur désactivé !"

ReactorsOnline=GUIDEBOT: "Les cinq réacteurs sont maintenant en ligne."

SelfDestruct=ACROPOLE ROUGE: "Nous commençons le compte à rebours avant l'auto-destruction des réacteurs. Vous avez quatre-vingt dix secondes pour vous mettre en lieu sûr avant leur fusion ! Evacuez !! IMMEDIATEMENT !!"

Shake=Nettoyez la mine !

ShieldsAtMax=GUIDEBOT: "Niveau Maximum des Boucliers atteint !"

StartTimer=Démarrez le Chrono maintenant !

Testing=Test !

WereGettinOut=ACROPOLE ROUGE: "Tous les agents sont présents, et les navettes ont reçu l'autorisation de décoller. Les réacteurs s'auto-détruiront dans 90 secondes alors ne traînons pas ! Vous devriez pouvoir trouver une sortie à partie du centre principal !"

30SecondsLeft=GUIDEBOT: "Plus que 30 secondes pour évacuer !  Vite !"

DefendReactorsShort=GUIDEBOT: "Protégez les réacteurs pendant 12 minutes et évacuez les lieux !"

ReactorHUDLabel=Réacteurs :

SelfDestruct=GUIDEBOT: "Ils en sont sortis vivants. Sortez d'ici avant que la séquence d'auto-destruction ne soit activée !"

