//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     57

// Message List
BLANK=
BossIntroductionText=Der Homunculus|
BuilderCollectorsCorrectlyPlaced=GUIDEBOT: "Eine Tür wurde entriegelt."
Builders3secondsleft=GUIDEBOT: "Sie haben noch 3 Sekunden übrig!"
BuildersDoorMessage=GUIDEBOT: "Als Bevollmächtigter der Sammler dürfen Sie passieren."
BuildersPuzzhint=GUIDEBOT: "Ventilationsschacht entdeckt."
BuildersPuzzMessage=GUIDEBOT: "Fliegen Sie schnell!"
BuildersPuzzMessage2=GUIDEBOT: "Das Baumeister-Symbol beendet den ausgewählten Pfad!"
BuildersTimerExpired=GUIDEBOT: "Die Zeit ist um!"
CollectorsDoorMessage=GUIDEBOT: "Als Bevollmächtigter der Baumeister dürfen Sie passieren."
EndPath=GUIDEBOT: "Ende des Pfads!"
EnterPriestPuzzle=GUIDEBOT: "Sie haben das Priesterrätsel betreten."
ExitPriestPuzzle=GUIDEBOT: "Sie haben das Priesterrätsel verlassen."
FirstPickupBuilder=Das Baumeister-Symbol
FirstPickupCollector=Das Sammler-Symbol
FirstPickupPriest=Das Priester-Symbol
IntroLevelMessage=Mars - Noctis Labyrinthus Schluchten|
InvGame=Mit den voreingestellten Standardtasten "Ü" und "+" können Sie Gegenstände aus dem Inventar auswählen.  Um einen Gegenstand zu benutzen, drücken Sie die Standardtaste "Eingabe".
InvHUD=GUIDEBOT: "Denken Sie daran, die Symbole aus Ihrem Inventar zu verwenden.... (SHIFT-F8)"
KeyAlreadyThere=GUIDEBOT: "Zwei in einem ergibt nicht drei..."
PlaceBuildersKey=GUIDEBOT: "Sie haben das Baumeister-Symbol plaziert."
PlaceCollectorsKey=GUIDEBOT: "Sie haben das Sammler-Symbol plaziert."
PlacePriestKey=GUIDEBOT: "Sie haben das Priester-Symbol plaziert."
PriestGalleryDoorLocked=GUIDEBOT: "Sie sind nicht würdig."
PriestHallDoorLocked=GUIDEBOT: "Der Hohe Priester wird Sie nicht einlassen!"
PriestKeyCorrectlyPlaced=GUIDEBOT: "Der Homunculus wartet!"
PriestPuzzleEnter=GUIDEBOT: "Zwischen den Säulen geht der Auserwählte Priester."
PriestPuzzleGoofed=GUIDEBOT: "Sie sind nicht der Auserwählte!"
PriestPuzzleSolved=GUIDEBOT: "Sie haben sich als würdig erwiesen!"
Test=Test
Testing=
ThisDoorDoesNotAnswer=GUIDEBOT: "Diese Tür reagiert nicht auf Sie."
TugMessage1=SCHLEPPSCHIFF: "Sieht so aus, als ob wir das Wrack gefunden haben.  Es scheint noch in ziemlich gutem Zustand zu sein."
TugMessage2= SCHLEPPSCHIFF: "Wir warten hier, bis Sie das Gebiet gesichert haben."
TugMessage3= SCHLEPPSCHIFF: "Uh, hier blockiert ein Kraftfeld unseren Weg -können Sie es so bald wie möglich deaktivieren?"
TugMessage4= SCHLEPPSCHIFF: "Sieht so aus, als ob Sie noch nicht ganz fertig sind!  Passen Sie auf!"
TugMessage5= SCHLEPPSCHIFF: "Beeilung, zerstören Sie das Ding, damit wir hier schnell rauskommen!"
TugMessage6= SCHLEPPSCHIFF: "O.K.! Dann lassen Sie uns mal die Kuh auf die Beine stellen."
TugMessageShipPickUp= SCHLEPPSCHIFF: "Alles klar.  Das Kraftfeld ist abgeschaltet. Wir greifen uns jetzt das Schiff."
TugMessageStart= SCHLEPPSCHIFF: "Von hier an sind Sie auf sich allein gestellt, Pilot..."
TugStartMessage2= SCHLEPPSCHIFF: "Wir halten Funkstille, bis wir uns ein Bild von der Absturzstelle gemacht haben."
XsecsOntheClock=GUIDEBOT: "%.0f Sekunden auf der Uhr!"
YoucantUseKeyHere=

