//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     27

// Message List
AccessDenied=GUIDEBOT: "Access Denied!  Pass Required."
Blank=
BossData=SUBJECT:  Advanced Assault Mech.  STATUS:  R&D deadlines met.  Production underway shortly.  NOTES:  (classified) Production numbers doubled as requested.  --SD
BothFireSwitches=GUIDEBOT: "Combustion Chamber deactivated."
CEDData=SUBJECT:  Collective Earth Defense Contract  STATUS:  Phoenix Interceptor contract fulfilled.  Blackshark Missile in development.  NOTES:  (classified)  New shipment to arrive as scheduled.  --SD
ClassifiedAccessPass=Restricted Access Passkey
ConsoleCrash=GUIDEBOT: "The system seems to have a non-recoverable error."
DravisData=SUBJECT:  Dravis, Samuel, Jr.  Director of Crisis Contingency Management & Public Relations  STATUS:  engaged in SRAD Press Tour  NOTES:  (classified) Requested promotion has been denied.  --Suzuki
EmergencySwitch=GUIDEBOT: "Emergency Release Switch currently locked."
EmergencySwitchOpen=GUIDEBOT: "Emergency Release Switch activated."
EndLevel=
FirstForcefield=Forcefield disabled!
IntroMessage=Deimos - PTMC Data Retention Center
LeftConsoleSwitch=GUIDEBOT: "Searching Production Schedule Database..."
LockDown=GUIDEBOT: "The facility has completed Security Lockdown!"
MDData=SUBJECT:  Material Defender ID No. 1032  STATUS:  MIA while in Tycho Brahe vicinity.  NOTES:  (classified)  Hardware failure of warp-core suspected.  --SD
PrimaryLoginSwitch=GUIDEBOT: "Searching Personnel Database..."
PTMCdisconnected=GUIDEBOT: "You have been DISCONNECTED..."
RightConsoleSwitch=GUIDEBOT: "Searching Administrative Files..."
SECRETAREA=You Found A Secret Area!
SecurityAlert=GUIDEBOT: "My unauthorized database access has been detected! Security measures have been activated!"
ShipMessageLog=Data transferred to Ship Message Log (SHIFT- F8)
SingleFireSwitch=GUIDEBOT: "Combustion Chamber switch triggered."
SRADLabData=NOTES:  Recent SRAD Lab accident responsible for death of 17 top scientists.  Dr. Sweitzer's employment terminated.  --SD
SweitzerData=SUBJECT:  Dr. Sweitzer, Karl  Chief Research Officer SRAD Laboratory on planet Tiris.  STATUS:  Terminated.  NOTES:  Serving time at Novak Corporate Prison on Phobos.  --SD
