
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     13



// Message List

BlueDoor=Vous n'avez pas la clé bleue !

BlueKeyFF=Champ de force de la clé bleue désactivé !

EndLevel=

FlameDeactivated=Salle de la Flamme désactivée !

IntroCam=Centre de Recherches sur les Armes à Haute Vélocité

NameBlueKey=Clé bleue

NameRedKey=Clé rouge

ReactorDestroyed=Réacteur primaire détruit ! Séquence d'auto-destruction activée !

ReactorFF=Champ de force du réacteur désactivé !

ReactorPrimed=GUIDEBOT: "Le Réacteur a désactivé ses propres systèmes de défense ! Achevez-le !"

RedDoor=Vous n'avez pas la clé rouge !

RedKeyFF=Champ de force de la clé rouge désactivé !

