//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     13

// Message List
BlueDoor=You do not have the Blue Key!
BlueKeyFF=Blue Key Forcefield deactivated!
EndLevel=
FlameDeactivated=Flame Chamber deactivated!
IntroCam=High Velocity Weapons Research Center
NameBlueKey=Blue Key
NameRedKey=Red Key
ReactorDestroyed=Primary Reactor destroyed!  Self-destruct sequence activated!
ReactorFF=Reactor Forcefield disabled!
ReactorPrimed=GUIDEBOT: "The reactor has disabled its own defenses!  Finish it off!"
RedDoor=You do not have the Red Key!
RedKeyFF=Red Key Forcefield deactivated!
