//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     38

// Message List
ALLHeatSinksDestroyed=GUIDEBOT: "All 3 Heat Sinks have been destroyed!  The Emergency Maintenance Access hatch is now unlocked!"
CenterClampDisengaged=GUIDEBOT: "Disengaging Bay 2 Docking Clamp.  Medical Frigate Nightingale present.  WARNING!  System Failure!  Unable to comply!"
ClampNotInUse=GUIDEBOT: "This Docking Clamp is not currently in use."
CoolFanDestroyed=GUIDEBOT: "Primary cooling network intake fan destroyed!"
CoolFanInvulnerable=GUIDEBOT: "Your weapons have no effect!"
CoolingSystemClock=GUIDEBOT: "Thermal Regulator clock has been engaged.  Unable to access until 32 hour cycle has completed."
CoolingSystemEngaged=GUIDEBOT: "Thermal Regulator engaged:  shutting down Steam Vents, and opening Heat Sink apertures."
CoreTempAboveNormal=GUIDEBOT: "Without the Cooling System intact, the Refinery Core temperature will rise indefinately."
CoreTempCritical=GUIDEBOT: "With its primary intake fan destroyed, the Refinery Core temperature rises slowly towards Critical."
DoorUnlocked=GUIDEBOT: "Nearby door unlocked!"
ElevatorAlreadyDown=GUIDEBOT: "The Hangar Elevator is already down."
ElevatorDOWN=GUIDEBOT: "Hangar Elevator descending."
ElevatorNeedsDown=FRIGATE:  "We're not going to make it out of here with that Elevator up!  Get to the Control Center pronto!"
EndLevel=
EngagingCenterClamp=GUIDEBOT: "Engaging Hangar Bay 2 Docking Clamp.  Medical Frigate Nightingale present.  WARNING!  System Failure!  Unable to comply!"
FanReverseSwitch=GUIDEBOT: "Cooling Intake Fan reversed."
ForcefieldDisabled=GUIDEBOT: "Forcefield Disabled!"
FoundSecretData=RECOVERED:  Damaged data cartridge... (SHIFT F8)
FrigateSaved=FRIGATE:  "Thanks for getting this clamp open.  No time to chat now... this place doesn't feel too stable!"
HeatSinkDestroyed=GUIDEBOT: "Cooling System Heat Sink destroyed!"
IntroCamera=Europa - PTMC Fuel Refinery Dol Ammad
Mayday=FRIGATE:  "Medical Frigate Nightingale to Hangar Control, requesting clearance for docking clamp release.  Repeat:  docking clamp 2 is still locked.  Need assistance for immediate departure."
MessageFromFrigate=Incoming Data Transmission from Medical Frigate...  SHIFT-F8
WeaponsPlantData=The cartridge is in pretty bad shape, but your Guidebot manages to extract a chunk of data  that may be useful.  The data refers to an SRAD Weapons Plant that isn't on any of the usual PTMC nav charts.  Definately could be worth a visit later.
