
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     33



// Message List

All4Radio=GUIDEBOT: "Liaison de données activée !"

All4Radio2=GUIDEBOT: "Vous devriez maintenant avoir accès à l'armurerie !"

DataFinal=GUIDEBOT: "La cartouche contient maintenant les données dont nous avons besoin ! Retournez dehors pour achever votre mission !"

DataNodes=GUIDEBOT: "Placez la cartouche de données entre les noeuds de transfert !"

DataOriginal=GUIDEBOT: "La cartouche est vide !  Trouvez les noeuds de chargement de données et placez-y la cartouche !"

DestroyedSuper=GUIDEBOT: "Le SuperVoleur est détruit !  La cartouche devrait contenir les données maintenant !"

DestroyedThief=GUIDEBOT: "Voleur détruit !  Récupérez la cartouche de données !"

EndLevel=Données des recherches du Dr. Sweitzer récupérées.

FalseTransfer=GUIDEBOT: "Impossible de faire le transfert : il n'y a pas de cartouche !"

ForceFieldDeactivated=Champ de force désactivé !

IntroMessage=Tiris - Station Piccu de la PTMC | & Laboratoire Beta Ceti de la DARS

KillSuper=GUIDEBOT: "Détruisez le SuperVoleur et récupérez la cartouche de données !"

LTSelfDestruct=GUIDEBOT: "La tour antifoudre ne peut plus se décharger et s'auto-détruit !"

MainKeyCard=Clé Sécurité

PlaceCartridge=GUIDEBOT: "La cartouche de données est prête pour le transfert !  Trouvez les commandes de données !"

RadioRoomFirst=GUIDEBOT: "Couplage de l'alimentation primaire engagé !"

RadioRoomUnlock=GUIDEBOT: "Alimentation auxiliaire renvoyée sur système de liaison."

SecretArea=Vous avez trouvé une zone secrète !

SecurityDoor=Accès refusé !

SuperIntro=SuperVoleur

TempGetData=GUIDEBOT: "La cartouche de données est quelque part dans ce labo !"

ThiefGotIt=GUIDEBOT: "Le voleur a dérobé la cartouche de données ! Tuez-le pour la récupérer !"

Uploading=GUIDEBOT: "Transfert des données sur le virus dans la cartouche !"

UploadNode=GUIDEBOT: "Ces noeuds transféreront les données à n'importe quel dispositif placé entre eux."

