//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     59

// Message List
BeamIgnited=ROBOGUÍA: "Has encendido el rayo transmisor. Protege la transmisión hasta que termine."
BeamIgniteError1=ROBOGUÍA: "ERROR: El sistema de transmisión está desconectado."
BeamIgniteError2=ROBOGUÍA: "ERROR: No se han cargado datos."
BeamIgniteError3=ROBOGUÍA: "ERROR: El suministro eléctrico es insuficiente."
BeamIgniteError4=ROBOGUÍA: "ERROR: El transmisor de la red de defensa está desconectado."
BeamIgniteError5=ROBOGUÍA: "ERROR: El escudo del haz está activado."
BeamIgniteError6=ROBOGUÍA: "ERROR: Detectados nodos de espejo mal alineados."
BumpDialError=ROBOGUÍA: "ERROR: El sistema de transmisión está apagado."
BypassConnDisplay=Conectores de paso: %d
DataLinkAlreadyActive=ROBOGUÍA: "Este vínculo de datos funciona correctamente."
DataLinkError=ROBOGUÍA: "ERROR: No es posible pasar por alto los sistemas infectados."
DataLinkFixed=ROBOGUÍA: "Se ha utilizado un conector de puente para reparar este vínculo de datos."
DialCodeEntered=ROBOGUÍA: "Código de marcado aceptado... La salida de la red de defensa está activada."
DialCodeIncorrect=ROBOGUÍA: "ERROR: El código de marcado es incorrecto."
DialSwitchError=ROBOGUÍA: "ERROR: El sistema de transmisión está apagado."
Empty=
FoundAllBypassConns=ROBOGUÍA: "Todos los conectores de puente recuperados."
FoundBypassConn=Conector de puente
FoundEquipRmKey=Llave de la sala de equipo
GotCoreMaterial=Programa antivirus
GotSpareLens=Lente de transmisión de repuesto
IntroText=Órbita de la Tierra - Plataforma de operaciones estratégicas del CED
JournalBeamGame=DIARIO: "¡Y hay trabajadores nuevos que piensan que tienen mala suerte! El primer día me han puesto de servicio en el encendido del haz. Por supuesto, no se les ha ocurrido decirme dónde está el interruptor. He pasado una hora buscándolo hasta que alguien me ha dicho: "Recuerda para quién trabajas."
JournalBeamHUD=Se ha encontrado el diario del controlador del haz... (MAYÚS+F8)
JournalDialGame=INFORME: "El nuevo sistema de selección de salida de transmisión está listo. Nos permite dirigir nuestras transmisiones de datos a una red en concreto. El mecanismo de selección es un marcador circular que se encuentra en la parte inferior de la sala de ingeniería."
JournalDialHUD=Se ha encontrado un informe de la sala de ingeniería... (MAYÚS+F8)
JournalPowerGame=DIARIO: "Después del incidente de anoche, desconecté la alimentación eléctrica de la estación. Esto detuvo la producción de más robots infectados, pero también impidió que funcionara el emisor de haz. Tendremos que volver a conectar la alimentación más tarde o más temprano..."
JournalPowerHUD=Se ha encontrado el diario del ingeniero de la estación... (MAYÚS+F8)
JournalRobotGame=DIARIO: "La última vez que intentamos transmitir, un robot infectado estuvo a punto de quitar la lente. Ni que decir tiene que he encargado unas contramedidas Gunboy."
JournalRobotHUD=Se ha encontrado el diario de seguridad del haz... (MAYÚS+F8)
JournalShieldGame=CÓDIGO: "La siguiente secuencia de desactivación del haz esta codificada con arreglo a lo establecido en la directiva S897 del CED:  NO - SE - O - NE."
JournalShieldHUD=Recibido el código de desactivación de escudos del haz... (MAYÚS+F8)
JournalVirusGame=DIARIO: "Hoy he intentado arreglar uno de los vínculos de datos defectuosos. Parece que está infectado con un virus... pero no se parece a nada de lo que había visto hasta ahora. No quiero ni pensar en lo que ocurriría si se extendiera por los sistemas robóticos de trabajo y seguridad.
JournalVirusHUD=Encontrado el diario del técnico de datos...  (MAYÚS+F8)
LensDestroyed=ROBOGUÍA: "¡El robot ha destruido la lente! Habrá que cambiarla."
LensRobotWarning=ROBOGUÍA: "Un robot se dirige hacia la lente."
MirrorNodesUnaligned=ROBOGUÍA: "Los nodos de espejo han perdido la alineación."
OmnicronDisplayed=ROBOGUÍA: "Carga completa. Esperando selección de transmisor..."
PowerInsufficient=ROBOGUÍA: "El suministro eléctrico que recibe el encendido del haz es insuficiente."
PowerOffline=El suministro eléctrico %d está desconectado.
PowerOnline=El suministro eléctrico %d está conectado.
ShieldCodeIncorrect=ROBOGUÍA: "ERROR: Secuencia de código de escudo incorrecta."
ShieldCodeSeqReset=ROBOGUÍA: "Ha terminado el intervalo para introducir la secuencia de código."
ShieldCodeSeqStart=ROBOGUÍA: "Activada la secuencia de desactivación de escudos del haz. Tienes 15 segundos."
ShieldDeactivated=ROBOGUÍA: "Este escudo de haz está desactivado."
ShuttleFreed=ROBOGUÍA: "Has liberado la lanzadera de escape."
SystemStarted=ROBOGUÍA: "El sistema de transmisión está listo."
SystemStarting=ROBOGUÍA: "El sistema de transmisión se está iniciando."
TransmissionComplete=ROBOGUÍA: "Se ha transmitido el programa de antivirus. ¡Buen trabajo."
UploadError=ROBOGUÍA: "ERROR: El sistema de transmisión está desconectado."
UploadStarted=ROBOGUÍA: "Cargando el programa de antivirus en el sistema de transmisión."
UseCoreMaterialFailed=ROBOGUÍA: "Es necesario cargar el programa antivirus en el vínculo de datos."
UseLensCompleted=ROBOGUÍA: "La lente de repuesto está colocada. Reanudando la transmisión..."
UseLensFailed1=ROBOGUÍA: "Estás demasiado lejos para colocar la lente."
UseLensFailed2=ROBOGUÍA: "Ya hay una lente colocada."
