//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     45

// Message List
BLANK=
CenterLavaCrank=ROBOGUÍA: "Bomba de lava central activada."
DravisDoor=Puerta de la caja fuerte de Dravis abierta.
End=
EnergyCenterBroken=ROBOGUÍA: "El centro de energía no funciona a causa de la falta de suministro eléctrico."
EnergyCentersOnline=ROBOGUÍA: "Todos los centros de energía están conectados."
FuseFound=Fusible del reactor de reserva
HellionIntroduction=Mecanismo de asalto avanzado Hellion.
InnerDoorsDenied=ROBOGUÍA: "Acceso a la caja fuerte interior denegado. Es necesario un pase."
InnerDoorsUnlock=ROBOGUÍA: "Ahora tienes acceso a la caja fuerte interior."
InnerStrongholdKey=Llave de la caja fuerte interior
IntroCameraText=Venus - Caja fuerte de Dravis
LeftLavaCrank=ROBOGUÍA: "Bomba de lava izquierda activada."
MagicMatCenSwitches=ROBOGUÍA: "Los MatCen de seguridad de los cinco sectores perimétricos están desactivados. "Es posible acceder al arsenal."
MatCenSwitchAOff=ROBOGUÍA: "Reducida la alimentación de los MatCen de seguridad 1 y 5."
MatCenSwitchAOn=ROBOGUÍA: "Aumentada la alimentación de los MatCen de seguridad 1 y 5."
MatCenSwitchBOff=ROBOGUÍA: "Reducida la alimentación de los MatCen de seguridad 4 y 5. MatCen de seguridad 3 activado."
MatCenSwitchBOn=ROBOGUÍA: "Aumentada la alimentación de los MatCen de seguridad 4 y 5. MatCen de seguridad 3 desactivado."
MatCenSwitchCOff=ROBOGUÍA: "Reducida la alimentación del MatCen de seguridad 3."  MatCen de seguridad 2 activado."
MatCenSwitchCOn=ROBOGUÍA: "Aumentada la alimentación del MatCen de seguridad 3.  MatCen de seguridad 2 desactivado."
MatCenSwitchDOff=ROBOGUÍA: "MatCen de seguridad 5 activado."
MatCenSwitchDOn=ROBOGUÍA: "MatCen de seguridad 5 desactivado."
MatCenSwitchEOff=ROBOGUÍA: "Reducida la alimentación de los MatCen de seguridad 2 y 3. MatCen de seguridad 1 activado."
MatCenSwitchEOn=ROBOGUÍA: "Aumentada la alimentación de los MatCen de seguridad 2 y 3. MatCen de seguridad 1 desactivado."
MatCenSwitchFOff=ROBOGUÍA: "Reducida la alimentación de los MatCen de seguridad 2 y 4."
MatCenSwitchFOn=ROBOGUÍA: "Aumentada la alimentación de los MatCen de seguridad 2 y 4."
MatCenSwitchGOff=ROBOGUÍA: "Reducida la alimentación del MatCen de seguridad 5."  MatCen de seguridad 4 activado."
MatCenSwitchGOn=ROBOGUÍA: "Aumentada la alimentación del MatCen de seguridad 5.  MatCen de seguridad 4 desactivado."
PowerRestored=ROBOGUÍA: "Sustituido el fusible de reserva del reactor.  Restablecido el suministro eléctrico de los centros de energía."
ReactorBroken=ROBOGUÍA: "Este reactor necesita un fusible nuevo. El fusible que tiene colocado está fundido."
RightLavaCrank=ROBOGUÍA: "Bomba de lava derecha activada."
TNTDispenserCenter=ROBOGUÍA: "Produciendo explosivo para minería de rendimiento medio."
TNTDispenserLeft=ROBOGUÍA: "Produciendo explosivo para minería de rendimiento bajo."
TNTDispenserLeftBroken=ROBOGUÍA: "Es imposible reparar este mecanismo."
TNTDispenserRight=ROBOGUÍA: "Produciendo explosivo para minería de rendimiento alto."
TNTElevatorActivated=ROBOGUÍA: "Ascensor activado."
TNTRockWall=ROBOGUÍA: "Tus armas no pueden derribar esos obstáculos."
TNTRockwalldestroyed=ROBOGUÍA: "Se ha abierto una entrada."
