//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     57

// Message List
BLANK=
BossIntroductionText=The Homunculus|
BuilderCollectorsCorrectlyPlaced=GUIDEBOT: "A door has been unlocked."
Builders3secondsleft=GUIDEBOT: "You've got 3 seconds left!"
BuildersDoorMessage=GUIDEBOT: "As an Agent of the Collectors, you may pass."
BuildersPuzzhint=GUIDEBOT: "Ventilation shaft detected."
BuildersPuzzMessage=GUIDEBOT: "Fly fast!"
BuildersPuzzMessage2=GUIDEBOT: "The Builders' Icon ends the chosen path!"
BuildersTimerExpired=GUIDEBOT: "Time's up!"
CollectorsDoorMessage=GUIDEBOT: "As an Agent of the Builders, you may pass."
EndPath=GUIDEBOT: "End of Path!"
EnterPriestPuzzle=GUIDEBOT: "You Have Entered The Priest's Puzzle."
ExitPriestPuzzle=GUIDEBOT: "You have left The Priest's Puzzle."
FirstPickupBuilder=The Builders' Icon
FirstPickupCollector=The Collectors' Icon
FirstPickupPriest=The Priest's Icon
IntroLevelMessage=Mars - Noctis Labyrinthus Canyons|
InvGame=You can select items in the inventory using the default controls, [ and ].  To use or deploy an item, the default control is \.
InvHUD=GUIDEBOT: "Remember to use your inventory with the icons.... SHIFT-F8."
KeyAlreadyThere=GUIDEBOT: "Two in one does not make three..."
PlaceBuildersKey=GUIDEBOT: "You have placed the Builders' Icon."
PlaceCollectorsKey=GUIDEBOT: "You have placed the Collectors' Icon."
PlacePriestKey=GUIDEBOT: "You have placed the Priests' Icon."
PriestGalleryDoorLocked=GUIDEBOT: "You are not worthy."
PriestHallDoorLocked=GUIDEBOT: "The High Priest won't let you enter!"
PriestKeyCorrectlyPlaced=GUIDEBOT: "The Homunculus awaits!"
PriestPuzzleEnter=GUIDEBOT: "Among the columns walks the Chosen Priest."
PriestPuzzleGoofed=GUIDEBOT: "You are not The Chosen!"
PriestPuzzleSolved=GUIDEBOT: "You have proven yourself worthy!"
Test=Test
Testing=
ThisDoorDoesNotAnswer=GUIDEBOT: "This door does not answer to you."
TugMessage1=TUGSHIP: "Looks like we've found the wreckage.  Seems in pretty good shape from here."
TugMessage2=TUGSHIP: "We'll wait here while you secure the area."
TugMessage3=TUGSHIP: "Uh, we've got a forcefield blocking our path here--can you disable it anytime soon?"
TugMessage4=TUGSHIP: "Looks like you're not done yet!  Watch out!"
TugMessage5=TUGSHIP: "Hurry up and destroy that thing so we can get the Hell out of here!"
TugMessage6=TUGSHIP: "Alright, now let's get this show on the road."
TugMessageShipPickUp=TUGSHIP: "Roger that.  The forcefield is down. We're  gonna go grab that ship."
TugMessageStart=TUGSHIP: "You're on your own from here pilot..."
TugStartMessage2=TUGSHIP: "We'll keep radio silence until we get a visual on the crash site."
XsecsOntheClock=GUIDEBOT: "%.0f seconds on the clock!"
YoucantUseKeyHere=
