//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     13

// Message List
BlueDoor=Sie haben den blauen Schlüssel nicht!
BlueKeyFF='Blauer Schlüssel'-Kraftfeld deaktiviert!
EndLevel=
FlameDeactivated=Brennkammer deaktiviert!
IntroCam=Forschungszentrum für Hochgeschwindigkeitswaffen 
NameBlueKey=Blauer Schlüssel
NameRedKey=Roter Schlüssel 
ReactorDestroyed=Primärreaktor zerstört! Selbstzerstörungssequenz aktiviert!
ReactorFF=Reaktorkraftfeld entschärft!
ReactorPrimed=GUIDEBOT: "Der Reaktor hat seine eigene Abwehr ausser Kraft gesetzt!  Zerstören Sie ihn!"
RedDoor=Sie haben den roten Schlüssel nicht!
RedKeyFF='Roter Schlüssel'-Kraftfeld deaktiviert!
