//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     45

// Message List
1ReactorOn=GUIDEBOT: "Einer von 5 Reaktoren wiederhergestellt. Energieumwandler verfügbar."
BLANK=
Critical=Schutzschildlevel kritisch!
DefendThoseReactors2=ROTE AKROPOLIS: "Wir stehen unter Beschuss! Verteidigen Sie drei von den fünf Reaktoren, bis wir unser Signal geben.  Das gesamte Personal sollte die Evakuierungs-Shuttle in den nächsten 12 Minuten erreicht haben.  Wir werden die Reaktoren vom Orbit aus in die Luft jagen, um jegliche Beweise zu zerstören."
Destroyed=GUIDEBOT: "Reaktor ist funktionsuntüchtig!"
EnergyConvertedToShields=GUIDEBOT: "Transferiere Energie an die Schutzschilde des Reaktors!"
EnergytoShield=ROTE AKROPOLIS: "Jeder Reaktor verfügt über einen eingebauten Energie-zu-Schutzschild-Umformer. Feuern Sie Ihre Energiewaffen auf den Reaktor, um seinen Schutzschild zu verstärken, falls er angegriffen wird. Sollten Sie mehr Energie benötigen: in der Mitte von Tunnel 3 befindet sich ein Energiezentrum."
EntranceDoorMessage=GUIDEBOT: "Rote Akropolis-Notfall-Sicherheitsabschaltung ist in Kraft!"
ExitOnly=GUIDEBOT: "Nur Notausgang!"
GetThoseReactorsMore=ROTE AKROPOLIS: "Harper hier. Sie müssen die Reaktoren neu starten. Aktivieren Sie  die Fusionspumpen, die sich neben eines jeden Reaktors befinden. Mindestens 3 Reaktoren müssen am Netz sein, um die erforderliche Energie für die Evakuierung zu liefern.  In circa 12 Minuten sollte die gesamte Evakuierung abgeschlossen sein - versuchen Sie, uns etwas Zeit zu verschaffen!"
Health25=25 Prozent Schutzschildlevel...
Health50=50 Prozent Schutzschildlevel...
Health75=75 Prozent Schutzschildlevel...
HITPOINTS=Reaktortreffer : %f
IncomingMessage=Eingehende Nachricht von der Roten Akropolis... (SHIFT - F8)
IntroMessage=Mars - Rote Akropolis Forschungszentrum|
OOPS=RED ACROPOLIS: "Das gesamte Versorgungsnetz verliert an Energie!  Die Notfall-Evakuierungssysteme versagen!   Ich fürchte, uns bleibt nichts anderes übrig... wir müssen uns ergeben."
Reactor1Started=GUIDEBOT: "Reaktor 1 ist jetzt in Betrieb."
Reactor1Status=Reaktor 1 Status :
Reactor2Started=GUIDEBOT: "Reaktor 2 ist jetzt in Betrieb."
Reactor2Status=Reaktor 2 Status :
Reactor3Started=GUIDEBOT: "Reaktor 3 ist jetzt in Betrieb."
Reactor3Status=Reaktor 3 Status :
Reactor4Started=GUIDEBOT: "Reaktor 4 ist jetzt in Betrieb."
Reactor4Status=Reaktor 4 Status :
Reactor5Started=GUIDEBOT: "Reaktor 5 ist jetzt in Betrieb."
Reactor5Status=Reaktor 5 Status :
ReactorDisabled=GUIDEBOT: "Reaktor ist funktionsuntüchtig!"
ReactorsOnline=GUIDEBOT: "Alle 5 Reaktoren sind jetzt am Netz."
SelfDestruct=ROTE AKROPOLIS: "Wir initialisieren den Countdown zur Spregung der Reaktoren.  Sie haben 90 Sekunden, um den Mindestsicherheitsabstand zu erreichen, bevor es kritisch wird!  Kommen Sie da raus!  SOFORT!!"
Shake=Erschüttere die Mine!
ShieldsAtMax=GUIDEBOT: "Maximaler Schutzschildlevel erreicht!"
StartTimer=Zeitauslöser hier starten!
Testing=Test!
WereGettinOut=ROTE AKROPOLIS: "Gute Arbeit!  Das ganze Personal ist vollzählig, und die Shuttles sind startbereit.  Die Reaktoren werden sich in 90 Sekunden selbst zerstören, also sehen Sie zu, dass Sie da schnellstens rauskommen. Fliegen Sie zurück zum Zentralraum, um den Ausgang zu finden!"
30SecondsLeft=GUIDEBOT: "Es bleiben nur 30 Sekunden für die Evakuierung! Beeilung!"
DefendReactorsShort=GUIDEBOT: "Verteidigen Sie die Reaktoren für 12 Minuten! Flüchten Sie sofort danach!"
ReactorHUDLabel=Reaktoren:
SelfDestruct=GUIDEBOT: "Alle sind sicher rausgekommen.  Gelangen Sie zum Ausgang, bevor sich die Selbstzerstörungssequenz aktiviert!"





