//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     59

// Message List
BeamIgnited=GUIDEBOT: "Vous avez activé le faisceau émetteur !  Protégez l'émission jusqu'au boutà son achèvement..."
BeamIgniteError1=GUIDEBOT: "ERREUR: Le Système Transmetteur est déconnecté."
BeamIgniteError2=GUIDEBOT: "ERREUR: Aucune donnée à transmettretransmise."
BeamIgniteError3=GUIDEBOT: "ERREUR: Alimentation fournie insuffisante."
BeamIgniteError4=GUIDEBOT: "ERREUR: Transmetteur Réseau Défense déconnecté."
BeamIgniteError5=GUIDEBOT: "ERREUR: Bouclier Faisceau actif."
BeamIgniteError6=GUIDEBOT: "ERREUR: détection de nNoeœud(s) miroir(s) mal aligné(s) détecté(s)."
BumpDialError=GUIDEBOT: "ERREUR: Système de Transmission en panne..."
BypassConnDisplay=Circuits de dérivation: %d
DataLinkAlreadyActive=GUIDEBOT: "Cette Liaison de Données fonctionne désormais maintenant normalement."
DataLinkError=GUIDEBOT: "ERREUR: Impossible de contourner le(s) système(s) infecté(s)."
DataLinkFixed=GUIDEBOT: "Vous avez utilisé un Connecteur de Dérivation pour réparer cette Liaison de Données ."
DialCodeEntered=GUIDEBOT: "Code de Connexion accepté... ... Sortie Réseau Défense activée."
DialCodeIncorrect=GUIDEBOT: "ERREUR: Code de Connexion incorrect."
DialSwitchError=GUIDEBOT: "ERREUR: Système de Transmission en panne..."
Empty=
FoundAllBypassConns=GUIDEBOT: "Tous les Connecteurs de Dérivation sont récupérés."
FoundBypassConn=Connecteur de Dérivation
FoundEquipRmKey=Clé de la sSalle d'Equipement
GotCoreMaterial=Logiciel Anti-Virus
GotSpareLens=Lentille d'Emetteur de Rechange
IntroText=Orbite Terrestre - Plate-Forme des Opérations Stratégiques de lau CDT
JournalBeamGame=JOURNAL: "Certains des bleus pensent qu'ils n'ont pas de chance. Pour mon premier jour, moi, j'ai dû bosser sur l'Activation Faisceau. Bien sûr, ils ne m'ont pas dit où était l'interrupteur. J'ai cherché pendant une heure avant que quelqu'un me dise, "rappelle-toi pour qui tu travailles. "
JournalBeamHUD=Trouvé: Trouvé le Journal du Contrôleur deu Faisceau... (SHIFT+ - F8)
JournalDialGame=REPORT: "Le nouveau Système de Sélection de Sortie du Transmetteur est prêt. Il nous permet de cibler un réseau particulier avec nos émissions de données. Le mécanisme de sélection est un cadran comme celui d'unede type horloge dans la sSalle d'Ingénieurie technique inférieure."
JournalDialHUD=Trouvé: Trouvé Rapport de la Salle d'IngénieurieTechnique... (SHIFT+ - F8)
JournalPowerGame=JOURNAL: "Après l'incident de la nuit dernière, j'ai déconnecté l'Alimentation de la Station. Cela a stoppé la génération de robots infectés supplémentaires, mais cela veut aussi dire que l'émetteur de faisceaux ne fonctionne plus. On devra remettre le courant tôt ou tard..."
JournalPowerHUD=Trouvé: le Journal de l'Ingénieur de la Station... (SHIFT+F8)
JournalRobotGame=JOURNAL: "La dernière fois que nous avons essayé d'émettreLors de notre dernière tentative d'émission, un robot infecté nous a quasiment volé lae lentille de l'émetteur! J'ai évidemment tout de suite fait une demande pour des GunBoys Gunboys..."
JournalRobotHUD=Trouvé: Trouvé Journal de la Sécurité Faisceau... (SHIFT+F8)
JournalShieldGame=CODE: "La Séquence de Désactivation du Bouclier du Faisceau est encodée selon la réglementation CDT S897 de la u CDT:  NO - SE - O - NE."
JournalShieldHUD=Code de Désactivation du Bouclier du Faisceau reçu. (SHIFT+F8)
JournalVirusGame=JOURNAL: "Aujourd'hui j'ai essayé de réparer une Liaison de Données qui faisait des siennes. En fait, On s'est aperçu qu'elle était infectée par un virus...... mais c'est au-delà toutça dépasse tout ce que j'ai jamais vu. Je n'ose pas imaginer aime pas penser à ce qui arriverait si ça contaminait aussi les systèmesles ro bots ouvriers et ceux de la sécurité et de travail..."
JournalVirusHUD=Trouvé: Trouvé Journal du Technicien de données...  (SHIFT+F8SHIFT - F8)
LensDestroyed=GUIDEBOT: "Le robot a détruit la lentille ! Vous allez devoirIl vous faut la remplacer..."
LensRobotWarning=GUIDEBOT: "Un robot se dirige vers la lentille !"
MirrorNodesUnaligned=GUIDEBOT: "Les noeœuds miroirs ne sont plus alignés  maintenant!"
OmnicronDisplayed=GUIDEBOT: "Transfert achevé. Attente sélection Transmetteur..."
PowerInsufficient=GUIDEBOT: "La puissance fournie à l'activateur de rayon n'est plus suffisante !"
PowerOffline=L'Alimentation %d est maintenant déconnectée.
PowerOnline=L'Alimentation %d est maintenant connectée.
ShieldCodeIncorrect=GUIDEBOT: "ERREUR: séquence code bouclier incorrecte."
ShieldCodeSeqReset=GUIDEBOT: "Le temps délai pour entrerde saisie de la séquence codée est expiré."
ShieldCodeSeqStart=GUIDEBOT: "Séquence de Désactivation du Bouclier du Faisceau Initialisée. Vous avez 15 secondes."
ShieldDeactivated=GUIDEBOT: "Le Bouclier du Rayon a été désactivé !"
ShuttleFreed=GUIDEBOT: "Vous avez libéré la navette de sauvetage !"
SystemStarted=GUIDEBOT: "Le Système de Transmission est prêt."
SystemStarting=GUIDEBOT: "Le Système de Transmission est en phase de démarrage !"
TransmissionComplete=GUIDEBOT: "L'Anti-Virus a été transmis . Bon Travail!"
UploadError=GUIDEBOT: "ERREUR: Système de Transmission Déconnecté."
UploadStarted=GUIDEBOT: "Transfert Code Anti--Virus au Système de Transmission..."
UseCoreMaterialFailed=GUIDEBOT: "Vous devez transférer l'Anti-Virus sur une Liaison de Données."
UseLensCompleted=GUIDEBOT: "La lentille de rechange est positionnéeen place ! Reprise de la transmission..."
UseLensFailed1=GUIDEBOT: Vous êtes etes trop loin pour placer la lentille !"
UseLensFailed2=GUIDEBOT: "Il y a déjà une lentille  en place!"

