//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     52

// Message List
ActivatedMatcen=GUIDEBOT: "Materialisierungszentrum aktiviert!"
Arena1Defeated=GUIDEBOT: "Level 1-Arena erobert.  Sie sind befugt, sich zu Level 2 zu begeben!"
Arena1Enter=Level 1-Arena| Fertig machen zum Kampf!
Arena2Defeated=GUIDEBOT: "Level 2-Arena erobert.  Sie sind befugt, sich zu Level 3 zu begeben!"
Arena2Enter=Level 2-Arena| Fertig machen zum Kampf!
Arena3Defeated=GUIDEBOT: "Level 3-Arena erobert.  Sie sind befugt, sich zu Level 4 zu begeben!"
Arena3Enter=Level 3-Arena| Fertig machen zum Kampf!
Arena4Defeated=GUIDEBOT: "Level 4-Arena erobert.  Sie sind befugt, sich zur Meisterschafts-Arena zu begeben!"
Arena4Defeated2=GUIDEBOT: "Zugang zu allen Bereichen gewährt!"
Arena4Enter=Level 4-Arena| Fertig machen zum Kampf!
Arena4Enter2=Level 4-Arena Teil 2| Ein Bonus wartet!
ArenaChamp=GUIDEBOT: "Testgelände-Champion besiegt!  Zugang zur Oberfläche gewährt!"
CowFFDisable=GUIDEBOT: "Kraftfeldfolge abgeschlossen!"
CowPipeActive=GUIDEBOT: "Kontrollgenerator aktiviert!"
DoorUnlocked=Tür entriegelt!
EmergencyOverride=GUIDEBOT: "Notfallumgehung aktiviert.  Alle Sicherheitskraftfelder deaktiviert."
EndBossBegin=Meisterschafts-Arena| Fertig machen zum Kampf!
EndLevel=
EscapedDestroyed=GUIDEBOT: "Noch ein Generator zum Zerstören übrig!"
EscapedDestroyed2=GUIDEBOT: "Sie sind dem Haltemechanismus erfolgreich entkommen!"
EscapedTorture=GUIDEBOT: "Foltermechanismus zerstört!"
EscapeTorture2=GUIDEBOT: "Die Kraftfeldgeneratoren sollten jetzt angreifbar sein!"
Forcefield=Kraftfelder deaktiviert!
GonnaClean=WARNUNG: Kontrollgeneratoren zerstört!  Wärmesäuberungssystem wird aktiviert!
Guards1=Ein Konkurrent eliminiert!
Guards2=Noch zwei Konkurrenten eliminieren!
Guards3=Noch einen Konkurrenten eliminieren!
IntroMessage=Charon - PTMC-Testgelände
L1Door=Level 1--Schlüssel wird benötigt!
L2Door=Level 2--Schlüssel wird benötigt!
L3Door=Level 3--Schlüssel wird benötigt!
L4Door=Level 4--Schlüssel wird benötigt!
Level1Key=Level 1--Schlüssel
Level2Key=Level 2--Schlüssel 
Level3Key=Level 3--Schlüssel 
Level4Key=Level 4--Schlüssel 
LevelStarted=GUIDEBOT: "Begeben Sie sich so schnell wie möglich zum Testgelände!  Das ist Ihre einzige Fluchtchance!  Kämpfen Sie sich an die Oberfläche zurück!"
MainFFDeactivated=GUIDEBOT: "Hauptkonkurrenten eliminiert.  Der letzte Konkurrent wird jetzt die Meisterschafts-Arena betreten!"
MainGuards=GUIDEBOT: "Sie müssen die Konkurrenten eliminieren, damit Sie sich für die Meisterschafts-Arena qualifizieren!"
RecoveredSecret=WIEDERGEFUNDEN: Alte Datenkassette.  Guide-Bot tastet nach Informationen ab...
RedUnitsArmed=GUIDEBOT: "Kontrolleinheiten bewaffnet und bereit zum Detonieren!"
RepairActivated=GUIDEBOT: "Reparatureinrichtungen reaktiviert!"
RepairDeactivated=GUIDEBOT: "Reparatureinrichtungen deaktiviert!"
RepairingShip=Repariere die Schutzschilde Ihres| Schiffes bis zur vollen Stärke!
SecretData=Diese Kassette ist ziemlich abgenutzt und stark verrostet, aber Ihr Guide-Bot hat es geschafft, Daten zu extrahieren, die möglicherweise brauchbar sind. Sie deuten auf eine Art versteckten Industriekomplex, der auf keiner Ihrer Navigationskarten auftaucht, hin. Es könnte nützlich sein, das später zu prüfen.
SRepairInit=GUIDEBOT: "Kalibrierung der Reparatureinheit ausgeschaltet. Bitte neu initialisieren!"
