//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     45

// Message List
30SecondsLeft=ROBOGUÍA: "¡Solo tenemos 30 segundos para evacuar!  ¡Deprisa!"
1ReactorOn=GUIDEBOT: "1 de 5 reactores restablecidos. Conversores de energía disponibles."
BLANK=
Critical=¡El nivel de los escudos es crítico!
DefendReactorsShort= ROBOGUÍA: "Defiende los reactores por 12 minutos, y evacúa."
DefendThoseReactors2=RED ACRÓPOLIS: "Defiende esos reactores hasta que emitamos nuestra señal. Todo el personal debe alcanzar las lanzaderas de evacuación en menos de doce minutos.  uando todo el personal se encuentre a salvo destruiremos los reactores desde la órbita."
Destroyed=ROBOGUÍA: "El reactor está desactivado."
EnergyConvertedToShields=ROBOGUÍA: "Transfiriendo energía a los escudos del reactor."
EnergytoShield=RED ACRÓPOLIS: "En cada reactor encontrarás un conversor de energía a escudos. Dispara contra él con las armas energéticas para levantar los escudos del reactor si recibe un ataque. Si necesitas más energía, existe un centro de energía en el centro del túnel 3."
EntranceDoorMessage=ROBOGUÍA: "El bloqueo energético de seguridad de Red Acrópolis está activado."
ExitOnly=ROBOGUÍA: "Sólo salida de emergencia."
GetThoseReactorsMore=RED ACRÓPOLIS: "Al habla Harper. Es necesario reiniciar los reactores. Dispara a las bombas de fusión que se encuentran en la base de los reactores. Necesitaremos tener conectados por lo menos tres reactores para conseguir suficiente energía para huir. La evacuación completa durará alrededor de doce minutos; intenta conseguir algo de tiempo."
Health25=Nivel de los escudos al 25 %...
Health50=Nivel de los escudos al 50 %...
Health75=Nivel de los escudos al 75 %...
HITPOINTS=puntos de impacto del reactor: %f
IncomingMessage=Recibiendo mensaje de Red Acrópolis... (MAYÚS+F8)
IntroMessage=Marte - Instalación de investigación de Red Acrópolis|
OOPS=RED ACRÓPOLIS: "Perdemos energía por la red. Los sistemas de evacuación de emergencia están fallando. Me temo que no nos queda más remedio que rendirnos."
Reactor1Started=ROBOGUÍA: "El reactor 1 se encuentra operativo."
Reactor1Status=Estado del reactor 1:
Reactor2Started=ROBOGUÍA: "El reactor 2 se encuentra operativo."
Reactor2Status=Estado del reactor 2:
Reactor3Started=ROBOGUÍA: "El reactor 3 se encuentra operativo."
Reactor3Status=Estado del reactor 3:
Reactor4Started=ROBOGUÍA: "El reactor 4 se encuentra operativo."
Reactor4Status=Estado del reactor 4:
Reactor5Started=ROBOGUÍA: "El reactor 5 se encuentra operativo."
Reactor5Status=Estado del reactor 5:
ReactorDisabled=ROBOGUÍA: "El reactor está desactivado. No es posible restablecer los niveles de escudo."
ReactorHUDLabel=Reactores:
ReactorsOnline=ROBOGUÍA: "Los cinco reactores se encuentran conectados."
SelfDestruct=RED ACRÓPOLIS: "Estamos iniciando la cuenta atrás para detonar los reactores. Tienes 90 segundos para alcanzar la distancia mínima de seguridad antes de que la situación sea crítica. ¡Lárgate! ¡Inmediatamente!"
Shake=¡Sacude la mina!
ShieldsAtMax=ROBOGUÍA: "Alcanzado el nivel máximo de escudos."
StartTimer=Iniciar temporizador.
Testing=Prueba.
WereGettinOut=RED ACRÓPOLIS: "Buen trabajo. Todo el personal está a bordo, y las lanzaderas están listas para despegar. Partimos hacia el punto de encuentro con el Beagle en órbita; os recomendamos que hagáis lo mismo. Nos vemos allí.
