//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     60

// Message List
BeamIgnited=GUIDEBOT: "You ignited the emitter beam!  Protect the transmission until it's done..."
BeamIgniteError1=GUIDEBOT: "ERROR: Transmitter System is off-line."
BeamIgniteError2=GUIDEBOT: "ERROR: No data has been uploaded."
BeamIgniteError3=GUIDEBOT: "ERROR: Power supplied is insufficient."
BeamIgniteError4=GUIDEBOT: "ERROR: Defense Net Transmitter off-line."
BeamIgniteError5=GUIDEBOT: "ERROR: Beam Shield is active."
BeamIgniteError6=GUIDEBOT: "ERROR: Misaligned mirror node(s) detected."
BumpDialError=GUIDEBOT: "ERROR: Transmitter System down..."
BypassConnDisplay=Bypass Connectors: %d
DataLinkAlreadyActive=GUIDEBOT: "This Data Link is now functioning properly."
DataLinkError=GUIDEBOT: "ERROR: Unable to bypass infected system(s)."
DataLinkFixed=GUIDEBOT: "You used a Bypass Connector to repair this Data Link."
DialCodeEntered=GUIDEBOT: "Dial Code accepted... Defense Net Output enabled."
DialCodeIncorrect=GUIDEBOT: "ERROR: Dial code is incorrect."
DialSwitchError=GUIDEBOT: "ERROR: Transmitter System down..."
Empty=
FoundAllBypassConns=GUIDEBOT: "All Bypass Connectors retrieved."
FoundBypassConn=Bypass Connector
FoundEquipRmKey=Equipment Room Key
GotCoreMaterial=Anti-Virus Program
GotSpareLens=Spare Emitter Lens
IntroText=Earth orbit - CED Strategic Operations Platform
JournalBeamGame=JOURNAL: "Some of the new guys think they have it bad.  On my first day, they put me on Beam Ignition duty.  Of course, they failed to tell me where the switch is located.  I searched for an hour before somebody said, "Just remember who you work for."
JournalBeamHUD=Found Beam Controller's Journal... (SHIFT - F8)
JournalDialGame=REPORT: "The new Transmitter Output Selection System is ready.  It allows us to target a particular network with our data broadcasts.  The selection mechanism is a clock-like dial in the lower Engineering Room."
JournalDialHUD=Found Engineering Room Report... (SHIFT - F8)
JournalPowerGame=JOURNAL: "After last night's incident, I took the Station's Power off-line.  This stopped the generation of more infected bots, but it also meant that the beam emitter couldn't operate.  We'll have to turn the power back on sooner or later..."
JournalPowerHUD=Found Station Engineer's Journal... (SHIFT - F8)
JournalRobotGame=JOURNAL: "The last time we tried to broadcast, an infected robot almost took out the emitter lens!  Needless to say, I put in a request for some GunBoys..."
JournalRobotHUD=Found Beam Security Journal... (SHIFT - F8)
JournalShieldGame=CODE: "The following Beam Shield Deactivation Sequence is encoded as specified in CED regulation S897:  NW - SE - W - NE."
JournalShieldHUD=Beam Shield Deactivation Code Received... (SHIFT - F8)
JournalVirusGame=JOURNAL: "Today I tried to fix one of the Data Links that's been acting up.  It appears to be infected with a virus... but it's beyond anything I've ever seen.  I'd hate to think what could happen if it spread into the worker and security bot systems..."
JournalVirusHUD=Found Data Technician's Journal...  (SHIFT - F8)
LensDestroyed=GUIDEBOT: "The robot destroyed the lens!  You'll need to replace it..."
LensRobotWarning=GUIDEBOT: "A robot is heading for the lens!"
MirrorNodesUnaligned=GUIDEBOT: "The mirror nodes are not aligned anymore!"
OmnicronDisplayed=GUIDEBOT: "Upload Completed.  Awaiting Transmitter selection..."
PowerInsufficient=GUIDEBOT: "The power supplied to the beam igniter is now insufficient!"
PowerOffline=Power Supply %d is now off-line.
PowerOnline=Power Supply %d is now on-line.
ShieldCodeIncorrect=GUIDEBOT: "ERROR: Incorrect shield code sequence."
ShieldCodeSeqReset=GUIDEBOT: "The time to enter the code sequence has expired."
ShieldCodeSeqStart=GUIDEBOT: "Beam Shield Deactivation Sequence Engaged.  You have 15 seconds."
ShieldDeactivated=GUIDEBOT: "The Beam Shield has been deactivated!"
ShuttleFreed=GUIDEBOT: "You freed the escape shuttle!"
SystemStarted=GUIDEBOT: "The Transmitter System is ready."
SystemStarting=GUIDEBOT: "The Transmitter System is starting up!"
TransmissionComplete=GUIDEBOT: "The Anti-Virus Program has been transmitted. Good Job!"
UploadError=GUIDEBOT: "ERROR: Transmitter System off-line."
UploadStarted=GUIDEBOT: "Uploading Anti-Virus Program to Transmitter System..."
UseCoreMaterialFailed=GUIDEBOT: "You must upload the Anti-Virus Program at a Data Link."
UseLensCompleted=GUIDEBOT: "The spare lens is in position!  Resuming transmission..."
UseLensFailed1=GUIDEBOT: "You are too far away to place the lens!"
UseLensFailed2=GUIDEBOT: "A lens is already in place!"
