//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     70

// Message List
BaseAlertDisplay=Alarmstufe: %d
BaseAlertStatus=GUIDEBOT: "Das Kommandozentrum ist jetzt auf Alarmstufe %d"
CannonHitPlayer=GUIDEBOT: "Die Oberflächenkanone hat geschossen!"
CrashedShipGame=Aufklärungspilot T. Murphy S.O.S!  Mein Schiff brennt.  Alle Systeme sind gestört. Stürze ab.  Wiederhole,...stürze ab.  Die Basis ist streng bewacht. Auf Wachen achten, die die Türme alarmieren...hätte Tarnvorrichtung verwenden sollen, um nicht bemerkt zu werden! Jetzt ist es zu spät.
CrashedShipHud=Sie haben das Logbuch eines Piloten gefunden  (SHIFT- F8)
D1GuardSpotted=GUIDEBOT: "Die Minenwache hat Sie entdeckt!"
DataUplinkActivated=GUIDEBOT: "Andocksystem aktiviert."
Empty=
GuardTowerAlertedGG=GUIDEBOT: "Die Minenwache hat den Turm alarmiert!"
GuardTowerAlertedHG=GUIDEBOT: "Die Hangarwache hat den Turm alarmiert!"
HangerCamSawPlayer=GUIDEBOT: "Die Sicherheitskamera des Hangars hat Sie entdeckt!"
HangerDoorUnlocked=GUIDEBOT: "Die Hangartür wurde entriegelt."
HangerGuardSpotted=GUIDEBOT: "Die Hangarwache hat Sie entdeckt!"
HangerMsgGame=LOGBUCH: Gestern hat die Kamera der Hangarwache nicht richtig funktioniert und ein Datenlieferungsschiff falsch identifiziert.  Geschütztürme wurden aktiviert und das Schiff erlitt einen Totalschaden.  Alle Überreste des Schiffes wurden laut Protokoll in der alten Mine abgeworfen.
HangerMsgHUD=Hangarsicherheitsprotokoll heruntergeladen... (SHIFT- F8)
InitInterfaceCin=GUIDEBOT: "Datenschnittstelle initialisieren..."
InterfaceAcquired=GUIDEBOT: "Sie haben eine Datenschnittstelle Modell P103Z erhalten."
InterfaceHasNoPower=GUIDEBOT: "Die Daten-Uplinkkontrolltafel wird derzeitig nicht mit Energie versorgt."
InterfaceInitialized=GUIDEBOT: "Die Datenschnittstelle Ihres Schiffes wurde erfolgreich initialisiert."
InterfacePowerOff=GUIDEBOT: "Die Uplinkkontrolltafel ist jetzt abgeschaltet."
InterfacePowerOn=GUIDEBOT: "Die Energieversorgung der Uplinkkontrolltafel ist jetzt aktiviert."
InterfacePrepDenied=GUIDEBOT: "Fehler: Datenschnittstelle ist nicht kompatibel oder nicht vorhanden."
InterfacePrepInstHUD=Schnittstellenvorbereitungs-Anleitung heruntergeladen... (SHIFT - F8)
InterfacePrepInstrGame=ANWEISUNGEN: Willkommen im Datenschnittstellen-Vorbereitungsraum, Pilot.  Bevor Daten in das Daten-Uplinkzentrum eingespielt werden können, muss Ihre Schiffsdatenschnittstelle initialisiert werden. Um Ihr Schiff vorzubereiten, müssen Sie den Initialisierungsbereich in der Mitte des Raumes betreten.
IntroText=Der Mond - KEV Mondkommandozentrum
JuggAlertedBase=GUIDEBOT: "Der Juggernaut hat die Nachrichtenbasis alarmiert!"
JuggAlertWarning=GUIDEBOT: "Der Juggernaut ist Richtung Nachrichtenzentrum unterwegs... stoppen Sie ihn, bevor er dort ankommt!"
JuggSawPlayer=GUIDEBOT: "Der Juggernaut hat Sie entdeckt!"
MatcenActivated=GUIDEBOT: "Dieses Matcen ist jetzt aktiv."
MatcenDeactivated=GUIDEBOT: "Dieses Matcen wurde deaktiviert."
MemPlasmaGame=INFO: Bestimmte Datenschnittstellen benötigen eine Memoryplasma-Ladung, um eine erfolgreiche Verbindung mit dem Haupt-Uplinkzentrum herzustellen.  Das Gerät hier unten erzeugt permanent Ladungen zu diesem Zweck (ausser wenn die Erzeugung deaktiviert wurde).
MemPlasmaHUD=Memoryplasma-Ladungsinformation erhalten... (SHIFT- F8)
MemPlasmaLost=GUIDEBOT: "Ihre Memoryplasma-Ladung ist verfallen!"
MemPlasmaObtained=GUIDEBOT: "Memoryplasma-Ladung erhalten (hält %d Sekunden)"
MemPlasmaOff=GUIDEBOT: "Memoryplasmaerzeugung wurde deaktiviert."
MemPlasmaOn=GUIDEBOT: "Memoryplasmaerzeugung wurde aktiviert."
NanoPlasmaDefOff=GUIDEBOT: "Die Nanoplasmaverteidigung des Uplinks wurde deaktiviert."
NanoPlasmaDefOn=GUIDEBOT: "Die Nanoplasmaverteidigung des Uplinks ist jetzt aktiv."
NoEntry=Kein Zutritt!
Secret1=Sie haben einen geheimen Bereich gefunden!
UplinkCenterGame=INFO: Willkommen im Daten-Uplinkzentrum.  Sobald die Uplinkkontrolle Ihre Datenübertragung genehmigt hat, können Sie an den Daten-Uplink durch direktes Positionieren Ihres Schiffes zwischen den Plasmaknoten andocken.  Wenn alles in Ordnung ist, wird die Übertragung automatisch beginnen.
UplinkCenterHUD=Uplinkanleitungen erhalten... (SHIFT- F8)
UplinkControlGame=ANWEISUNGEN: Uplink-Kontrolloperatoren müssen alle Schiffe einer Sicherheitskontrolle unterzogen werden, bevor die Ladegenehmigung gewährt werden kann. Sobald ein Schiff als zulässig erachtet wird, kann die Uplink-Andockkontrolle an der hinteren Schalttafel aktiviert werden. 
UplinkControlHUD=Uplinkkontrollanweisungen erhalten... (SHIFT- F8)
UplinkDocking=GUIDEBOT: "Mit Daten-Uplink verbinden..."
UplinkErrorNano=GUIDEBOT: "Fehler: Nanoplasmaverteidigung ist aktiviert. Übertragung abgebrochen."
UplinkErrorNoChg=GUIDEBOT: "Fehler: Unzureichende Memory Plasmaladung auf Ausgangsschiff gefunden."
UplinkErrorNoInit=GUIDEBOT: "Fehler: Datenschnittstelle des Ausgangsschiffs wurde nicht inititalisiert."
UplinkErrorNoInt=GUIDEBOT: "Fehler: Das Ausgangsschiff ist nicht mit einer kompatiblen Datenschnittstelle ausgestattet."
UplinkErrorNoPlasma=GUIDEBOT: "Fehler: Hauptdatenuplink Plasmavorrat ist nicht aktiviert."
UplinkErrorNotAct=GUIDEBOT: "Fehler: Uplink-Andockkontrolle wurde nicht aktiviert."
UplinkPlasmaOff=GUIDEBOT: "Der Datenuplink Plasmavorrat ist jetzt deaktiviert."
UplinkPlasmaOn=GUIDEBOT: "Der Datenuplink Plasmavorrat ist jetzt aktiviert."
UploadingVirus=
VaultKeyAcquired=Datenkammer Eingangsschlüssel
ZCamMonitorOff=Sicherheitskamerabildschirm Aus
ZCamMonitorOn=Sicherheitskamerabildschirm Ein
ZCamSpotted=GUIDEBOT: "Lokale Verteidigung durch Geschütztürme wurde aktiviert!"
ZCanyonAmbush=GUIDEBOT: "Mir gefällt das gar nicht..."
ZCanyonRun=GUIDEBOT: "Der Schluchtwächter rennt weg! Fassen Sie ihn!"
ZCBAlerted=GUIDEBOT: "Die Kommandobasis wurde alarmiert!"
ZCBNoticed=GUIDEBOT: "Der Wächter der Kommandobasis wurde auf Sie aufmerksam!"
ZDVAlerted=GUIDEBOT: "Der Geschützturm des Datenraums wurde aktiviert!"
ZDVSpotted=GUIDEBOT: "Die Datenraumwache hat Sie entdeckt!"
ZGotCamMonitor=GUIDEBOT: "Sie haben einen Sicherheitskamerabildschirm gefunden!"
ZMegaTrap=GUIDEBOT: "Das Mega-Geschoss war verdrahtet... Passen Sie auf!"
ZturretHit=GUIDEBOT: "Lokale Geschützturm-Verteidigung wurde aktiviert!"

