
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     37



// Message List

ALLHeatSinksDestroyed=ROBOT-GUIDA: "Distrutti tutti e 3 gli scarichi di calore! Il portello di manutenzione è ora sbloccato!"

CenterClampDisengaged=ROBOT-GUIDA: "Disattivazione del dispositivo di aggancio all'attracco 2. Fregata ospedale Nightingale presente,  ATTENZIONE! Avaria del sistema!... Impossibile procedere!"

ClampNotInUse=ROBOT-GUIDA: "Questo aggancio d'attracco non è in funzione adesso."

CoolFanDestroyed=ROBOT-GUIDA: "Ventola della rete primaria di raffreddamento distrutta!"

CoolFanInvulnerable=ROBOT-GUIDA: "Le tue armi non hanno effetto!"

CoolingSystemClock=ROBOT-GUIDA: "Il termostato è in funzione. Accesso impossibile fin quando non sarà stato completato il ciclo di 32 ore."

CoolingSystemEngaged=ROBOT-GUIDA: "Regolatore termico in funzione: chiusura valvole di vapore e apertura scarichi di calore."

CoreTempAboveNormal=ROBOT-GUIDA: "Senza un sistema di raffreddamento funzionante, la temperatura del nucleo della raffineria continuerà a salire indefinitamente."

CoreTempCritical=ROBOT-GUIDA: "Distrutta la ventola primaria, la temperatura del nucleo della raffineria continuerà a salire fino a raggiungere il punto critico."

DoorUnlocked=ROBOT-GUIDA: "Porta adiacente bloccata!"

ElevatorAlreadyDown=ROBOT-GUIDA: "L'ascensore dell'hangar è già disattivato."

ElevatorDOWN=ROBOT-GUIDA: "Ascensore dell'hangar in discesa."

ElevatorNeedsDown=FREGATA: "Non riusciremo a uscire di qui se quell'ascensore resta su! Corri al centro di controllo!"

EndLevel=

EngagingCenterClamp=ROBOT-GUIDA: "Attivazione del dispositivo di aggancio all'attracco 2. Fregata ospedale Nightingale presente. ATTENZIONE! Avaria del sistema!... Impossibile procedere!"

FanReverseSwitch=ROBOT-GUIDA: "Inversione della ventola di raffreddamento."

ForcefieldDisabled=ROBOT-GUIDA: "Campo di forza disabilitato!"

FoundSecretData=RECUPERATI: Cartuccia dati danneggiata... (MAIUSC-F8)

FrigateSaved=FREGATA: "Grazie per avere aperto l'aggancio. Non c'è tempo per le chiacchiere adesso... Questo posto è instabile!"

HangarForcefieldDown=ROBOT-GUIDA: "Concessa autorizzazione di sicurezza. Campo di forza dell'hangar disattivato. Decollo autorizzato."

HangarForcefieldUp=ROBOT-GUIDA: "Autorizzazione di sicurezza negata. Richiesto Pass di autorizzazione per la disattivazione manuale del campo di forza."

HeatSinkDestroyed=ROBOT-GUIDA: "Scarico di calore del sistema di raffreddamento distrutte!"

IntroCamera=Europa - Raffineria carburante del PTMC Dol Ammad

Mayday=FREGATA: "Fregata ospedale Nightingale a controllo hangar. Richiesta autorizzazione per la disattivazione dell'aggancio d'attracco. Ripeto. L'aggancio d'attracco 2 è ancora bloccato. Necessito assistenza per partenza immediata."

MessageFromFrigate=In arrivo trasmissione dati dalla fregata ospedale...  MAIUSC-F8

Passkey=Pass di sicurezza hangar

WeaponsPlantData=La cartuccia è malconcia, ma il robot guida è in grado di estrarre molti dati che potranno tornare utili. I dati si riferiscono a una fabbrica d'armi del SRAD che non compare sulle normali carte di navigazione del PTMC. Varrà la pena di farle una visitina più tardi.

