
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     51



// Message List

AftMatcenCheck=GUIDEBOT: "Inspection de l'interrupteur du robogène arrière..."

AftSwCinema=Désactiver le robogène arrière

AuxCoreDoor=GUIDEBOT: "Accès au Coeur du Moteur Auxiliaire refusé. Trouvez un autre accès !"

Bay62Door=GUIDEBOT: "La porte d'accès à la baie 62 est bloquée. Trouvez un autre accès !"

Bay62Fuse=GUIDEBOT: "robogène Baie 62 désactivé."

Bay62Game=11:37.04.04.3750 JOURNAL DE BORD  CHASSEUR 62 BADGE ID M. KELLY EN CHARGE: "Nos efforts ont été infructueux ici.  Nous savons qu'ils ont pris le contrôle d'au moins deux chasseurs StarHawk ! L'infection s'est étendue aux drones ouvriers. J'évacue mes hommes."

Bay62Hud=Journal Baie 62 Téléchargé... (SHIFT-F8)

Bay62Lance=GUIDEBOT: "Tourelles désactivées."

BayInfoGame=07:02.04.04.3750: Livraison DeepSpace 432178 de la PTMC: "Commande Pièces de robogène à bord."

BayInfoHud= Journal Baie 36 Téléchargé... (SHIFT-F8)

Cleanup=COMMANDANT CDT: "Eliminez tout membre des troupes d'assaut restant."

CoreAccFF=GUIDEBOT: "Accès au Coeur Blindé. Trouvez un autre accès."

CoreInfo1=11:11:04.04.3750 Journal Téléchargé... (SHIFT-F8)

CoreInfo2=11:11.04.04.3750  ALERTE INTRUS ! "Accès Coeur Moteur Porte NO. 79.287  Désactivé par Utilisateur BADGE ID NO. 80-84."

CoreRads=GUIDEBOT: "Interférence Critique !"

DangerEngine=GUIDEBOT: "ATTENTION  -- Zone de Pompage Moteur !"

EndCine=

EndMission=COMMANDANT CDT: "Vous avez éliminé toutes les troupes d'assaut. Bien joué !"

EngineDown=GUIDEBOT: "Objectif Tertiaire réussi ! Coupure Cœur Moteur."

EngineMisfire=GUIDEBOT: "ATTENTION - DEFAUT ALLUMAGE MOTEUR!!"

EngineTakover=COMMANDANT CDT: "Des troupes d'assaut se sont emparées des commandes du moteur..."

GotReconInterface=Interface Reconnaissance

IntroText=Orbite de Mars - CDT| Porte-Vaisseau Amiral Expediator

JeffriesID=GUIDEBOT: "Jeffries - Proue : Il y a ici un chemin pour aller à la Section de Poupe."

LandingDoor62=GUIDEBOT: "La porte d'accès principal à la Baie 62 a été bloquée.  Trouvez un autre accès !"

LeaderCinema=La Horde sauvage: Commandant des Troupes de la Légion Victorieuse

LeaderTaunt1=RADIO de la CDT: "Ici le Commandant des Troupes de la Légion Victorieuse..."

LeaderTaunt2=RADIO de la CDT: "Nous avons le contrôle de l'Expediator."

LeaderTaunt3=RADIO du CDT: "Nous éliminerons toute unité que ne se rendra pas immédiatement."

LeaderTaunt4=RADIO de la CDT: "Nous sommes sans foi. Alors, pas de quartier."

LeaderTaunt5=RADIO du CDT: "Stop....!"

LevelObjA=GUIDEBOT: "Vous avez désactivé le robogène arrière !"

LevelObjtives1=Objectifs Primaires: | 1. DESACTIVER ROBOGENE ARRRIERE | Détruire l'interrupteur de commande manuelle.

LevelObjtives2=2. La horde sauvage | Commandant des Troupes de la Légion Victorieuse.

LevelObjtives3=Neutraliser la menace de prise de contrôle adverse: | ELIMINER | LEGION DE DEFENSE DES TROUPES D'ASSAUT | Rouge, Verte et Blanche.

MainDeckGame=11:22.04.04.3750 JOURNAL DE BORD VAISSEAU CDT DREADNAUGHT EXPEDIATOR: "Un Virus inconnu a contaminé les systèmes de défense du vaisseau y compris les Unités-ST. Nous avons isolé toute la Section Arrière du Vaisseau. Par chance, tout le monde a pu sortir à temps ! Nous recherchons des solutions de survie."

MainDeckHud=Journal de bord du Vaisseau Téléchargé ... (SHIFT-F8)

NoEntry=QUARANTAINE  -- Ne Pas Dépasser Cette Limite.

NoEntry62=Cette porte d'accès à la travée du hangar a été fermée par soudure. Trouvez un autre accès.

PplDoors1=Accès interdit au personnel.

PrimaryObjB=COMMANDEMENT DE LA CDT: "Félicitations!  Vous avez accompli vos objectifs secondaires."

PrimerDamage=GUIDEBOT: "Champ de Plasma!!   Le Vaisseau est Touché."

RobotCount=Il reste toujours %d agents d'assaut infectés !

SecondaryObjective=ALARME!!! | AVARIE MOTEUR...|

ShipInfo1= Journal de bord du Vaisseau Téléchargé... (SHIFT-F8)

ShipInfo2=10:59.04.04.3750: "Ceci est un enregistrement vocal en urgence du Mécanicien-Chef Partie Arrière Kalmer. Après remplacement de pièces avec la nouvelle commande 47632-09, le CentMat a débloqué. Il s'est mis à produire des agents d'assaut infectés ! Impossible de l'arrêter ! Nous évacuons les équipes de réparation..."

SpyPlead=HUNTER DRONE: "S'il vous plaît - Je ne ferai rien si vous ne me tuez pas -  Je ne suis pas comme les autres !"

StormtroopersCine=Butez ces gars...| Avant qu'ils ne vous fassent la peau !

