//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     11

// Message List
BPDefeated=GUIDEBOT: "PTMC-Söldner besiegt!"
CartridgeError=GUIDEBOT: "Sie können die Datenkassette hier nicht ablegen!"
CinematicAmbush=PTMC-Söldner
CinematicDataCart=Daten werden an Suzuki übertragen
CinematicEndCam=
CinematicIntroCam=Erde - Seoul, Korea
Debug1=Anpassungsschwierigkeit: %f
Debug2=Das sollte SCHÜTTELN!
GetOut=GUIDEBOT: "Übertragung erfolgreich!  Suzuki sollte die Daten jetzt haben!"
PutTheCartridge=GUIDEBOT: "Legen Sie die Datenkassette in der Mitte des Übertragungsraums ab!"
