//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     39

// Message List
1Switch=ROBOGUÍA: "Si quieres buscar una ruta alternativa para esquivar los campos de fuerza principales, busca y activa los 9 conmutadores para desbloquear la puerta del ascensor."
2Switch=ROBOGUÍA: "¡2 conmutadores alternativos activados!"
3Switch=ROBOGUÍA: "¡3 conmutadores alternativos activados!"
4Switch=ROBOGUÍA: "¡4 conmutadores alternativos activados!"
5Switch=ROBOGUÍA: "¡Faltan 4 conmutadores alternativos!"
6Switch=ROBOGUÍA: "¡Sólo faltan 3 conmutadores alternativos!"
7Switch=ROBOGUÍA: "¡Sólo faltan 2 conmutadores alternativos para desbloquear la puerta del ascensor!"
8Switch=ROBOGUÍA: "¡Falta 1 conmutador alternativo para completar la secuencia!"
9Switch=ROBOGUÍA: "¡Secuencia alternativa completa! Se ha desbloqueado la puerta del ascensor abandonado."
All6Deactive=ROBOGUÍA: "Desactivados los 6 direccionadores de energía. Generadores de campo de fuerza de respaldo activados."
DestroyThese=Busca la forma de activar los generadores| de respaldo para poder| destruir y bajar los campos de fuerza.
DoorUnlocked=Puerta desbloqueada.
DoThis=
ExitAbort=La nave capturada ha quedado atascada en las puertas; este nivel finalizará automáticamente en 5 segundos.
FirstCamera=Son pequeños, pero sus amigos| resultan temibles. Evita su ángulo| de visión si quieres seguir vivo.
ForcefieldDisabled=¡Campo de fuerza desactivado!
ForcefieldFirst=ROBOGUÍA: "Desactivada la energía principal del campo de fuerza. Activando generador de respaldo."
ForcefieldsDisabled=¡Campos de fuerza desactivados!
FreeAtLast=PILOT: "Gracias por rescatarme, Defensor! Vamos a salir de aquí... ¡Sígueme!"
GoalComplete=¡He cumplido un objetivo!
GotHim=Gracias por caer en nuestra| trampa, Defensor.
GoUpLeft=PILOT: "El bloqueo de estos tubos de salida está sincronizado. Levanta el lado izquierdo mientras yo me encargo del derecho, y nos veremos en la superficie."
MainDestroyed=ROBOGUÍA: "Generadores principales de campo de fuerza destruidos."
NextGoal=Efectuar patrulla 3
PathCaptured=Capturado
PathIntroCam=IntroCam
PathIntroShip=IntroShip
PickupKey=ROBOGUÍA: "Es posible acceder al núcleo secundario. Desbloqueadas todas las puertas del núcleo principal."
PipeDemo=Las tuberías son vulnerables cuando se encuentran activadas; de lo contrario, no malgastes munición.
Reroute=ROBOGUÍA: "¡Direccionador de energía desactivado!"
SecretArea=¡Has encontrado una zona secreta!
Spotted=ADVERTENCIA: ¡Alarma de intrusos! Torretas activadas.
Work=Titán: Instalaciones de almacenamiento del PTMC
