//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     57

// Message List
BLANK=
BossIntroductionText=El homúnculo|
BuilderCollectorsCorrectlyPlaced=ROBOGUÍA: "Se ha abierto una puerta."
Builders3secondsleft=ROBOGUÍA: "Te quedan tres segundos."
BuildersDoorMessage=ROBOGUÍA: "Como agente de los recolectores, puedes pasar."
BuildersPuzzhint=ROBOGUÍA: "Detectado pozo de ventilación."
BuildersPuzzMessage=ROBOGUÍA: "Vuela rápidamente."
BuildersPuzzMessage2=ROBOGUÍA: "El icono de los constructores está al final del camino elegido."
BuildersTimerExpired=ROBOGUÍA: "No queda tiempo."
CollectorsDoorMessage=ROBOGUÍA: "Como agente de los constructores, puedes pasar."
EndPath=ROBOGUÍA: "Fin del camino."
EnterPriestPuzzle=ROBOGUÍA: "Has entrado en el acertijo del sacerdote."
ExitPriestPuzzle=ROBOGUÍA: "Has salido del acertijo del sacerdote."
FirstPickupBuilder=Icono de los constructores
FirstPickupCollector=Icono de los recolectores
FirstPickupPriest=Icono del sacerdote
IntroLevelMessage=Marte - Cañones del laberinto de Noctis|
InvGame=Puedes seleccionar elementos del inventario por medio de los controles predefinidos, [ y ]. El control predeterminado para utilizar o desplegar un elemento es \.
InvHUD=ROBOGUÍA: "Recuerda utilizar el inventario con los iconos. MAYÚS+F8."
KeyAlreadyThere=ROBOGUÍA: "Dos en uno no es lo mismo que tres."
PlaceBuildersKey=ROBOGUÍA: "Has colocado el icono de los constructores."
PlaceCollectorsKey=ROBOGUÍA: "Has colocado el icono de los recolectores."
PlacePriestKey=ROBOGUÍA: "Has colocado el icono del sacerdote."
PriestGalleryDoorLocked=ROBOGUÍA: "No mereces la pena."
PriestHallDoorLocked=ROBOGUÍA: "El sumo sacerdote no te permitirá entrar."
PriestKeyCorrectlyPlaced=ROBOGUÍA: "El homúnculo espera."
PriestPuzzleEnter=ROBOGUÍA: "Entre las columnas camina el sacerdote elegido."
PriestPuzzleGoofed=ROBOGUÍA: "No eres el elegido."
PriestPuzzleSolved=ROBOGUÍA: "Has demostrado tu valía."
Test=Prueba
Testing=
ThisDoorDoesNotAnswer=ROBOGUÍA: "Esta puerta no te responde."
TugMessage1=NAVE REMOLCADORA: "Creo que hemos encontrado los restos. Desde aquí parece que se encuentran en buen estado."
TugMessage2=NAVE REMOLCADORA: "Esperaremos mientras aseguras la zona."
TugMessage3=NAVE REMOLCADORA: "Hay un campo de fuerza que nos bloquea el paso. ¿Puedes desactivarlo rápidamente?"
TugMessage4=NAVE REMOLCADORA: "Parece que aún no has terminado. ¡Ten cuidado!"
TugMessage5=NAVE REMOLCADORA: "Date prisa y destruye eso para que podamos largarnos cuanto antes."
TugMessage6=NAVE REMOLCADORA: "De acuerdo. Ahora, vamos a poner esto en marcha."
TugMessageShipPickUp=NAVE REMOLCADORA: "De acuerdo. El campo de fuerza está desactivado. Vamos a buscar esa nave."
TugMessageStart=NAVE REMOLCADORA: "A partir de ahora estás solo, piloto."
TugStartMessage2=NAVE REMOLCADORA: "No nos comunicaremos por radio hasta establecer contacto visual con el lugar del accidente."
XsecsOntheClock=ROBOGUÍA: "Sólo quedan 30 segundos."
YoucantUseKeyHere=
