
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     70



// Message List

BaseAlertDisplay=Livello allerta: %d

BaseAlertStatus=ROBOT-GUIDA: "Il Centro di Comando si trova ora in stato di Allerta livello %d."

CannonHitPlayer=ROBOT-GUIDA: "Il cannone di superficie ha sparato!"

CrashedShipGame=Pilota ricognitore T Murphy S.O.S! Nave in fiamme. Tutti i sistemi fuori uso. Scendo, Ripeto, ...Scendo. La base Š strettamente sorvegliata. Dovr• fare attenzione alle torri di guardia.... Per non essere visto avrei dovuto utilizzare il sistema stealth! Ora Š troppo tardi

CrashedShipHud=Hai trovato il libro di bordo del Pilota  (MAIUSC-F8)

D1GuardSpotted=ROBOT-GUIDA: "La guardia della miniera ti ha individuato!"

DataUplinkActivated=ROBOT-GUIDA: "Controllo trasferimento dati attivato."

Empty=

GuardTowerAlertedGG=ROBOT-GUIDA: "La guardia della miniera ha allertato la torre!"

GuardTowerAlertedHG=ROBOT-GUIDA: "La guardia dell'hangar ha allertato la torre!"

HangerCamSawPlayer=ROBOT-GUIDA: "La telecamera di sorveglianza dell'hangar ti ha individuato!"

HangerDoorUnlocked=ROBOT-GUIDA: "La porta dell'hangar Š stata aperta."

HangerGuardSpotted=ROBOT-GUIDA: "La guardia dell'hangar ti ha individuato!"

HangerMsgGame=REGISTRO: Ieri abbiamo avuto un problema con la telecamera di sorveglianza dell'hangar che ha male identificato una nave da carico. Sono state attivate le difese della torretta e la nave Š stata irrimediabilmente danneggiata. I rottami sono stati scaricati nella vecchia miniera secondo protocollo.

HangerMsgHUD=Registro sicurezza hangar scaricato... (MAIUSC-F8)

InitInterfaceCin=ROBOT-GUIDA: "Sto inizializzando l'interfaccia dati..."

InterfaceAcquired=ROBOT-GUIDA: "Hai avuto un'interfaccia dati modello P103Z."

InterfaceHasNoPower=ROBOT-GUIDA: "Il pannello di controllo trasferimento dati Š al momento spento."

InterfaceInitialized=ROBOT-GUIDA: "L'interfaccia dati della nave Š stata inizializzata."

InterfacePowerOff=ROBOT-GUIDA: "Alimentazione del pannello di controllo del trasferimento dati disinserita."

InterfacePowerOn=ROBOT-GUIDA: "L'alimentazione del pannello di controllo trasferimento dati Š attiva."

InterfacePrepDenied=ROBOT-GUIDA: "Errore: L'interfaccia dati Š incompatibile o assente."

InterfacePrepInstHUD=Istruzioni di preparazione interfaccia scaricate... (MAIUSC-F8)

InterfacePrepInstrGame=ISTRUZIONI: Benvenuto nella sala di preparazione all'interfaccia dati, pilota. Prima di scaricare informazioni nel Centro trasferimento dati, devi inizializzare l'interfaccia dati della nave. Per preparare la nave, entra nel fulcro di inizializzazione al centro della sala.

IntroText=The Moon - Centro di Comando Lunare CDT 

JuggAlertedBase=ROBOT-GUIDA: "Il Juggernaut ha allertato la base Comm!"

JuggAlertWarning=ROBOT-GUIDA: "Il Juggernaut Š diretto alla base Comm... Fermalo prima che arrivi!"

JuggSawPlayer=ROBOT-GUIDA: "Il Juggernaut ti ha individuato!"

MatcenActivated=ROBOT-GUIDA: "Questo Matcen Š attivo."

MatcenDeactivated=ROBOT-GUIDA: "Questo Matcen Š stato disattivato."

MemPlasmaGame=INFO: Per collegarsi al Centro principale trasferimento dati alcune interfacce dati richiedono una carica di memoria al plasma.  Il dispositivo qui sotto genera continue cariche (a meno che la funzione di generazione non sia stata disattivata).

MemPlasmaHUD=Ricevute informazioni sulla carica di memoria al plasma... (MAIUSC-F8)

MemPlasmaLost=ROBOT-GUIDA: "La tua carica di memoria al plasma Š finita!"

MemPlasmaObtained=ROBOT-GUIDA: "Ottenuta carica di memoria al plasma (durata %d secondi)"

MemPlasmaOff=ROBOT-GUIDA: "La funzione di generazione di memoria al plasma Š stata disattivata."

MemPlasmaOn=ROBOT-GUIDA: "La funzione di generazione di memoria al plasma Š stata attivata."

NanoPlasmaDefOff=ROBOT-GUIDA: "Le difese nano plasma del trasferimento dati sono state disattivate."

NanoPlasmaDefOn=ROBOT-GUIDA: " Le difese nano plasma del trasferimento dati sono attive."

NoEntry=Vietato l'ingresso oltre questo punto!

Secret1=Hai trovato un'area segreta!

UplinkCenterGame=INFO: Benvenuto nel Centro trasferimento dati. Quando il Controllo avr... autorizzato il caricamento dati potrai posizionare la nave direttamente tra i nodi al plasma. Se Š tutto in ordine, il trasferimento avr... immediatamente inizio.

UplinkCenterHUD=Ricevute istruzioni per trasferimento dati... (MAIUSC-F8)

UplinkControlGame=DIRETTIVE: Gli operatori del Controllo devono sottoporre tutte le navi a verifica di sicurezza prima di autorizzare il trasferimento dati. Se la nave sar... riconosciuta idonea, potr... essere attivato sul pannello posteriore il collegamento per il trasferimento dati.

UplinkControlHUD=Ricevute direttive controllo trasferimento dati... (MAIUSC-F8)

UplinkDocking=ROBOT-GUIDA: "Connessione al trasferimento dati in corso..."

UplinkErrorNano=ROBOT-GUIDA: "Errore: Le difese nano plasma sono attive. Trasferimento interrotto."

UplinkErrorNoChg=ROBOT-GUIDA: "Errore: Riscontrata insufficiente carica di memoria al plasma sulla nave origine."

UplinkErrorNoInit=ROBOT-GUIDA: "Errore: I dati della nave origine non sono stati inizializzati."

UplinkErrorNoInt=ROBOT-GUIDA: "Errore: La nave origine non Š munita di una interfaccia dati compatibile.."

UplinkErrorNoPlasma=ROBOT-GUIDA: "Errore: La scorta di plasma per il Trasferimento centrale dati non Š attiva."

UplinkErrorNotAct=ROBOT-GUIDA: "Errore: Il Controllo trasferimento dati non Š stato attivato."

UplinkPlasmaOff=ROBOT-GUIDA: "La scorta di plasma per il trasferimento dati Š finita."

UplinkPlasmaOn=ROBOT-GUIDA: "La scorta di plasma per il trasferimento dati Š attiva."

UploadingVirus=

VaultKeyAcquired=Chiave di accesso alla sala dati.

ZCamMonitorOff=Monitor telecamera di sicurezza spento.

ZCamMonitorOn=Monitor telecamera di sicurezza acceso.

ZCamSpotted=ROBOT-GUIDA: "Le torrette di difesa locale sono state attivate!"

ZCanyonAmbush=ROBOT-GUIDA: "Questa faccenda non mi piace..."

ZCanyonRun=ROBOT-GUIDA: "La guardia del canyon sta scappando!  Prendilo! "

ZCBAlerted=ROBOT-GUIDA: "La Base Comando Š stata allertata!"

ZCBNoticed=ROBOT-GUIDA: "La guardia della Base Comando ti ha individuato! "

ZDVAlerted=ROBOT-GUIDA: "Le difese della torretta della Sala Dati sono state attivate!"

ZDVSpotted=ROBOT-GUIDA: "La guardia della Sala Dati ti ha individuato!"

ZGotCamMonitor=ROBOT-GUIDA: "Hai trovato il monitor della telecamera di sicurezza!"

ZMegaTrap=ROBOT-GUIDA:" Quel Mega era minato... fa attenzione!"

ZTurretHit=ROBOT-GUIDA: "Le difese locali della torretta sono state attivate!"

