//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     73

// Message List
BaseAlertDisplay=Nivel de alerta: %d
BaseAlertStatus=ROBOGUÍA: "El centro de mando está ahora en alerta de nivel %d."
CannonHitPlayer=ROBOGUÍA: "¡El cañón de superficie ha disparado!"
CrashedShipGame=Piloto T. Murphy, en misión de reconocimiento. S.O.S. Mi nave está ardiendo. Fallo en todos los sistemas. Estoy cayendo. Repito, estoy cayendo. La base está fuertemente custodiada. Los guardas avisan a las torres... Debería haber entrado furtivamente, pero ya es tarde.
CrashedShipHud=Has encontrado el cuaderno de bitácora de un piloto  (MAYÚS+F8)
D1GuardSpotted=ROBOGUÍA: "El guarda de la mina te ha descubierto."
DataUplinkActivated=ROBOGUÍA: "Control de anclaje de carga activado."
Empty=
GuardTowerAlertedGG=ROBOGUÍA: "El guarda de la mina ha avisado a la torre."
GuardTowerAlertedHG=ROBOGUÍA: "El guarda del hangar ha avisado a la torre."
HangerCamSawPlayer=ROBOGUÍA: "La cámara de seguridad del hangar te ha descubierto."
HangerDoorUnlocked=ROBOGUÍA: "La puerta del hangar está desbloqueada."
HangerGuardSpotted=ROBOGUÍA: "El guarda del hangar te ha descubierto."
HangerMsgGame=CUADERNO DE BITÁCORA: Ayer, la cámara de seguridad del hangar tuvo una avería e identificó de forma errónea una nave de suministro de datos. Se activaron las torretas y la nave quedó inutilizada. Tal y como establece el protocolo, los restos de la nave se han depositado en la mina antigua.
HangerMsgHUD=Registro de seguridad del hangar descargado... (MAYÚS+F8)
InitInterfaceCin=ROBOGUÍA: "Inicializando interfaz de datos..."
InterfaceAcquired=ROBOGUÍA: "Has conseguido una interfaz de datos, modelo P103Z."
InterfaceHasNoPower=ROBOGUÍA: "El panel de control de carga de datos no tiene alimentación eléctrica."
InterfaceInitialized=ROBOGUÍA: "La interfaz de datos de tu nave se ha inicializado correctamente."
InterfacePowerOff=ROBOGUÍA: "El panel de control de carga de datos está sin suministro eléctrico."
InterfacePowerOn=ROBOGUÍA: "El panel de control de carga de datos recibe suministro eléctrico."
InterfacePrepDenied=ROBOGUÍA: "Error: La interfaz de datos es incompatible o no se encuentra."
InterfacePrepInstHUD=Instrucciones de preparación de la interfaz descargadas... (MAYÚS+F8)
InterfacePrepInstrGame=INSTRUCCIONES: Bienvenido a la sala de preparación de la interfaz de datos, piloto. Para poder cargar información en el centro de anclaje de carga de datos es necesario inicializar la interfaz de datos de la nave. Para preparar su nave, introduzca el núcleo de inicialización en el centro de la sala.
IntroText=La luna: Centro de mando lunar del CED
JuggAlertedBase=ROBOGUÍA: "¡El Juggernaut ha avisado a la base!"
JuggAlertWarning=ROBOGUÍA: "El Juggernaut se dirige a la base. ¡Deténlo antes de que llegue!"
JuggSawPlayer=ROBOGUÍA: "El Juggernaut te ha detectado."
MatcenActivated=ROBOGUÍA: "Este Matcen está activado."
MatcenDeactivated=ROBOGUÍA: "Este Matcen está desactivado."
MemPlasmaGame=INFO: Algunas interfaces de datos pueden necesitar una carga de plasma de memoria para conectarse al centro de carga principal. Este dispositivo genera cargas de forma continua (a no ser que se desactive su generación).
MemPlasmaHUD=Información de carga de plasma de memoria recibida... (MAYÚS+F8)
MemPlasmaLost=ROBOGUÍA: "Tu carga de plasma de memoria ha caducado."
MemPlasmaObtained=ROBOGUÍA: "Carga de plasma de memoria obtenida (dura 30 segundos)"
MemPlasmaOff=ROBOGUÍA: "La generación de plasma de memoria está desactivada."
MemPlasmaOn=ROBOGUÍA: "La generación de plasma de memoria está activada."
NanoPlasmaDefOff=ROBOGUÍA: "Las nanodefensas de plasma del enlace de carga están desactivadas."
NanoPlasmaDefOn=ROBOGUÍA: "Las nanodefensas de plasma del enlace de carga están activadas."
NoEntry=¡Paso prohibido!
Secret1=¡Has encontrado una zona secreta!
UplinkCenterGame=INFO: Bienvenido al centro de carga de datos. Cuando el control haya autorizado la carga podrá anclarse al enlace de carga colocando la nave entre los nodos de plasma. Si la configuración es correcta, la transferencia comenzará automáticamente.
UplinkCenterHUD=Recibidas instrucciones de carga del piloto... (MAYÚS+F8)
UplinkControlGame=DIRECTRICES: Los operadores del control de carga deben pasar las naves por una comprobación de seguridad para recibir autorización de carga. Cuando la nave se considere aceptable, se puede activar el control de anclaje del panel trasero.
UplinkControlHUD=Directrices de control de carga de datos recibidas... (MAYÚS+F8)
UplinkDocking=ROBOGUÍA: "Conectando a enlace de carga de datos..."
UplinkErrorNano=ROBOGUÍA: "Error: Las nanodefensas de plasma están activadas.  Carga interrumpida."
UplinkErrorNoChg=ROBOGUÍA: "Error: La carga de plasma de memoria de la nave de origen es insuficiente."
UplinkErrorNoInit=ROBOGUÍA: "Error: La interfaz de datos de la nave de origen no se ha inicializado."
UplinkErrorNoInt=ROBOGUÍA: "Error: La nave de origen no cuenta con una interfaz de datos compatible."
UplinkErrorNoPlasma=ROBOGUÍA: "Error: La alimentación eléctrica de plasma del enlace de carga de datos principal no está activada."
UplinkErrorNotAct=ROBOGUÍA: "Error: No se ha activado el control de anclaje."
UplinkPlasmaOff=ROBOGUÍA: "La alimentación de plasma del enlace de carga de datos está desactivada."
UplinkPlasmaOn=ROBOGUÍA: "La alimentación de plasma del enlace de carga de datos está activada."
UploadingVirus=
VaultKeyAcquired=Llave de entrada a la cámara acorazada de datos
ZCamMonitorOff=Monitor de la cámara de seguridad desactivado
ZCamMonitorOn=Monitor de la cámara de seguridad activado
ZCamSpotted=ROBOGUÍA: "Las torretas de defensa locales están activadas."
ZCanyonAmbush=ROBOGUÍA: "No me gusta la pinta que tiene esto..."
ZCanyonRun=ROBOGUÍA: "El guarda del cañón huye. ¡Captúralo!"
ZCBAlerted=ROBOGUÍA: "Han avisado a la base de mando."
ZCBNoticed=ROBOGUÍA: "El guarda de la base de mando te ha detectado."
ZDVAlerted=ROBOGUÍA: "Las torretas de defensa de la cámara acorazada de datos se han activado."
ZDVSpotted=ROBOGUÍA: "El guarda de la cámara acorazada de datos te ha detectado."
ZGotCamMonitor=ROBOGUÍA: "Has encontrado un monitor de la cámara de seguridad."
ZMegaTrap=ROBOGUÍA: "Ese mega estaba conectado... ¡Ten cuidado!"
ZTurretHit= ROBOGUÍA: "¡Torretas defensivas se han activado!"
