//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     48

// Message List
1stInvalidPassOffense=KONTROLLPUNKT: "Gewährung der Sicherheitsfreigabe nicht möglich.  Bitte warten Sie auf Unterstützung."
2ndInvalidPassOffense=KONTROLLPUNKT: "Sicherheitsfreigabe verweigert!  Sicherheitskräfte alarmiert!"
AnotherTurretGone=GUIDEBOT: "Geschützturm der Peripherieverteidigung zerstört."
ChemicalReactionAlert=GUIDEBOT: "GEFAHR!  Säurebehälter kontaminiert!  Biochemie-Alarm auf Ebene 4!  Hochsicherheitsebene evakuieren!"
ChemicalReactionSwitches=GUIDEBOT: "Chemie-Sicherheitsabschottung wurde eingeleitet."
ComputerDestroyed=GUIDEBOT: "Novaks Gefängnisdaten-Supercomputer wurde zerstört!"
DontShootMe=SHUTTLE: "Immer sachte mit meinen Schutzschilden!"
Empty=
EndLevel=
EscortShuttle=SHUTTLE:  "Ich könnte eine Eskorte jetzt gut gebrauchen."
ForcefieldDown=SHUTTLE: "Das Kraftfeld ist deaktiviert, eskortieren Sie mich auf dem Weg zu Schweitzer."
ForcefieldDownEarly=GUIDEBOT: "Das Kraftfeld im Gefangenentransferhangar wurde deaktiviert."
G1MinSecurityPassB=Sicherheitspass G-1
IncomingMessage=Eingehende Übertragung vom Shuttle...  (SHIFT-F8)
InnerTowerForcefields=GUIDEBOT: "Kraftfelder deaktiviert."
IntroMessage=Phobos - Novak Firmengefängnis
LoadedSweitzer=SHUTTLE:  "Schweitzer ist an Bord, und wir sind bereit, um hier rauszukommen. Decken Sie mich!"
LoadingSweitzer=SHUTTLE:  "Dann wollen wir den Doktor mal an Bord bringen."
MaximumSecurityClearance=KONTROLLPUNKT: "Sicherheitsfreigabe für Hochsicherheitsebene gewährt."
MediumSecurityClearance= KONTROLLPUNKT: "Sicherheitsfreigabe für mittlere Sicherheitsebene gewährt."
MinimumSecurityClearance= KONTROLLPUNKT: "Sicherheitsfreigabe für Minimal-Sicherheitsebene gewährt."
OneTurretDown=SHUTTLE: "O.K.! Einer der peripheren Geschütztürme ist runter; bleiben noch die anderen vier. Wir werden uns in einer nahegelegenen Schlucht aufhalten, bis Sie das Gebiet gesichert haben. Viel Glück."
R1MaxSecurityPassC=Sicherheitspass R-1
RecordsNodeDestroyed=GUIDEBOT: "Novak-Gefängnisdaten Ersatzknoten zerstört!"
SECRETAREA= Sie haben einen geheimen Bereich gefunden!
SecurityPassNotUsableHere=GUIDEBOT: "Dieser Sicherheitspass ist hier nicht anwendbar."
SecurityPassReturned=GUIDEBOT: "Der Sicherheitspass wurde zu seinem Automaten zurückgeführt."
ShuttleMoveToTower=SHUTTLE: "Die Peripherieverteidigung ist beseitigt und die Kraftfelder des Versorgungshangars sind deaktiviert. Ich fliege zum Hauptturm und erwarte Ihr Signal, wenn Sie Schweitzer gefunden haben.  Sieht so aus, als wäre der Versorgungshangar Ihre einzige Einstiegsmöglichkeit."
ShuttleUnderAttack=SHUTTLE: "Uh, wir sind hier in was hineingeraten und könnten etwas Feuerunterstützung gut gebrauchen! Ich bin von Sicherheitstruppen umzingelt!"
SPUDhasTheBall=SPM DRONE: "Transportiere Chemie-Kapsel."
SPUDisBorn=GUIDEBOT: "Spezialproduktions-Mehrzweckdrone anfordern. Chemie-Kapsel produzieren."
SPUDkilled=GUIDEBOT: "Spezialproduktions-Mehrzweckdrone terminieren."
SPUDscores=GUIDEBOT: "Spezialproduktions-Mehrzweckdrone hat den Bereich verlassen."
SupplyAlarm=GUIDEBOT: "Einer der Roboter hat einen lokalen Alarm ausgelöst!"
SupplyAlarmPlayer=GUIDEBOT: "Der Schalter ist für unbefugtes Personal tabu."
SweitzerMAX=SHUTTLE:  "Grossartig, Sie haben Dr. Schweitzer gefunden. Aber ich werde auf keinen Fall mit dieser alten Kiste in den Hochsicherheitstrakt fliegen.  Sie müssen eine Möglichkeit finden, Schweitzer an einen sichereren Ort zu bringen - am besten in die Minimal-Sicherheitsebene."
SweitzerMINLockedOut=SHUTTLE:  "Gute Arbeit da drinnen.  Ich erwähne es nur ungern, aber ich habe hier noch ein Problem. Es gibt hier oben im Turm ein Kraftfeld, das deaktiviert werden muss, bevor ich reinkommen kann - tut mir leid."
WhatTheHell=SHUTTLE: "Hey, ist da unten alles in Ordnung?!  Ich weiss zwar nicht, wie Sie das gemacht haben, aber es scheint, als ob sich das Gefängnis im Alarmzustand befindet. Dem Funkverkehr nach zu urteilen, wird eine Art Notfallevakuierung durchgeführt." 
X1OldSecurityPassD=Sicherheitspass X-1 
Y1MedSecurityPassA=Sicherheitspass Y-1 

                                              
