//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     13

// Message List
Area1=Area 1
Area1Active=
Area2=Area 2
Area2Active=
Area3=Area 3
Area3Active=
EndLevelMessage=Material Defender... We're losing your signal, anything wierd down there?
EntranceDoorMessage=Testing Protocol Active!
IntroBriefingMessage=Beagle: I'm not sure what you'll find in this place.  Explore the area and get out.
IntroHUDmessage=IncomingTransmission ... SHIFT- F8
ObjectivesCompleted=Area1Active
ReturnPathActive=
