//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     33

// Message List
All4Radio=ROBOGUÍA: "Transmisión de comunicador de vínculo de datos activada."
All4Radio2=ROBOGUÍA: "Ahora debes de tener acceso al arsenal."
DataFinal=ROBOGUÍA: "Ya tenemos en el cartucho los datos que necesitamos. Vuelve a la superficie para completar tu misión."
DataNodes=ROBOGUÍA: "Pon el cartucho de datos entre los nodos de carga."
DataOriginal=ROBOGUÍA: "El cartucho está vacío. Busca los nodos de carga y pon el cartucho entre ellos."
DestroyedSuper=ROBOGUÍA: "Superladrón destruído. El cartucho ya debe contener los datos."
DestroyedThief=ROBOGUÍA: "Ladrón destruído. Recupera el cartucho de datos."
EndLevel=Datos de investigación de Sweitzer recuperados.
FalseTransfer=ROBOGUÍA: "No hay ningún cartucho al que transferir datos."
ForceFieldDeactivated=Campos de fuerza desactivados.
IntroMessage=Tiris - Instalación de la estación Piccu del PTMC| y laboratorio en Beta Ceti del SRAD
KillSuper=ROBOGUÍA: "Destruye el superladrón para recuperar el cartucho de datos."
LTSelfDestruct=ROBOGUÍA: "La torre de iluminación no puede seguir descargando y se está autodestruyendo."
MainKeyCard=Clave de seguridad
PlaceCartridge=ROBOGUÍA: "El cartucho de datos está listo para la carga. Busca los controles de datos."
RadioRoomFirst=ROBOGUÍA: "Acoplamiento de energía principal activado."
RadioRoomUnlock=ROBOGUÍA: "Energía auxiliar desviada al sistema de vínculo de datos."
SecretArea=¡Has encontrado una zona secreta!
SecurityDoor=Acceso de seguridad denegado.
SuperIntro=Superladrón
TempGetData=ROBOGUÍA: "El cartucho de datos está en algún lugar de este laboratorio."
ThiefGotIt=ROBOGUÍA: "El ladrón ha robado el cartucho de datos. Mátalo para recuperarlo."
Uploading=ROBOGUÍA: "Cargando datos del virus en el cartucho."
UploadNode=ROBOGUÍA: "Estos nodos de carga transmiten los datos a cualquier dispositivo que se coloque entre ellos."
