
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     14



// Message List

Area1=ROBOT-GUIDA: "Area 1"

Area2=ROBOT-GUIDA: "Area 2"

Area3=ROBOT-GUIDA: "Area 3"

EndLevelMessage=BEAGLE: Difensore della Materia... Stiamo perdendo il tuo segnale! Noti niente di strano laggiù?

EntranceDoorMessage=ROBOT-GUIDA: "Protocollo di prova attivato!"

IntroBriefingMessage=BEAGLE: Non so bene che cosa troverai in questo posto. Esplora la zona e fa rapporto alla base.

IntroHUDmessage=Trasmissione in arrivo da Beagle ... (MAIU - F8)

Nothing=

