
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     45



// Message List

1ReactorOn=ROBOT-GUIDA: "Reattore 1 di 5 riattivato. Convertitori di energia disponibili."

30SecondsLeft=ROBOT-GUIDA: "Rimangono 30 secondi per l'evacuazione! Presto!"

BLANK=

Critical=Livello critico Schermo di protezione!

DefendReactorsShort= ROBOT-GUIDA: "Difendi i reattori per 12 minuti e poi scappa!"

DefendThoseReactors2=RED ACROPOLIS: "Siamo attaccati!  Difendi tre reattori su cinque finché non ti daremo il segnale. Tutto il personale deve raggiungere le navette d'evacuazione entro 12 minuti. Una volta in orbita, faremo esplodere i reattori per cancellare le prove!"

Destroyed=ROBOT-GUIDA: "Il reattore è stato disattivato!"

EnergyConvertedToShields=ROBOT-GUIDA: "Trasferimento di energia agli schermi del reattore in atto!"

EnergytoShield=RED ACROPOLIS: "Troverai in ogni reattore un convertitore energia/schermo. Basta sparargli contro con le armi ad energia per attivare gli schermi di protezione dagli attacchi. Se serve maggiore energia, c'è un centro di energia a metà del tunnel 3."

EntranceDoorMessage=ROBOT-GUIDA: "Il blocco d'emergenza di Red Acropolis è attivo!"

ExitOnly=ROBOT-GUIDA: "Solo uscita d'emergenza!"

GetThoseReactorsMore=RED ACROPOLIS: "Qui Harper. È necessario far ripartire i reattori. Colpisci le pompe a fusione alla base di ogni reattore. Avremo bisogno di almeno 3 reattori in attività per avere energia sufficiente per la fuga. L'evacuazione completa richiederà circa 12 minuti: cerca di farci guadagnare tempo!"

Health25=Livello schermo 25 per cento...

Health50= Livello schermo 50 per cento...

Health75= Livello schermo 75 per cento...

HITPOINTS=Punti a segno sul reattore : %f

IncomingMessage=Messaggio in arrivo da Red Acropolis... (MAIUSC-F8)

IntroMessage=Marte - Centro di Ricerche di Red Acropolis|

OOPS=RED ACROPOLIS: "Stiamo perdendo energia dalla griglia! I sistemi di evacuazione d'emergenza cedono! Temo che ci resti solo la resa."

Reactor1Started=ROBOT-GUIDA: "Il reattore 1 è ora operativo."

Reactor1Status=Stato del reattore 1 :

Reactor2Started=ROBOT-GUIDA: "Il reattore 2 è ora operativo."

Reactor2Status=Stato del reattore 2 :

Reactor3Started=ROBOT-GUIDA: "Il reattore 3 è ora operativo."

Reactor3Status=Stato del reattore 3 :

Reactor4Started=ROBOT-GUIDA: "Il reattore 4 è ora operativo."

Reactor4Status=Stato del reattore 4 :

Reactor5Started=ROBOT-GUIDA: "Il reattore 5 è ora operativo."

Reactor5Status=Stato del reattore 5 :

ReactorDisabled=ROBOT-GUIDA: "Il reattore è disattivato!

ReactorHUDLabel=Reattori:

ReactorsOnline=ROBOT-GUIDA: "Tutti e 5 i reattori sono in attività."

SelfDestruct=RED ACROPOLIS: "Stiamo inizializzando la sequenza del conto alla rovescia per fare esplodere i reattori... Hai 90 secondi per guadagnare la distanza minima di sicurezza prima che arrivino allo stato critico! Scappa... PRESTO!"

SelfDestruct=ROBOT-GUIDA: "Ce l'hanno fatto a salvarsi. Vai all'uscita prima che inizi la sequenza di autodistruzione!"

Shake=Scuoti la mina!

ShieldsAtMax=ROBOT-GUIDA: "Raggiunto massimo livello di sicurezza!"

StartTimer=Avvia il temporizzatore!

Testing=Prova!

WereGettinOut=RED ACROPOLIS: " Bel lavoro! Tutto il personale presente e le navette sono pronte al decollo. L'autodistruzione dei reattori avverrà in 90 secondi, perciò scappate subito! Correte all'uscita presso il fulcro principale!"

