//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     11

// Message List
BPDefeated=GUIDEBOT: "PTMC Mercenaries defeated!"
CartridgeError=GUIDEBOT: "You can't drop the Data Cartridge here!"
CinematicAmbush=PTMC Mercenaries
CinematicDataCart=Uploading Data to Suzuki
CinematicEndCam=
CinematicIntroCam=Earth - Seoul, Korea
Debug1=Difficulty Adjustment: %f
Debug2=Should SHAKE!
GetOut=GUIDEBOT: "Upload successful!  Suzuki should now have the data!"
PutTheCartridge=GUIDEBOT: "Put the Data Cartidge in the middle of the upload room!"
