
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     57



// Message List

BLANK=

BossIntroductionText=L'Homunculus|

BuilderCollectorsCorrectlyPlaced=GUIDEBOT: "Une porte a été déverrouillée."

Builders3secondsleft=GUIDEBOT: "Il vous reste trois secondes !"

BuildersDoorMessage=GUIDEBOT: "Vous êtes un Agent des Collecteurs, vous pouvez donc passer."

BuildersPuzzhint=GUIDEBOT: "Puits de ventilation détecté."

BuildersPuzzMessage=GUIDEBOT: "Il faut aller vite !"

BuildersPuzzMessage2=GUIDEBOT: "L'icône des constructeurs couronne la voie choisie !"

BuildersTimerExpired=GUIDEBOT: "Délai expiré !"

CollectorsDoorMessage=GUIDEBOT: "Vous êtes un agent des constructeurs, vous pouvez donc passer."

EndPath=GUIDEBOT: "Fin du Passage !"

EnterPriestPuzzle=GUIDEBOT: "Vous venez d'entrer dans Le Puzzle du Prêtre."

ExitPriestPuzzle=GUIDEBOT: " Vous avez quitté Le Puzzle du Prêtre."

FirstPickupBuilder=L'Icône des Constucteurs

FirstPickupCollector=L'Icône des Collecteurs

FirstPickupPriest=L'Icône du Prêtre

IntroLevelMessage=Mars - Canyons Noctis Labyrinthus|

InvGame=Vous pouvez choisir des objets dans votre inventaire par les touches par défaut, ^ et $[EC2]$.  Pour utiliser ou déployer un objet, la touche par défaut est 'Entrée'[E3].

InvHUD=GUIDEBOT: "N'oubliez pas d'utiliser votre inventaire avec les icônes... SHIFT-F8."

KeyAlreadyThere=GUIDEBOT: "Deux en un ne font pas trois..."

PlaceBuildersKey=GUIDEBOT: "Vous avez placé l'icône des constructeurs."

PlaceCollectorsKey=GUIDEBOT: "Vous avez placé l'icône des collecteurs."

PlacePriestKey=GUIDEBOT: "Vous avez placé l'icône du prêtre."

PriestGalleryDoorLocked=GUIDEBOT: "Vous n'êtes pas digne."

PriestHallDoorLocked=GUIDEBOT: "Le Grand Prêtre ne vous laissera pas entrer !"

PriestKeyCorrectlyPlaced=GUIDEBOT: "L'Homunculus attend !"

PriestPuzzleEnter=GUIDEBOT: "Le long des colonnes marche le Prêtre Elu."

PriestPuzzleGoofed=GUIDEBOT: "Vous n'êtes pas l'élu !"

PriestPuzzleSolved=GUIDEBOT: "Vous avez prouvé votre dignité !"

Test=Test

Testing=

ThisDoorDoesNotAnswer=GUIDEBOT: "Cette porte ne veut pas vous répondre."

TugMessage1=REMORQUEUR: "On dirait qu'on a trouvé le vaisseau ! Il a l'air en pas trop mauvais état, vu d'ici."

TugMessage2=REMORQUEUR: "On attendra ici pendant que vous faites le ménage..."

TugMessage3=REMORQUEUR: "Euh, on a un champ de force qui nous bloque le passage... Vous pourriez pas nous en débarrasser assez vite ?"

TugMessage4=REMORQUEUR: "On dirait que le boulot n'est pas fini ! Attention !"

TugMessage5=REMORQUEUR: "Dépêchez-vous de détruire ce truc qu'on puisse se tirer d'ici !"

TugMessage6=REMORQUEUR: "Bon, à nous de jouer maintenant."

TugMessageShipPickUp=REMORQUEUR: "OK. Le champ de force est coupé. On va aller le chercher ce vaisseau..."

TugMessageStart=REMORQUEUR: "Vous êtes tout seul à partir d'ici..."

TugStartMessage2=REMORQUEUR: "On va garder le silence radio tant qu'on aura pas de visuel du vaisseau."

XsecsOntheClock=REMORQUEUR: ""%.0f secondes chrono !"

YoucantUseKeyHere=

[EC1]Vérifiez le mapping des touches pour le clavier francais. Les touches ne sont vraisemblablement pas les même. 
[EC2]Vérifiez le mapping des touches pour le clavier francais. Les touches ne sont vraisemblablement pas les même. 
[E3]Vérifiez le mapping des touches pour le clavier francais. Les touches ne sont vraisemblablement pas les même.

[E4]Vérifiez le mapping des touches pour le clavier francais. Les touches ne sont vraisemblablement pas les même.

