
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     11



// Message List

BPDefeated=ROBOT-GUIDA: "Mercenari del PTMC sconfitti!"

CartridgeError=ROBOT-GUIDA: "Non puoi gettare qui la cartuccia dati!"

CinematicAmbush=Mercenari PTMC 

CinematicDataCart=Traferimento dati a Suzuki

CinematicEndCam=

CinematicIntroCam=Terra - Seul. Corea

Debug1=Rettifica difficoltà: %f

Debug2=Occorre SHAKE!

GetOut=ROBOT-GUIDA: "Trasferimento dati riuscito!  Ora Suzuki dovrebbe avere i dati!"

PutTheCartridge=ROBOT-GUIDA: "Metti la cartuccia dati al centro della sala di trasferimento!"

