//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     51

// Message List
AftMatcenCheck=ROBOGUÍA: "Inspeccionando disparador de Matcen de popa."
AftSwCinema=Desactivar Matcen de popa.
AuxCoreDoor=ROBOGUÍA: "Acceso al núcleo auxiliar del motor denegado. Busca otra forma de llegar."
Bay62Door=ROBOGUÍA: "La puerta de acceso al muelle 62 está bloqueada. Busca otra forma de llegar."
Bay62Fuse=ROBOGUÍA: "Centro de materialización del muelle 62 desactivado."
Bay62Game=11:37.04.04.3750 CUADERNO DE BITÁCORA; ID ALA DE CAZA 62. COMUNICADO DE M. KELLY: "Nuestros esfuerzos han sido infructuosos. Sabemos que ahora controlan por lo menos dos cazas StarHawk. La infección se ha extendido entre los robots trabajadores. Estoy evacuando a mis hombres."
Bay62Hud=Descargado el cuaderno de bitácora del muelle 62... (MAYÚS+F8)
Bay62Lance=ROBOGUÍA: "Torretas desactivadas."
BayInfoGame=07:02.04.04.3750: Entrega estación espacial PTMC 432178: "Registrado a bordo el pedido de piezas para Matcen."
BayInfoHud=Descargado el cuaderno de bitácora del muelle 36... (MAYÚS+F8)
Cleanup=COMANDANTE DEL CED: "Limpieza de las tropas de asalto que queden."
CoreAccFF=ROBOGUÍA: "Acceso al núcleo protegido. Busca otra forma de entrar."
CoreInfo1=11:11:04.04.3750 Descargado el cuaderno de bitácora... (MAYÚS+F8)
CoreInfo2=11:11.04.04.3750  ¡ALARMA DE INTRUSOS! "Puerta de acceso nº 79.287 al núcleo del motor desactivada por el usuario con ID nº 80-84."
CoreRads=ROBOGUÍA: "Interferencia grave de masa."
DangerEngine=ROBOGUÍA: "ADVERTENCIA: Zona de subida de voltaje del motor."
EndCine=
EndMission=COMANDANTE DEL CED: "Has acabado con todas las tropas de asalto. ¡Buen trabajo."
EngineDown=ROBOGUÍA: "Tercer objetivo cumplido. "Apagado del núcleo del motor."
EngineMisfire=ROBOGUÍA: "ADVERTENCIA: Fallo del motor."
EngineTakover=COMANDANTE DEL CED: "Las tropas de asalto se han hecho con el control del motor..."
GotReconInterface=Interfaz de reconocimiento
IntroText=Órbita de Marte - CED| Transportador de nave insignia Expediator
JeffriesID=ROBOGUÍA: "Tubo de Jeffries de popa.  Es posible pasar desde aquí a la sección de proa."
LandingDoor62=ROBOGUÍA: "La puerta de acceso principal al muelle 62 está bloqueada. Busca otra forma de llegar."
LeaderCinema=Buscar y destruir: Comandante de la legión Victorious
LeaderTaunt1=RADIO DEL CED: "Aquí el comandante de la legión Victorious..."
LeaderTaunt2=RADIO DEL CED: "Vamos a tomar el control del Expediator."
LeaderTaunt3=RADIO DEL CED: "Aniquilaremos a todas las unidades que no se rindan de inmediato."
LeaderTaunt4=RADIO DEL CED: "No sangramos, así que no nos sentimos identificados."
LeaderTaunt5=RADIO DEL CED: "¡Alto...!"
LevelObjA=ROBOGUÍA: "Has conseguido desactivar el Matcen de popa."
LevelObjtives1=Objetivos principales: | 1. DESACTIVAR MATCEN DE POPA | Destruir conmutador de anulación manual.
LevelObjtives2=2. Buscar y destruir | Comandante de la legión Victorious.
LevelObjtives3=Neutralizar amenaza de toma de control hostil: | REDUCIR | Rojo, verde y blanco | LEGIÓN DE DEFENSA DE TROPAS DE ASALTO.
MainDeckGame=11:22.04.04.3750 ESTADO DE LA NAVE CUADERNO DE BITÁCORA DEL ACORAZADO C.E.D. EXPEDIATOR: "Un virus desconocido ha contaminado los sistemas de defensa de la nave, incluidas las unidades ST. Hemos aislado toda la sección de popa de la nave. Espero que todos hayan podido salir a tiempo. Se están investigando las posibles soluciones."
MainDeckHud=Descargado el cuaderno de bitácora de estado de la nave... (MAYÚS+F8)
NoEntry=EN CUARENTENA: No hay nada más a partir de aquí.
NoEntry62=Esta puerta de acceso al hangar está soldada. Encuentra otra manera de entrar.
PplDoors1=Acceso de personal restringido por cuarentena.
PrimaryObjB=MANDO DEL CED: "¡Felicidades! Has cumplido tu objetivo secundario."
PrimerDamage=ROBOGUÍA: "¡Campo de plasma! La nave ha sufrido daños."
RobotCount=Aún te quedan %d soldados de asalto infectados.
SecondaryObjective=¡EMERGENCIA! | FALLO DEL MOTOR...|
ShipInfo1=Descargado el cuaderno de bitácora de sucesos de la nave... (MAYÚS+F8)
ShipInfo2=10:59.04.04.3750: "Éste es el cuaderno de bitácora auditivo de emergencia de Kalmer, ingeniero jefe de la zona de popa. Se ha enviado el Matcen después de instalarle las piezas de repuesto del nuevo pedido 47632-09. Está produciendo tropas de asalto infectadas. Es imposible detener la fabricación. Evacuando tripulación de reparación."
SpyPlead=DRONE CAZADOR: "Por favor... No os haré nada si no me disparáis. No soy como los demás."
StormtroopersCine=Acaba con esos tipos...| Antes de que acaben contigo
