//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     37

// Message List
AllDone=GUIDEBOT: "Ziel erreicht!  Verlassen Sie die Fabrik, um Ihre Mission zu beenden!"
AllStabsDone=GUIDEBOT: "Alle 4 Stabilisatoren unterbrochen!"
Blank=
CovDamaged=FRACHTSCHIFF: Bitte helfen Sie uns!  Wir erleiden beträchtlichen Schaden!
CovDanger=FRACHTSCHIFF: Wir sind in Gefahr!
CovDropOff=FRACHTSCHIFF: Lassen Komponente zum Aufheben herunterfallen!
CovEntering=FRACHTSCHIFF: Laufe in die Raumfahrzeugfabrik ein 
CovFFHelp=FRACHTSCHIFF: Wir brauchen Ihre Hilfe, um durch diese Kraftfelder in den Lagerbereich zu kommen.  Beeilen Sie sich!
CovGettingPummeled= FRACHTSCHIFF: Wir werden von PTMC-Kräften angegriffen!  Bitte um Hilfe!
CovInClear=FRACHTSCHIFF: Momentan ist bei uns alles klar!
CovLeaveMeAlone=FRACHTSCHIFF: Pasen Sie auf, wo Sie hinzielen!
CovLeaving=FRACHTSCHIFF: Unsere Arbeit ist hier getan!  Danke für Deine Hilfe!
CovPickup=FRACHTSCHIFF: Hebe eine Schiffskomponente auf.
CovRepaired=FRACHTSCHIFF: Reparatur abgeschlossen.  Setze Mission fort!
CovShutDown=FRACHTSCHIFF: Zu grosser Schaden! Schalte ab, um Reparaturen durchzuführen!
CovStillStuckFF=FRACHTSCHIFF: Es ist uns immer noch nicht möglich, dieses Kraftfeld zu umgehen!  Bitte um Unterstützung!
CovThanksFF=FRACHTSCHIFF: Vielen Dank für die Hilfe!
DestroyedAnt=GUIDEBOT: "Übertragungsantenne zerstört!"
DestroyedRadar=GUIDEBOT: "Überwachungsradar zerstört!"
Disruptor=Seismischer Unterbrecher
DoStabs=GUIDEBOT: "Unterbrechen Sie die Stabilisatoren, um Ihre Mission fortzusetzen!"
EndLevel=
IntroCam=Merkur - PTMC Raumfahrzeugfabrik
StabAssemblyDone=Der seismische Stabilisator des Montagewerks| wurde unterbrochen!
StabAssemblyPower=GUIDEBOT "Montagewerk Stabilisator schaltet auf Passivmodus!"
StabControlDone=Der seismische Stabilisator des Kontrollzentrums | wurde unterbrochen!
StabControlPower=GUIDEBOT: "Kontrollzentrum Stabilisator schaltet auf Passivmodus!"
StabFactoryDone=Der seismische Stabilisator der Hauptfabrik| wurde unterbrochen!
StabFactoryPower=GUIDEBOT: "Hauptfabrik Stabilisator schaltet auf Passivmodus!"
StabStoreDone=Der seismische Stabilisator des Lagerzentrums| wurde unterbrochen!
StabStorePower=GUIDEBOT: "Lagerzentrum Stabilisator schaltet auf Passivmodus!"
TempGoal=GUIDEBOT: "Leiten Sie ein Ablenkungsmanöver ein, indem Sie die Stabilisatoren unterbrechen, während das verdeckte Frachtschiff Komponenten einsammelt!"
Testing=Ablenkungslevel: %f
Testing2=Schutzschildlevel: %f
Transmitter=Empfange verschlüsselte Übertragung ...
TransmitterHave=GUIDEBOT: "Um eine Bildübertragung des Frachtschiffs zu erhalten, müssen Sie Ihren Geheimsender verwenden!"

