
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     37



// Message List

AllDone=ROBOT-GUIDA: "Obiettivi raggiunti! Per completare la missione fuggi dalla fabbrica!"

AllStabsDone=ROBOT-GUIDA: "Tutti e 4 gli stabilizzatori sono fuori uso!"

Blank=

CovDamaged=NAVE CARGO: Per favore aiuto! Abbiamo  subito gravi danni!

CovDanger=NAVE CARGO: Siamo in pericolo!

CovDropOff=NAVE CARGO: Sganciamo componente da raccogliere!

CovEntering=NAVE CARGO: Stiamo entrando nella fabbrica d'astronavi

CovFFHelp=NAVE CARGO: Abbiamo bisogno d'aiuto per superare questi campi di forza nell'area di magazzinaggio. Svelti!

CovGettingPummeled=NAVE CARGO: Le forze del PTMC ci stanno facendo a pezzi! Chiediamo aiuto! 

CovInClear=NAVE CARGO: Per il momento siamo salvi!

CovLeaveMeAlone=NAVE CARGO: Attenti a dove mirate!

CovLeaving=NAVE CARGO: Il nostro lavoro qui è finito! Grazie dell'aiuto! 

CovPickup=NAVE CARGO: Sto raccogliendo un componente della nave.

CovRepaired=NAVE CARGO: Riparazioni completate.  Riprendiamo la missione! 

CovShutDown=NAVE CARGO: Troppi danni! Chiudiamo tutti i sistemi per riparazioni!

CovStillStuckFF=NAVE CARGO: Non siamo ancora in grado di aggirare i campi di forza! Forniteci assistenza! 

CovThanksFF=NAVE CARGO: Grazie dell'aiuto!

DestroyedAnt=ROBOT-GUIDA: "Antenna trasmissioni distrutta!"

DestroyedRadar=ROBOT-GUIDA: "Radar di sorveglianza distrutto!"

Disruptor=Disruttore sismico

DoStabs=ROBOT-GUIDA: "Per completare la missione distruggi gli stabilizzatori!"

EndLevel=

IntroCam=Mercurio - Fabbrica astronavi del PTMC 

StabAssemblyDone=Lo stabilizzatore sismico della fabbrica di montaggio è stato distrutto!

StabAssemblyPower=ROBOT-GUIDA "Stabilizzatore fabbrica di montaggio commutato in modalità passiva!" 

StabControlDone=Lo stabilizzatore sismico del centro di controllo è stato distrutto!

StabControlPower=ROBOT-GUIDA: "Stabilizzatore centro di controllo commutato in modalità passiva!" 

StabFactoryDone=Lo stabilizzatore sismico della fabbrica principale è stato distrutto!

StabFactoryPower=ROBOT-GUIDA: "Stabilizzatore fabbrica principale commutato in modalità passiva!"

StabStoreDone= Lo stabilizzatore sismico del centro di magazzinaggio è stato distrutto!

StabStorePower=ROBOT-GUIDA: "Stabilizzatore centro di archiviazione commutato in modalità passiva!"



TempGoal=ROBOT-GUIDA: "Distruggi gli stabilizzatori per creare una diversione mentre la nave cargo segreta raccoglie i componenti!"

ROBOT-GUIDATesting=Livello Diversione: %f

Testing=Livello distrazione: %f

Testing2=Livello Schermi: %f

Transmitter=Ricezione trasmissione criptata in arrivo...

TransmitterHave=ROBOT-GUIDA: "Per ricevere una trasmissione video dalla nave cargo, utilizza il trasmettitore segreto!"

