//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     48

// Message List
1stInvalidPassOffense=PUESTO DE CONTROL: "No es posible conceder permiso de seguridad. Espera a que llegue más ayuda."
2ndInvalidPassOffense=PUESTO DE CONTROL: "Permiso de seguridad denegado. Se ha avisado a las fuerzas de seguridad."
AnotherTurretGone=ROBOGUÍA: "Torreta de defensa de perímetro destruída."
ChemicalReactionAlert=ROBOGUÍA: "¡PELIGRO! Contaminación por depósitos de ácido. Alarma de peligro biológico nivel 4. Evacuar nivel de máxima seguridad.
ChemicalReactionSwitches=ROBOGUÍA: "Se ha activado el bloqueo químico de seguridad."
ComputerDestroyed=ROBOGUÍA: "El superordenador de registros de la cárcel de Novak ha sido destruído."
DontShootMe=LANZADERA: "No seas muy duro con mis escudos."
Empty=
EndLevel=
EscortShuttle=LANZADERA:  "No me vendría mal tener escolta en este momento."
ForcefieldDown=LANZADERA: "El campo de fuerza está desactivado, así que ya puedo escoltarte para recoger a Sweitzer."
ForcefieldDownEarly=ROBOGUÍA: "El campo de fuerza del hangar de transferencia de presidiarios está desactivado."
G1MinSecurityPassB=Pase de seguridad G-1
IncomingMessage=Recibiendo transmisión de lanzadera...  (MAYÚS+F8)
InnerTowerForcefields=ROBOGUÍA: "Campos de fuerza desactivados."
IntroMessage=Phobos - Cárcel corporativa Novak
LoadedSweitzer=LANZADERA:  "Sweitzer está a bordo, y estamos listos para salir. ¡Cubridme!"
LoadingSweitzer=LANZADERA:  "Vamos a subir al doctor a bordo."
MaximumSecurityClearance=PUESTO DE CONTROL: "Obtenido permiso de seguridad de nivel máximo."
MediumSecurityClearance=PUESTO DE CONTROL: "Obtenido permiso de seguridad de nivel medio."
MinimumSecurityClearance=PUESTO DE CONTROL: "Obtenido permiso de seguridad de nivel mínimo."
OneTurretDown=LANZADERA: "De acuerdo, ya hemos derribado una torreta del perímetro; sólo quedan cuatro. Esperaremos en un barranco cercano hasta que hayas asegurado la zona. Que tengas suerte."
R1MaxSecurityPassC=Pase de seguridad R-1
RecordsNodeDestroyed=ROBOGUÍA: "El nodo de seguridad de registros de la cárcel de Novak ha sido destruído."
SECRETAREA=¡Has encontrado una zona secreta!
SecurityPassNotUsableHere=ROBOGUÍA: "Este pase de seguridad no sirve para nada aquí."
SecurityPassReturned=ROBOGUÍA: "El pase de seguridad se ha devuelto al dispensador."
ShuttleMoveToTower=LANZADERA: "Parece que las defensas del perímetro están despejadas, y se han desactivado los campos de fuerza del hangar de suministros.  Iré a la torre de seguridad. Avísame cuando hayas encontrado a Sweitzer. Parece que sólo es posible entrar por el hangar de suministros."
ShuttleUnderAttack=LANZADERA: "Las cosas se están poniendo feas por aquí, y no nos vendría mal tener refuerzos. Estoy rodeado de agentes de seguridad."
SPUDhasTheBall=DRONE SPU: "Transportando cápsula química."
SPUDisBorn=ROBOGUÍA: "Llamando al robot de producción especial. Produciendo cápsula de proceso químico."
SPUDkilled=ROBOGUÍA: "Eliminando al robot de producción especial."
SPUDscores=ROBOGUÍA: "El robot de producción especial ha abandonado la zona."
SupplyAlarm=ROBOGUÍA: "Un robot ha activado una alarma local."
SupplyAlarmPlayer=ROBOGUÍA: "El conmutador no está al alcance del personal no autorizado."
SweitzerMAX=LANZADERA:  "¡Estupendo! Has encontrado al doctor Sweitzer. Pero no estoy dispuesto a meterme en la zona de máxima seguridad con esta lata de sardinas. Será mejor que encuentres la forma de llevarlo a un lugar menos peligroso; a ser posible, la zona de mínima seguridad."
SweitzerMINLockedOut=LANZADERA:  "Buen trabajo. Siento tener que comentarlo, pero me ha surgido otro problema aquí arriba. En la parte superior de la torre hay un campo de fuerza, y no puedo entrar si no está desactivado. Lo siento.
WhatTheHell=LANZADERA: "¿Va todo bien por ahí abajo? No sé qué has hecho, pero parece que la cárcel está en alerta roja. A juzgar por los mensajes de radio, parece que están llevando a cabo una evacuación de emergencia.
X1OldSecurityPassD=Pase de seguridad X-1
Y1MedSecurityPassA=Pase de seguridad Y-1
