//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     30

// Message List
CameraActivation=GUIDEBOT: "Empfange Bild von Überwachungskamera..."
ContainmentDoorUnlocked=Eindämmungstür entriegelt.
Controller=GUIDEBOT: "Reserve-Oberflächenverteidigungsysteme werden an das Primärsystem gekoppelt."
ControlVulnerable=GUIDEBOT: "Die primäre Oberflächensystemsteuerung ist jetzt ungeschützt!"
CoolersAllGone=GUIDEBOT: "Hauptkühlsystem ausgefallen.  Notfall-Kühlsystem wird aktiviert."
DoThis=GUIDEBOT: "Finden Sie die Virusproben, und verlassen Sie die Einrichtung so schnell wie möglich!"
FFDisable1=GUIDEBOT: "Hilfsenergie der Eindämmungskraftfelder abgeschaltet!"
FFDisabled=GUIDEBOT: "Kraftfelder deaktiviert!  Zugang zum Virus-Eindämmungsraum gewährt."
FFKeyPickup=GUIDEBOT: "Zugang zur Sicherheitssystemsteuerung gewährt."
Finished=
IntroMessage=Asteroid Ceres - Geheimer PTMC | Forschungs-Bunker C4
MagnetActivated=GUIDEBOT: "Abwärtsführender magnetischer Beschleuniger aktiviert.  Sicherheitstüren entriegelt."
MagnetTube1=GUIDEBOT: "Kontrollraumschloss 1 von 2 deaktiviert!"
MagnetTubeDoorUnlock=GUIDEBOT: "Kontrollraumzugang gewährt!  Tür entriegelt!"
ManualActivation=GUIDEBOT: "Dieses Gerät benötigt eine direkte Aktivierung."
NeedFFKey=GUIDEBOT: "Sie sind nicht befugt, dieses Steuerungssystem zu verwenden."
PathEnd=EndLevel
SecretArea=Sie haben einen geheimen Bereich gefunden!
SteamRelease=GUIDEBOT: "Dampfausstoss aktiviert."
SuperHeaterShutdown=GUIDEBOT: "Hochtemperatur-Viruseindämmungsgerät funktionsunfähig."
TurretsDeactivated=GUIDEBOT: "Primäre Systemsteuerung zerstört!  Oberflächenverteidigungssysteme ausser Kraft gesetzt!"
TurretsInvuln=GUIDEBOT: "Die grossen Gefechtstürme sind zu robust, um sie einfach zu zerschiessen!  Sie müssen sie auf eine andere Weise bewältigen!"
UpperTubeActivate=GUIDEBOT: "Abwärtsführende Fahrstuhlröhre aktiviert."
Virus1Collected=Sie haben einen Virus!
Virus2Collected=Grossartige Arbeit!  Sie haben beide Virusproben eingesammelt.
VirusDescription=GUIDEBOT: "Sammeln Sie beide Proben ein, und verlassen Sie schnellstens diese Einrichtung!"

