//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     59

// Message List
BeamIgnited=GUIDEBOT: "Sie haben den Richtstrahlsender aktiviert!  Schützen Sie die Übertragung, bis sie abgeschlossen ist..."
BeamIgniteError1=GUIDEBOT: "FEHLER: Übertragungssystem ist abgeschaltet."
BeamIgniteError2=GUIDEBOT: "FEHLER: Es wurden keine Daten übertragen."
BeamIgniteError3=GUIDEBOT: "FEHLER: Vorhandene Energie nicht ausreichend."
BeamIgniteError4=GUIDEBOT: "FEHLER: Sender des Verteidigungsnetzes abgeschaltet."
BeamIgniteError5=GUIDEBOT: "FEHLER: Senderschild ist aktiv."
BeamIgniteError6=GUIDEBOT: "FEHLER: Falsch ausgerichtete(r) Spiegelknoten entdeckt."
BumpDialError=GUIDEBOT: "FEHLER: Übertragungssystem abgeschaltet..."
BypassConnDisplay=Überbrückungsstecker: %d
DataLinkAlreadyActive=GUIDEBOT: "Dieser DataLink funktioniert jetzt korrekt."
DataLinkError=GUIDEBOT: "FEHLER: Umgehen der infizierten Systeme nicht möglich."
DataLinkFixed=GUIDEBOT: "Sie haben einen Überbrückungsstecker verwendet, um diesen DataLink zu reparieren."
DialCodeEntered=GUIDEBOT: "Wahlcode akzeptiert... Verteidigungsnetz Datenausgabe aktiviert."
DialCodeIncorrect=GUIDEBOT: "FEHLER: Wahlcode ist nicht korrekt."
DialSwitchError=GUIDEBOT: "FEHLER: Übertragungssystem abgeschaltet..."
Empty=
FoundAllBypassConns=GUIDEBOT: "Alle Überbrückungsstecker erhalten."
FoundBypassConn=Überbrückungsstecker 
FoundEquipRmKey=Austattungsraum-Schlüssel
GotCoreMaterial=Anti-Virus-Programm
GotSpareLens=Reserve-Sendestrahllinse
IntroText=Erdorbit - Strategische Operationsplattform der K.E.V.
JournalBeamGame=LOGBUCH: "Manche der neuen Leute denken, sie hätten es schlecht.  An meinem ersten Tag haben sie mich zum Richtstrahlaktivierungsdienst verpflichtet.  Natürlich haben sie vergessen, mir zu sagen, wo sich die Schalter befinden.  Ich habe eine Stunde gesucht, bevor jemand gesagt hat "denk einfach dran, für wen du arbeitest."
JournalBeamHUD=Logbuch des Richtstrahlaufsehers gefunden... (SHIFT - F8)
JournalDialGame=BERICHT: "Das neue Übertragungs-Auswahlsystem ist fertig.  Es erlaubt uns, ein bestimmtes Netzwerk mit unseren Datenübertragungen anzupeilen.  Der Auswahlmechanismus ist eine uhrenähnliche Skala im unteren Technikraum."
JournalDialHUD=Technikraum-Logbuch gefunden... (SHIFT - F8)
JournalPowerGame=LOGBUCH: "Nach dem Vorfall in der letzten Nacht, habe ich die Energieversorgung der Station abgestellt.  Das hat die Erzeugung weiterer infizierter Roboter beendet, aber das bedeutet auch, dass der Richtstrahlsender nicht arbeiten konnte. Wir müssen früher oder später die Energie wieder anschalten..."
JournalPowerHUD=Logbuch des Stationstechnikers gefunden... (SHIFT - F8)
JournalRobotGame=LOGBUCH: "Das letzte Mal, als wir zu übertragen versucht haben, hat ein infizierter Roboter fast unsere Richtstrahllinsen herausgenommen!  Es ist unnötig, zu erwähnen, dass ich um einige Gunboys gebeten habe..."
JournalRobotHUD=Logbuch des Strahlensicherheitswächters gefunden... (SHIFT - F8)
JournalShieldGame=CODE: "Die folgende Deaktivierungsfolge für den Schutzschild des Senders ist verschlüsselt, wie in der KEV-Vorschrift S897 angegeben:  NW - SE - W - NE."
JournalShieldHUD=Deaktivierungscode für den Schutzschild des Senders erhalten... (SHIFT - F8)
JournalVirusGame=LOGBUCH: "Heute habe ich versucht, einen der nicht funktionierenden DataLinks zu reparieren. Er scheint von einem Virus befallen zu sein... aber es ist anders als alles, was ich bisher gesehen habe. Ich möchte gar nicht daran denken, was passieren würde, wenn er sich auf die Arbeiter- und Sicherheitsroboter-Systeme ausbreitet..."
JournalVirusHUD=Logbuch des Datentechnikers gefunden...  (SHIFT - F8)
LensDestroyed=GUIDEBOT: "Der Roboter hat die Linse zerstört!  Sie müssen sie ersetzen..."
LensRobotWarning=GUIDEBOT: "Ein Roboter nähert sich der Linse!"
MirrorNodesUnaligned=GUIDEBOT: "Die Spiegelknoten sind nicht mehr korrekt ausgerichtet!"
OmnicronDisplayed=GUIDEBOT: "Einlesen der Daten abgeschlossen.  Warte auf Übertragungsauswahl..."
PowerInsufficient=GUIDEBOT: "Die für den Richstrahlauslöser bereitgestellte Energie ist nun unzureichend!"
PowerOffline=Energieversorgung %d ist jetzt abgeschaltet.
PowerOnline=Energieversorgung %d ist jetzt angeschaltet.
ShieldCodeIncorrect=GUIDEBOT: "FEHLER: Falsche Schutzschildcodefolge."
ShieldCodeSeqReset=GUIDEBOT: "Die Eingabezeit für die Codefolge ist abgelaufen."
ShieldCodeSeqStart=GUIDEBOT: "Deaktivierungsfolge für den Schutzschild ist aktiviert. Sie haben  15 Sekunden."
ShieldDeactivated=GUIDEBOT: "Der Schutzschild wurde deaktiviert!"
ShuttleFreed=GUIDEBOT: "Sie haben das Rettungs-Shuttle befreit!"
SystemStarted=GUIDEBOT: "Das Übertragungssystem ist bereit."
SystemStarting=GUIDEBOT: "Das Übertragungssystem startet!"
TransmissionComplete=GUIDEBOT: "Das Anti-Virus-Programm wurde übertragen. Gute Arbeit!"
UploadError=GUIDEBOT: "FEHLER: Übertragungssystem ist abgeschaltet."
UploadStarted=GUIDEBOT: "Anti-Virus-Programm auf Übertragungssystem laden..."
UseCoreMaterialFailed=GUIDEBOT: "Sie müssen das Anti-Virus-Programm an einem DataLink aufspielen."
UseLensCompleted=GUIDEBOT: "Die Ersatzlinse ist positioniert!  Übertragung fortsetzen..."
UseLensFailed1=GUIDEBOT: "Sie sind zu weit entfernt, um die Linse zu plazieren!"
UseLensFailed2=GUIDEBOT: "Es wurde bereits eine Linse plaziert!"

