//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     33

// Message List
All4Radio=GUIDEBOT: "Datlink communicator transmission activated!"
All4Radio2=GUIDEBOT: "You should now have access to the armory!"
DataFinal=GUIDEBOT: "The cartridge now has the data we need!  Return to the surface to complete your mission!"
DataNodes=GUIDEBOT: "Put the data cartridge between the upload nodes!"
DataOriginal=GUIDEBOT: "The cartridge is empty!  Find the data upload nodes and place the cartridge there!"
DestroyedSuper=GUIDEBOT: "Super Thief destroyed!  The cartridge should have the data now!"
DestroyedThief=GUIDEBOT: "Thief destroyed!  Retrieve the data cartridge!"
EndLevel=Retrieved Sweitzer's research data
FalseTransfer=GUIDEBOT: "There is no cartridge to transfer data to!"
ForceFieldDeactivated=Forcefield deactivated!
IntroMessage=Tiris - PTMC Piccu Station Facility| & SRAD Beta Ceti Laboratory
KillSuper=GUIDEBOT: "Destroy the Super Thief to retrieve the data cartridge!"
LTSelfDestruct=GUIDEBOT: "The lightning tower can no longer discharge and is self-destructing!"
MainKeyCard=Security Key
PlaceCartridge=GUIDEBOT: "The data cartridge is ready for uploading!  Find the data controls!"
RadioRoomFirst=GUIDEBOT: "Primary power coupling engaged!"
RadioRoomUnlock=GUIDEBOT: "Auxilary power diverted to datlink system."
SecretArea=You Found A Secret Area!
SecurityDoor=Security Access Denied!
SuperIntro=Super Thief
TempGetData=GUIDEBOT: "The data cartridge is somewhere in this lab!"
ThiefGotIt=GUIDEBOT: "The thief has stolen the data cartridge!  Kill him to get it back!"
Uploading=GUIDEBOT: "Uploading virus data to cartridge!"
UploadNode=GUIDEBOT: "These upload nodes will transfer data to any device placed between them"
