
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     59



// Message List

BeamIgnited=ROBOT-GUIDA: "Raggio emettitore attivato! Proteggere la trasmissione finché sarà finita..."

BeamIgniteError1=ROBOT-GUIDA: "ERRORE: Il sistema trasmittente è off-line."

BeamIgniteError2=ROBOT-GUIDA: "ERRORE: Non sono stati trasferiti dati."

BeamIgniteError3=ROBOT-GUIDA: "ERRORE: L'energia fornita è insufficiente."

BeamIgniteError4=ROBOT-GUIDA: "ERRORE: Il trasmettitore della rete difensiva è off-line."

BeamIgniteError5=ROBOT-GUIDA: "ERRORE: Lo scudo antiraggio è attivo."

BeamIgniteError6=ROBOT-GUIDA: "ERRORE: Individuati nodi dello specchio disallineati."

BumpDialError=ROBOT-GUIDA: "ERRORE: Sistema trasmittente spento..."
BypassConnDisplay=Bypass Connectors: %d
DataLinkAlreadyActive=ROBOT-GUIDA: "Questo collegamento dati ora funziona regolarmente."

DataLinkError=ROBOT-GUIDA: "ERRORE: Impossibile aggirare i sistemi infetti."

DataLinkFixed=ROBOT-GUIDA: "Hai utilizzato un connettore bypass per riparare questo collegamento dati."

DialCodeEntered=ROBOT-GUIDA: "Codice accettato. Output rete difensiva attivato."

DialCodeIncorrect=ROBOT-GUIDA: "ERRORE: Codice errato."

DialSwitchError=ROBOT-GUIDA: "ERRORE: Sistema trasmittente fuori uso..."

Empty=

FoundAllBypassConns=ROBOT-GUIDA: "Recuperati tutti i connettori bypass."

FoundBypassConn=Connettore bypass

FoundEquipRmKey=Chiave sala macchine

GotCoreMaterial=Programma antivirus

GotSpareLens=Lente di ricambio emittitore

IntroText=Orbita terrestre - Piattaforma Operazioni |Strategiche del CDT.

JournalBeamGame=GIORNALE: "Alcuni dei nuovi arrivati pensano sia dura. Il primo giorno sono stato assegnato al servizio attivazione raggi. Naturalmente nessuno mi ha detto dove si trovava l'interruttore. L'ho cercato per un'ora, poi qualcuno mi ha detto: "Ricordati per chi lavori".

JournalBeamHUD=Trovato Giornale del controllore del raggio... (MAIUSC-F8)

JournalDialGame=REPORT: "Il nuovo sistema di selezione dell'output del trasmettitore è pronto. Possiamo mirare a una particolare rete con le nostre trasmissioni radio. Il meccanismo di selezione è un quadrante simile a un orologio che si trova nella sala macchine inferiore."

JournalDialHUD=Trovato Report sala macchine... (MAIUSC-F8)

JournalPowerGame=GIORNALE: "Dopo quanto avvenuto la notte scorsa, ho disattivato l'alimentazione della stazione. Così ho interrotto la generazione dei robot infetti, ma l'emittitore non funziona più. Presto o tardi dovremo riattivare l'alimentazione..."

JournalPowerHUD=Trovato Giornale dell'ingegnere della stazione... (MAIUSC-F8)

JournalRobotGame=GIORNALE: "L'ultima volta che abbiamo provato a effettuare una trasmissione, un robot infetto per poco non ha distrutto la lente dell'emittitore! Inutile dire che ho fatto richiesta di qualche gorilla..."

JournalRobotHUD=Trovato Giornale del servizio di sicurezza al raggio... (MAIUSC-F8)

JournalShieldGame=CODICE: "La sequenza di disattivazione dello scudo antiraggio è criptata come specificato nel regolamento S897 del CDT:  NO - SE - O - NE."

JournalShieldHUD=Codice di disattivazione dello scudo antiraggio ricevuto... (MAIUSC - F8)

JournalVirusGame=GIORNALE: "Oggi ho cercato di riparare uno dei collegamenti dati che dava i numeri. Sembra infettato da un virus... ma non ho mai visto niente di simile. Non oso pensare cosa potrebbe succedere se si diffondesse nei sistemi dei robot operai e in quelli della sicurezza..."

JournalVirusHUD=Trovato Giornale del tecnico dati...  (MAIUSC-F8)

LensDestroyed=ROBOT-GUIDA: "Il robot ha distrutto la lente! Occorrerà sostituirla..."

LensRobotWarning=ROBOT-GUIDA: "Un robot sta dirigendosi verso la lente!"

MirrorNodesUnaligned=ROBOT-GUIDA: "I nodi dello specchio non sono più allineati!"

OmnicronDisplayed=ROBOT-GUIDA: "Trasferimento dati completato.  Attendo selezione trasmettitore..."

PowerInsufficient=ROBOT-GUIDA: "L'energia fornita all'attivatore dei raggi è insufficiente!"

PowerOffline=L'Alimentatore %d è ora off-line.

PowerOnline= L'Alimentatore %d è on-line.

ShieldCodeIncorrect=ROBOT-GUIDA: "ERRORE: Errata sequenza codice scudo."

ShieldCodeSeqReset=ROBOT-GUIDA: "È scaduto il tempo per inserire la sequenza del codice."

ShieldCodeSeqStart=ROBOT-GUIDA: "Sequenza di disattivazione dello scudo antiraggio in corso.  Hai 15 secondi."

ShieldDeactivated=ROBOT-GUIDA: "Lo scudo antiraggio è stato disattivato!"

ShuttleFreed=ROBOT-GUIDA: "Hai liberato la navetta per la fuga!"

SystemStarted=ROBOT-GUIDA: "Il sistema trasmittente è pronto."

SystemStarting=ROBOT-GUIDA: "Il sistema trasmittente si sta attivando!"

TransmissionComplete=ROBOT-GUIDA: "Il programma antivirus è stato trasmesso. Bel lavoro!"

UploadError=ROBOT-GUIDA: "ERRORE: Sistema trasmittente off-line."

UploadStarted=ROBOT-GUIDA: "Sto trasferendo il programma antivirus al sistema trasmittente..."

UseCoreMaterialFailed=ROBOT-GUIDA: "Devi trasferire il programma antivirus al Collegamento dati."

UseLensCompleted=ROBOT-GUIDA: "Lenti di ricambio in posizione! Riprendo la trasmissione..."

UseLensFailed1=ROBOT-GUIDA: "Sei troppo lontano per montare le lenti!"

UseLensFailed2=ROBOT-GUIDA: "Una lente è già montata!"

