//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     49

// Message List
1stInvalidPassOffense=CHECKPOINT: "Unable to grant Security Clearance.  Please wait for assistance."
2ndInvalidPassOffense=CHECKPOINT: "Security Clearance Denied!  Security forces alerted!"
AnotherTurretGone=GUIDEBOT: "Perimeter defense turret destroyed."
ChemicalReactionAlert=GUIDEBOT: "DANGER!  Acid tank contamination!  Level 4 biological hazard alert!  Evacuate Maximum Security level!"
ChemicalReactionSwitches=GUIDEBOT: "Chemical Safety lockdown has been engaged."
ComputerDestroyed=GUIDEBOT: "Novak Prison Records Super-computer has been destroyed!"
DontShootMe=SHUTTLE: "Take it easy on my shields!"
Empty=
EndLevel=
EscortShuttle=SHUTTLE:  "I could really use an escort right about now."
ForcefieldDown=SHUTTLE: "The forcefield's down, so I'm ready for you to escort the way to pickup Sweitzer."
ForcefieldDownEarly=GUIDEBOT: "Prisoner Transfer Hangar forcefield has been disabled."
G1MinSecurityPassB=G-1 Security Pass
IncomingMessage=Incoming transmission from shuttlecraft...  (SHIFT-F8)
InnerTowerForcefields=GUIDEBOT: "Forcefields disabled."
IntroMessage=Phobos - Novak Corporate Prison
LoadedSweitzer=SHUTTLE:  "Sweitzer's on board, and we are ready to get out of here.  Cover me!"
LoadingSweitzer=SHUTTLE:  "Let's get the Doctor on board."
MaximumSecurityClearance=CHECKPOINT: "Maximum Level Security Clearance granted."
MediumSecurityClearance=CHECKPOINT: "Medium Level Security Clearance granted."
MinimumSecurityClearance=CHECKPOINT: "Minimum Level Security Clearance granted."
OneTurretDown=SHUTTLE: "Alright, that's one Perimeter Turret down, and four more to go.  We'll be holding up in a ravine nearby until you've secured the area.  Good luck."
R1MaxSecurityPassC=R-1 Security Pass
RecordsNodeDestroyed=GUIDEBOT: "Novak Prison Records Backup Node destroyed!"
SECRETAREA=You Found A Secret Area!
SecurityPassNotUsableHere=GUIDEBOT: "This Security Pass is not useable here."
SecurityPassReturned=GUIDEBOT: "The Security Pass has been returned to it's Dispenser."
ShuttleMoveToTower=SHUTTLE: "Perimeter defenses look clear, and the Supply Hangar forcefields are down.  I'll head for the Main Tower and wait for your signal when you've located Sweitzer.  Looks like the Supply Hangar's your only way in."
ShuttleUnderAttack=SHUTTLE: "Uh, we've got a situation here, and could use some fire support!  I've got security all over me!"
SPUDhasTheBall=SPU DRONE: "Transporting chemical capsule."
SPUDisBorn=GUIDEBOT: "Summoning the Special Production Utility Drone.  Producing chemical processing capsule."
SPUDkilled=GUIDEBOT: "Terminating Special Production Utility Drone."
SPUDscores=GUIDEBOT: "Special Production Utility Drone has left the area."
SupplyAlarm=GUIDEBOT: "One of the robots has sounded a local alarm!"
SupplyAlarmPlayer=GUIDEBOT: "Switch off limits to unauthorized personnel."
SweitzerMAX=SHUTTLE:  "Great, you've found Dr. Sweitzer.  But, there's no way I'm flying into Maximum Security in this old crate.  You'll have to find a way to get him transferred to a safer location--preferably Minimum Security."
SweitzerMINLockedOut=SHUTTLE:  "Good work in there.  I hate to mention it, but, I've got another problem up here.  There's a forcefield at the top of the tower that has to be disabled before I can enter--sorry."
WhatTheHell=SHUTTLE: "Hey, are you ok down there?!  I don't know what you did, but it looks like the Prison is on full alert.  Some kind of emergency evacuation is in progress judging by the radio traffic."
X1OldSecurityPassD=X-1 Security Pass
Y1MedSecurityPassA=Y-1 Security Pass
