
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     52



// Message List

ActivatedMatcen=ROBOT-GUIDA: "Centro Materializzazione attivato!"

Arena1Defeated=ROBOT-GUIDA: "Arena Livello 1 sconfitta. Sei autorizzato a procedere al Livello 2!"

Arena1Enter=Arena Livello 1| Preparati al combattimento!

Arena2Defeated=ROBOT-GUIDA: "Arena Livello 2 sconfitta. Sei autorizzato a procedere al Livello 3!"

Arena2Enter=Arena Livello 2| Preparati al combattimento! 

Arena3Defeated=ROBOT-GUIDA: "Arena Livello 3 sconfitta. Sei autorizzato a procedere al Livello 4!"

Arena3Enter=Arena Livello 3| Preparati al combattimento!

Arena4Defeated=ROBOT-GUIDA:" Arena Livello 4 sconfitta. Sei autorizzato a procedere all'Arena Campionati!"

Arena4Defeated2=ROBOT-GUIDA: "Accesso autorizzato a tutte le aree!"

Arena4Enter=Arena Livello 4| Preparati al combattimento!

Arena4Enter2=Parte 2 dell'Arena Livello 4| Ti attende un bonus!

ArenaChamp=ROBOT-GUIDA: "Sconfitto il campione della Zona test! Accesso alla superficie autorizzato!"

CowFFDisable=ROBOT-GUIDA: "Sequenza campo di forza completata!"

CowPipeActive=ROBOT-GUIDA: "Generatore di controllo attivato!"

DoorUnlocked=Porta sbloccata!

EmergencyOverride=ROBOT-GUIDA: "Esclusione emergenza attivata.  Tutti i campi di forza di sicurezza disattivati."

EndBossBegin=Arena dei Campionati|Preparati alla battaglia!

EndLevel=

EscapedDestroyed=ROBOT-GUIDA: "Rimane da distruggere ancora un generatore!"

EscapedDestroyed2=ROBOT-GUIDA: "Sei riuscito a liberarti dal dispositivo di detenzione!"

EscapedTorture=ROBOT-GUIDA: "Meccanismo di tortura distrutto!"

EscapeTorture2=ROBOT-GUIDA: "I generatori dei campi di forza ora dovrebbero essere ora vulnerabili!"

Forcefield=Campi di forza disattivati!

GonnaClean=ATTENZIONE: Generatori di controllo distrutti! Attivati sistemi di sterilizzazione a calore!  

Guards1=Un avversario eliminato!

Guards2=Due avversari da eliminare!

Guards3=Rimane un solo avversario da eliminare!

IntroMessage=Charon - Zona test del PTMC 

L1Door=Richiesta chiave Livello 1!

L2Door= Richiesta chiave Livello 2!

L3Door= Richiesta chiave Livello 3!

L4Door= Richiesta chiave Livello 4!

Level1Key=Chiave Livello 1

Level2Key= Chiave Livello 2

Level3Key= Chiave Livello  3 

Level4Key= Chiave Livello 4 

LevelStarted=ROBOT-GUIDA: "Raggiungi al più presto possibile la Zona test! È la tua unica possibilità di fuga!  Apriti la strada verso la superficie!"

MainFFDeactivated=ROBOT-GUIDA: "Principali concorrenti dell'arena eliminati. Ora può entrare nell'Arena l'ultimo concorrente!"

MainGuards=ROBOT-GUIDA: "Prima di qualificarti per l'arena dei campionati dovrai eliminare i tutti gli avversari

RecoveredSecret=RECUPERO: Vecchia cartuccia dati. Robot-Guida cerca informazioni utili...

RedUnitsArmed=ROBOT-GUIDA: "Unità di controllo armate e pronte all'esplosione!"

RepairActivated=ROBOT-GUIDA: "Centri riparazione attivati!"

RepairDeactivated=ROBOT-GUIDA: " Centri riparazione disattivati!"

RepairingShip=Sto riparando gli schermi di protezione della tua nave| per riportarla in piena efficienza!

SecretData=Questa cartuccia è consunta e arrugginita, ma il Robot-Guida riesce ad estrarre alcuni dati che potrebbero rivelarsi utili. I dati si riferiscono a un Complesso industriale Segreto che non compare sulle carte di navigazione. Forse varrà la pena di indagare più avanti.

SrepairInit=ROBOT-GUIDA: "Calibrazione unità di riparazione interrotta. Reinizializzare, prego!"

