//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     30

// Message List
CameraActivation=ROBOGUÍA: "Transmitiendo señal de cámara de seguridad..."
ContainmentDoorUnlocked=Se ha desbloqueado la puerta de contención.
Controller=ROBOGUÍA: "Dirigiendo las defensas de superficie de repuesto al sistema principal."
ControlVulnerable=ROBOGUÍA: "El controlador principal del sistema de superficie es ahora vulnerable."
CoolersAllGone=ROBOGUÍA: "Fallo en el sistema de refrigeración principal. Activando anulación de emergencia del control de refrigeración."
DoThis=ROBOGUÍA: "Busca las muestras del virus y sal tan deprisa como puedas."
FFDisable1=ROBOGUÍA: "Cierre del suministro auxiliar de los campos de fuerza de contención."
FFDisabled=ROBOGUÍA: "Campos de fuerza desactivados. Es posible acceder a la sala de contención del virus."
FFKeyPickup=ROBOGUÍA: "Obtenida autorización para controles de seguridad."
Finished=
IntroMessage=Asteroide Ceres - Secreto del PTMC | Búnker de investigación C4
MagnetActivated=ROBOGUÍA: "Acelerador magnético descendente activado. Puertas de seguridad desbloqueadas."
MagnetTube1=ROBOGUÍA: "Bloqueo 1 de 2 de la sala de control desactivado."
MagnetTubeDoorUnlock=ROBOGUÍA: "Permitido el acceso a la sala de control. Puerta desbloqueada."
ManualActivation=ROBOGUÍA: "Este dispositivo se debe activar directamente."
NeedFFKey=ROBOGUÍA: "No estás autorizado para usar esos controles."
PathEnd=EndLevel
SecretArea=¡Has encontrado una zona secreta!
SteamRelease=ROBOGUÍA: "Activada la liberación de vapor." 
SuperHeaterShutdown=ROBOGUÍA: "Dispositivo calentador de contención del virus desactivado."
TurretsDeactivated=ROBOGUÍA: "Controles principales destruidos. Sistemas de defensa de superficie desactivados."
TurretsInvuln=ROBOGUÍA: "Las torretas grandes son demasiado resistentes para destruirlas. Busca otra forma de acabar con ellas."
UpperTubeActivate=ROBOGUÍA: "Tubo de acelerador ascendente activado."
Virus1Collected=¡Tienes un virus!
Virus2Collected=Buen trabajo. Has conseguido las dos muestras del virus.
VirusDescription=ROBOGUÍA: "Recoge las dos muestras del virus y sal tan deprisa como puedas."
