//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     45

// Message List
BLANK=
CenterLavaCrank=GUIDEBOT: "Center lava pump engaged."
DravisDoor=Dravis Stronghold door opened!
End=
EnergyCenterBroken=GUIDEBOT: "Energy Center not functional due to power shortage."
EnergyCentersOnline=GUIDEBOT: "All Energy Centers Online!"
FuseFound=Backup Reactor Fuse
HellionIntroduction=Hellion Assault Mech
InnerDoorsDenied=GUIDEBOT: "Access to Inner Stronghold Denied.  Passkey required."
InnerDoorsUnlock=GUIDEBOT: "You now have access to the Inner Stronghold."
InnerStrongholdKey=Inner Stronghold Key
IntroCameraText=Venus - Dravis' Stronghold
LeftLavaCrank=GUIDEBOT: "Left lava pump engaged."
MagicMatCenSwitches=GUIDEBOT: "Security MatCens in all 5 perimeter sectors have been turned off.  Access to Armory granted."
MatCenSwitchAOff=GUIDEBOT: "Security MatCens 1 and 5 power decreased."
MatCenSwitchAOn=GUIDEBOT: "Security MatCens 1 and 5 power increased."
MatCenSwitchBOff=GUIDEBOT: "Security MatCens 4 and 5 power decreased.  Security MatCen 3 turned on."
MatCenSwitchBOn=GUIDEBOT: "Security MatCens 4 and 5 power increased.  Security MatCen 3 turned off."
MatCenSwitchCOff=GUIDEBOT: "Security MatCen 3 power decreased.  Security MatCen 2 turned on."
MatCenSwitchCOn=GUIDEBOT: "Security MatCen 3 power increased.  Security MatCen 2 turned off."
MatCenSwitchDOff=GUIDEBOT: "Security MatCen 5 turned on."
MatCenSwitchDOn=GUIDEBOT: "Security MatCen 5 turned off."
MatCenSwitchEOff=GUIDEBOT: "Security MatCens 2 and 3 power decreased.  Security MatCen 1 turned on."
MatCenSwitchEOn=GUIDEBOT: "Security MatCens 2 and 3 power increased.  Security MatCen 1 turned off."
MatCenSwitchFOff=GUIDEBOT: "Security MatCens 2 and 4 power decreased."
MatCenSwitchFOn=GUIDEBOT: "Security MatCens 2 and 4 power increased."
MatCenSwitchGOff=GUIDEBOT: "Security MatCen 5 power decreased.  Security MatCen 4 turned on."
MatCenSwitchGOn=GUIDEBOT: "Security MatCen 5 power increased.  Security MatCen 4 turned off."
PowerRestored=GUIDEBOT: "Old Backup Reactor Fuse replaced.  Power to Energy Centers restored."
ReactorBroken=GUIDEBOT: "This Reactor needs a new Fuse.  The Reactor's current Fuse is broken."
RightLavaCrank=GUIDEBOT: "Right lava pump engaged."
TNTDispenserCenter=GUIDEBOT: "Producing medium-yield mining explosive device."
TNTDispenserLeft=GUIDEBOT: "Producing low-yield mining explosive device."
TNTDispenserLeftBroken=GUIDEBOT: "The mechanism is jammed beyond repair."
TNTDispenserRight=GUIDEBOT: "Producing high-yield mining explosive device."
TNTElevatorActivated=GUIDEBOT: "Elevator activated."
TNTRockWall=GUIDEBOT: "Your weapons won't budge these boulders."
TNTRockwalldestroyed=GUIDEBOT: "A cave entrance has been opened."
