//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     37

// Message List
AllDone=GUIDEBOT: "Objectives accomplished!  Escape from the factory to complete your mission!"
AllStabsDone=GUIDEBOT: "All 4 Stabilizers disrupted!"
Blank=
CovDamaged=CARGO SHIP: Help us please!  Taking serious damage!
CovDanger=CARGO SHIP: We're in danger!
CovDropOff=CARGO SHIP: Dropping off component for pickup!
CovEntering=CARGO SHIP: Entering the Spacecraft Factory
CovFFHelp=CARGO SHIP: We need your help to get past these forcefields in the storage area.  Hurry!
CovGettingPummeled=CARGO SHIP: We're getting pummeled by PTMC forces!  Please help!
CovInClear=CARGO SHIP: We're in the clear for now!
CovLeaveMeAlone=CARGO SHIP: Watch where you're aiming
CovLeaving=CARGO SHIP: Our job here is done!  Thanks for the help!
CovPickup=CARGO SHIP: Picking up a ship component
CovRepaired=CARGO SHIP: Repairs complete.  Resuming mission!
CovShutDown=CARGO SHIP: Too much damage! Shutting down for repairs!
CovStillStuckFF=CARGO SHIP: We're still unable to bypass this forcefield!  Please assist!
CovThanksFF=CARGO SHIP: Thanks for the help!
DestroyedAnt=GUIDEBOT: "Transmission antenna destroyed!"
DestroyedRadar=GUIDEBOT: "Surveillance radar destroyed!"
Disruptor=Seismic Disruptor
DoStabs=GUIDEBOT: "Disrupt the stabilizers to complete your mission!"
EndLevel=
IntroCam=Mercury - PTMC Spacecraft Factory
StabAssemblyDone=Assembly Plant Seismic Stabilizer| has been disrupted!
StabAssemblyPower=GUIDEBOT "Assembly Plant Stabilizer switching to Passive Mode!"
StabControlDone=Control Center Seismic Stabilizer| has been disrupted!
StabControlPower=GUIDEBOT: "Control Center Stabilizer switching to Passive Mode!"
StabFactoryDone=Main Factory Seismic Stabilizer| has been disrupted!
StabFactoryPower=GUIDEBOT: "Main Factory Stabilizer switching to Passive Mode!"
StabStoreDone=Storage Center Seismic Stabilizer| has been disrupted!
StabStorePower=GUIDEBOT: "Storage Center Stabilizer switching to Passive Mode!"
TempGoal=GUIDEBOT: "Disrupt the stabilizers to create a diversion while the covert cargo ship collects components!"
Testing=Distraction Level: %f
Testing2=Shield Level: %f
Transmitter=Receiving incoming encrypted transmission...
TransmitterHave=GUIDEBOT: "To receive a video transmission from the cargo ship, use your Covert Transmitter!"
