
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     13



// Message List

BlueDoor=Non hai la chiave azzurra!!

BlueKeyFF=Campo di forza della chiave azzurra disattivato!

EndLevel=

FlameDeactivated=Camera fiamme disattivata!

IntroCam=Centro ricerche armi ad alta velocità

NameBlueKey=Chiave azzurra

NameRedKey=Chiave rossa

ReactorDestroyed=Reattore principale distrutto! Sequenza autodistruzione attivata !

ReactorFF=Campo di forza reattore disattivato!

ReactorPrimed=ROBOT-GUIDA: "Il reattore ha disattivato le proprie difese!  Distruggilo!"

RedDoor=Non hai la chiave rossa!

RedKeyFF=Campo di forza chiave rossa disattivato!

