
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     27



// Message List

AccessDenied=GUIDEBOT: "Accès Refusé !  Passe nécessaire."

Blank=

BossData=SUJET:  Mech d'Assaut Avancé. STATUT:  Niveau R&D atteint.  Début de production à venir.  NOTES:  (secrètes) Production doublée comme demandé .  --SD

BothFireSwitches=GUIDEBOT: "Chambre de Combustion désactivée."

CEDData=SUJET:  Contrat de la Coopération de Défense Terrienne  STATUT:  Contrat Interceptor Phoenix rempli.  Missiles Requin Noir en cours de développement.  NOTES:  (secrètes)  Arrivage à la date prévue.  -SD

ClassifiedAccessPass=Passe d'accès réservé

ConsoleCrash=GUIDEBOT: "Le système semble avoir subi une erreur irrécupérable."

DravisData=SUJET:  Dravis, Samuel, Jr.  Directeur du Centre Spécial de Gestion de Crise et d'Information  STATUT: en visite de presse à la D.A.R.S.  NOTES:  (secrètes) La promotion demandée a été refusée.  -Suzuki

EmergencySwitch=GUIDEBOT: "Interrupteur Ouverture de Secours actuellement verrouillé."

EmergencySwitchOpen=GUIDEBOT: " Interrupteur Ouverture de Secours activé."

EndLevel=

FirstForcefield=Champ de force désactivé!

IntroMessage=Deimos - Centre d'Information de la PTMC

LeftConsoleSwitch=GUIDEBOT: "Recherche Base de Données des Plans de Production..."

LockDown=GUIDEBOT: "Le bâtiment a été armé d'un Verrouillage de Sécurité !"

MDData=SUJET:  Défenseur de la Matière ID No. 1032  STATUT: Disparu près de Tycho Brahé.  NOTES: (secrètes): Défaillance matérielle de l'intermix probable.  -SD

PrimaryLoginSwitch=GUIDEBOT: "Recherche Base de Données du Personnel..."

PTMCdisconnected=GUIDEBOT: "Vous avez été DECONNECTE..."

RightConsoleSwitch=GUIDEBOT: "Recherche Fichiers Administratifs..."

SECRETAREA=Vous avez trouvé une zone secrète !

SecurityAlert=GUIDEBOT: "Mon accès non autorisé à la base de données a été détecté ! Mesures de sécurité activées !"

ShipMessageLog=Données transférées dans le Journal de Messages du Vaisseau (SHIFT-F8)

SingleFireSwitch=GUIDEBOT: "Interrupteur Chambre de Combustion activé."

SRADLabData=NOTES: Un accident récent au Labo de la D.A.R.S. a causé la mort de dix-sept scientifiques. L'emploi du Dr. Sweitzer est résilié.  -SD

SweitzerData=SUJET:  Dr. Karl Sweitzer, Officier de Recherche en Chef du Labo de la D.A.R.S sur la planète Tiris.  STATUT: Résilié.  NOTES: emprisonné à la Novak Corporate sur Phobos.  -SD

