
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     39



// Message List

1Switch=ROBOT-GUIDA: "Per un percorso alternativo che aggiri i campi di forza primari, trova e attiva tutti i 9 interruttori che sbloccano la porta dell'ascensore!"

2Switch=ROBOT-GUIDA: "2 interruttori alternativi attivati!"

3Switch=ROBOT-GUIDA: "3 interruttori alternativi attivati!"

4Switch=ROBOT-GUIDA: "4 interruttori alternativi attivati!"

5Switch=ROBOT-GUIDA: "Rimangono ancora 4 interruttori alternativi!"

6Switch=ROBOT-GUIDA: "Rimangono solo 3 interruttori alternativi!"

7Switch=ROBOT-GUIDA: " Rimangono solo 2 interruttori alternativi per sbloccare la porta dell'ascensore!"

8Switch=ROBOT-GUIDA: "Rimane ancora 1 interruttore alternativo nella sequenza!"

9Switch=ROBOT-GUIDA: "Sequenza alternativa completata! La porta dell'ascensore abbandonato è sbloccata!"

All6Deactive=ROBOT-GUIDA: "Tutti e 6 gli instradatori d'energia disattivati!"

DestroyThese=Trova il modo di attivare i generatori d'emergenza prima di distruggerli e abbassare i campi di forza.

DoorUnlocked=Porta sbloccata!

DoThis=

ExitAbort=Nave catturata è bloccata tra le porte. Questo livello si autodistruggerà tra 5 secondi!

FirstCamera=Saranno piccoli, ma i loro amici |dispongono di una notevole potenza! Rimani fuori| dalla loro visuale se vuoi sopravvivere.

ForcefieldDisabled=Campo di forza disattivato!

ForcefieldFirst=ROBOT-GUIDA: "Energia del campo di forza primario disattivata. Attivare generatore d'emergenza!"

ForcefieldsDisabled=Campi di forza disattivati!

FreeAtLast=PILOTA: "Grazie di avermi salvato DM!  Filiamo via di qui... seguimi!"

GoalComplete=Ho raggiunto il risultato!

GotHim=Grazie per essere caduto nella| trappola, Difensore della Materia!

GoUpLeft=PILOTA: "Questi tubi d'uscita sono a chiusura sincronizzata. Tu va a sinistra mentre io vado a destra... Ci incontreremo in superficie!"

MainDestroyed=ROBOT-GUIDA: "Generatori dei campi di forza principali distrutti."

NextGoal=Fare pattuglia 3

PathCaptured=Catturato

PathIntroCam=IntroCam

PathIntroShip=IntroShip

PickupKey=ROBOT-GUIDA: "Accesso al fulcro secondario garantito! Tutte le porte del fulcro principale sbloccate!"

PipeDemo=I tubi sono vulnerabili solo quando| sono attivi. In caso contrario non| sprecare munizioni

Reroute=ROBOT-GUIDA: "Instradatore di energia disattivato!"

SecretArea=Hai trovato un'area segreta!

Spotted=ATTENZIONE: Allarme intruso! Attivare le difese della torretta!

Work=Titano - Centro magazzinaggio del PTMC

