//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     37

// Message List
ALLHeatSinksDestroyed=ROBOGUÍA: "Los tres disipadores de calor están destruidos.  La trampilla de acceso para mantenimiento de emergencia está desbloqueada."
CenterClampDisengaged=ROBOGUÍA: "Desanclando del muelle 2. Fragata médica Nightingale presente. ¡ADVERTENCIA! Fallo en el sistema. No es posible continuar."
ClampNotInUse=ROBOGUÍA: "Esta abrazadera de anclaje no está en uso."
CoolFanDestroyed=ROBOGUÍA: "Destruido el ventilador de entrada de refrigeración principal."
CoolFanInvulnerable=ROBOGUÍA: "Tus armas no tienen ningún efecto."
CoolingSystemClock=ROBOGUÍA: "Se ha activado el temporizador del regulador térmico. No es posible acceder hasta pasadas 32 horas."
CoolingSystemEngaged=ROBOGUÍA: "Se ha activado el regulador térmico:  Desactivando válvulas de vapor y abriendo huecos de disipación de calor."
CoreTempAboveNormal=ROBOGUÍA: "Sin el sistema de refrigeración intacto, la temperatura del núcleo de la refinería aumentará de forma indefinida."
CoreTempCritical=ROBOGUÍA: "Ahora que se ha destruido este ventilador principal de entrada, la temperatura del núcleo de la refinería aumentará paulatinamente hasta alcanzar niveles críticos."
DoorUnlocked=ROBOGUÍA: "Se ha desbloqueado la puerta cercana."
ElevatorAlreadyDown=ROBOGUÍA: "El ascensor del hangar ya está abajo."
ElevatorDOWN=ROBOGUÍA: "Ascensor del hangar descendiendo."
ElevatorNeedsDown=FRAGATA:  "No podremos salir de aquí con ese ascensor arriba. Ve inmediatamente al centro de control."
EndLevel=
EngagingCenterClamp=ROBOGUÍA: "Anclando en el muelle 2. Fragata médica Nightingale presente. ¡ADVERTENCIA! Fallo en el sistema. No es posible continuar."
FanReverseSwitch=ROBOGUÍA: "Invertido el ventilador de entrada de refrigeración."
ForcefieldDisabled=ROBOGUÍA: "Campo de fuerza desactivado."
FoundSecretData=RECUPERADO: Cartucho de datos dañado... (MAYÚS+F8)
FrigateSaved=FRAGATA:  "Gracias por abrir esa abrazadera.  No tenemos tiempo para charlar. Este sitio no parece muy estable."
HangarForcefieldDown=ROBOGUÍA: "Obtenida autorización de seguridad. Campo de fuerza del hangar desactivado. Tienes permiso para despegar."
HangarForcefieldUp=ROBOGUÍA: "Autorización de seguridad denegada. Se necesita un pase de autorización para desactivar manualmente el campo de fuerza."
HeatSinkDestroyed=ROBOGUÍA: "Destruido el disipador de calor del sistema de refrigeración."
IntroCamera=Europa - Refinería de combustible del PTMC Dol Ammad
Mayday=FRAGATA:  "Fragata médica Nightingale a control del hangar. Solicitamos permiso para desanclar del muelle. Repetimos: La abrazadera de anclaje 2 sigue bloqueada. Necesitamos ayuda para partir inmediatamente."
MessageFromFrigate=Transmisión de datos entrante de la fragata médica...  MAYÚS+F8
Passkey=Pase de seguridad del hangar
WeaponsPlantData=Este cartucho no está en muy buenas condiciones, pero tu Roboguía consigue recuperar varios datos que pueden ser útiles. Estos datos están relacionados con una planta de armamento del SRAD que no aparece en ninguno de los mapas de navegación normales del PTMC. Vale la pena comprobarlo más adelante.
