//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     52

// Message List
ActivatedMatcen=GUIDEBOT: "Materialization Center Activated!"
Arena1Defeated=GUIDEBOT: "Level 1 Arena defeated.  You are authorized to proceed to Level 2!"
Arena1Enter=Level 1 Arena| Prepare for battle!
Arena2Defeated=GUIDEBOT: "Level 2 Arena defeated.  You are authorized to proceed to Level 3!"
Arena2Enter=Level 2 Arena| Prepare for battle!
Arena3Defeated=GUIDEBOT: "Level 3 Arena defeated.  You are authorized to proceed to Level 4!"
Arena3Enter=Level 3 Arena| Prepare for battle!
Arena4Defeated=GUIDEBOT: "Level 4 Arena defeated.  You are authorized to proceed to Championship Arena!"
Arena4Defeated2=GUIDEBOT: "Access granted to all areas!"
Arena4Enter=Level 4 Arena| Prepare for combat!
Arena4Enter2=Level 4 Arena Part 2| A bonus awaits!
ArenaChamp=GUIDEBOT: "Proving Grounds champion defeated!  Access to the surface granted!"
CowFFDisable=GUIDEBOT: "Forcefield sequence completed!"
CowPipeActive=GUIDEBOT: "Control generator activated!"
DoorUnlocked=Door Unlocked!
EmergencyOverride=GUIDEBOT: "Emergency override activated.  All security forcefields disabled."
EndBossBegin=Championship Arena| Prepare for Battle!
EndLevel=
EscapedDestroyed=GUIDEBOT: "One more generator left to destroy!"
EscapedDestroyed2=GUIDEBOT: "You successfully escaped from the holding mechanism!"
EscapedTorture=GUIDEBOT: "Torture mechanism destroyed!"
EscapeTorture2=GUIDEBOT: "The forcefield generators should be vulnerable now!"
Forcefield=Forcefields deactivated!
GonnaClean=WARNING: Control generators destroyed!  Activating heat-cleansing system!
Guards1=One contender eliminated!
Guards2=Two contenders left to eliminate!
Guards3=One contender left to eliminate!
IntroMessage=Charon - PTMC Proving Grounds
L1Door=Level 1 Key Required!
L2Door=Level 2 Key Required!
L3Door=Level 3 Key Required!
L4Door=Level 4 Key Required!
Level1Key=Level 1 Key
Level2Key=Level 2 Key
Level3Key=Level 3 Key
Level4Key=Level 4 Key
LevelStarted=GUIDEBOT: "Get to the Proving Grounds as quickly as possible!  That's your only chance of escape!  Fight your way back to the surface!"
MainFFDeactivated=GUIDEBOT: "Main arena competitors eliminated.  The final competitor may now enter championship arena!"
MainGuards=GUIDEBOT: "You'll need to eliminate the contenders before you qualify for championship arena!"
RecoveredSecret=RECOVERED: Old data cartridge.  Guidebot scanning for information...
RedUnitsArmed=GUIDEBOT: "Control Units armed and ready for detonation!"
RepairActivated=GUIDEBOT: "Repair Facilities Reactivated!"
RepairDeactivated=GUIDEBOT: "Repair Facilities Deactivated!"
RepairingShip=Repairing your ship's shields| back to full strength!
SecretData=This cartridge is pretty worn and badly rusted, but your Guidebot manages to extract some data that may be useful.  It refers to some sort of Covert Industrial Complex that doesn't appear on any of your nav charts.  It may be worth checking out later.
SRepairInit=GUIDEBOT: "Repair unit calibration off.  Please reinitialize!"
