//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     14

// Message List
Area1=ROBOGUÍA: "Área 1"
Area2=ROBOGUÍA: "Área 2"
Area3=ROBOGUÍA: "Área 3"
EndLevelMessage=BEAGLE: Defensor... Estamos perdiendo tu señal. ¿Pasa algo raro ahí abajo?
EntranceDoorMessage=ROBOGUÍA: "Protocolo de pruebas activado."
IntroBriefingMessage=BEAGLE: No sé muy bien qué te vas a encontrar aquí. Explora la zona y presenta un informe en la base.
IntroHUDmessage=Recibiendo transmisión del Beagle... (MAYÚS+F8)
Nothing=
