//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     39

// Message List
1Switch=GUIDEBOT: "If you want an alternate path around the primary forcefields, locate and activate all 9 switches to unlock the elevator door!"
2Switch=GUIDEBOT: "2 alternate switches activated!"
3Switch=GUIDEBOT: "3 alternate switches activated!"
4Switch=GUIDEBOT: "4 alternate switches activated!"
5Switch=GUIDEBOT: "4 more alternate switches to go!"
6Switch=GUIDEBOT: "Only 3 more alternate switches to go!"
7Switch=GUIDEBOT: "Just 2 more alternate switches to unlock the elevator door!"
8Switch=GUIDEBOT: "1 more alternate switch left in the sequence!"
9Switch=GUIDEBOT: "Alternate sequence completed! Abandoned elevator door unlocked!"
All6Deactive=GUIDEBOT: "All 6 power routers disabled!  Backup forcefield generators enabled!"
DestroyThese=Find a way to turn on the backup| generators before you can| destroy them and lower the forcefields!
DoorUnlocked=Door Unlocked!
DoThis=
ExitAbort=Due to the captured ship getting caught on doors, this level will auto-end in 5 seconds!
FirstCamera=They may be small, but their friends| pack quite a wallop!  Stay out of their| field of view if you want to live.
ForcefieldDisabled=Forcefield disabled!
ForcefieldFirst=GUIDEBOT: "Primary forcefield power disabled.  Activating backup generator!"
ForcefieldsDisabled=Forcefields disabled!
FreeAtLast=PILOT: "Thanks for the rescue, MD!  Let's get out of here... follow me!"
GoalComplete=I finished a goal!
GotHim=Thanks for falling right into| our trap, Material Defender!
GoUpLeft=PILOT: "These exit tubes are synch-locked.  You head up the left side while I go up the right and we'll rendevous on the surface!"
MainDestroyed=GUIDEBOT: "Main forcefield generators destroyed."
NextGoal=Doing Patrol 3
PathCaptured=Captured
PathIntroCam=IntroCam
PathIntroShip=IntroShip
PickupKey=GUIDEBOT: "Access to secondary hub granted!  All primary hub doors unlocked!"
PipeDemo=When active, pipes are vulnerable| Otherwise don't waste your ammo
Reroute=GUIDEBOT: "Power router disabled!"
SecretArea=You Found A Secret Area!
Spotted=WARNING: Intruder Alert!  Turret defenses activated!
Work=Titan - PTMC Storage Facility
