//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     39

// Message List
1Switch=GUIDEBOT: "Falls Sie einen alternativen Weg benötigen, um die Primärkraftfelder zu umgehen, suchen und aktivieren Sie alle 9 Schalter, um die Fahrstuhltür zu entriegeln!"
2Switch=GUIDEBOT: "2 Wechselschalter aktiviert!"
3Switch=GUIDEBOT: "3 Wechselschalter aktiviert!"
4Switch=GUIDEBOT: "4 Wechselschalter aktiviert!"
5Switch=GUIDEBOT: "Noch 4 weitere Wechselschalter!"
6Switch=GUIDEBOT: "Nur noch 3 weitere Wechselschalter!"
7Switch=GUIDEBOT: "Nur noch 2 weitere Wechselschalter, um die Fahrstuhltür zu entriegeln!"
8Switch=GUIDEBOT: "1 weiterer Wechselschalter ist in der Folge noch übrig!"
9Switch=GUIDEBOT: "Wechselfolge komplett! Verlassene Fahrstuhltür entriegelt!"
All6Deactive=GUIDEBOT: "Alle 6 Energieleiter entschärft! Kraftfeld-Ersatzgeneratoren aktiviert!"
DestroyThese=Finden Sie einen Weg, um die Ersatzgeneratoren anzuschalten, bevor Sie sie zerstören können, um die Kraftfelder herunterzufahren!
DoorUnlocked=Tür geöffnet!
DoThis=
ExitAbort=Weil das Eroberungsschiff in den Türen gefangen ist, wird dieser Level automatisch in 5 Sekunden beendet!
FirstCamera=Sie mögen vielleicht klein sein, aber deren Freunde haben eine ziemliche Schlagkraft! Halte Dich aus deren Sichtfeld entfernt, wenn Du leben möchtest.
ForcefieldDisabled=Kraftfeld entschärft!
ForcefieldFirst=GUIDEBOT: "Hauptkraftfeldleistung entschärft.  Sicherheitsgeneratoren aktivieren!"
ForcefieldsDisabled=Kraftfelder entschärft!
FreeAtLast=PILOT: "Danke für die Rettung, MV! Lass uns von hier verschwinden... folge mir!"
GoalComplete=Ich habe ein Ziel erreicht!
GotHim=Danke, dass Sie uns direkt in die Falle gegangen sind, Materialverteidiger!
GoUpLeft=PILOT: "Diese Ausgangsröhren sind verschlossen.  Du fliegst links hoch und ich rechts, wir treffen uns dann an der Oberfläche!"
MainDestroyed=GUIDEBOT: "Hauptkraftfeldgeneratoren zerstört."
NextGoal= Patrouille 3 in Bearbeitung
PathCaptured=Gefangen
PathIntroCam=IntroCam
PathIntroShip=Introschiff
PickupKey=GUIDEBOT: "Zugang zum zweiten Bereich gewährt!  Alle Erstbereichstüren geöffnet!"
PipeDemo=Falls aktiviert, sind Rohre verletzbar.| Falls nicht, verschwende keine Munition.
Reroute=GUIDEBOT: "Kraftknoten entschärft!"
SecretArea=Du hast einen geheimen Bereich gefunden!
Spotted=WARNING: Eindringlings-Alarm!  Turmverteidigung aktiviert!
Work=Titan - PTMC-Lagerungseinrichtung

