//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     13

// Message List
BlueDoor=No tienes la llave azul.
BlueKeyFF=Campo de fuerza de llave azul desactivado.
EndLevel=
FlameDeactivated=Cámara de combustión desactivada.
IntroCam=Centro de investigación de armas de alta velocidad
NameBlueKey=Llave azul
NameRedKey=Llave roja
ReactorDestroyed=Reactor principal destruido. Secuencia de autodestrucción activada.
ReactorFF=Campo de fuerza del reactor desactivado.
ReactorPrimed=ROBOGUÍA: "El reactor ha desactivado sus defensas. Acaba con él."
RedDoor=No tienes la llave roja.
RedKeyFF=Campo de fuerza de llave roja desactivado.
