
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     11



// Message List

BPDefeated=GUIDEBOT: "Mercenaires de la PTMC battus !"

CartridgeError=GUIDEBOT: "Vous ne pouvez pas laisser la cartouche de données ici !"

CinematicAmbush=Mercenaires de la PTMC 

CinematicDataCart=Transfert de Données vers Suzuki en cours...

CinematicEndCam=

CinematicIntroCam=Terre - Séoul, Corée

Debug1=Réglage Difficulté : %f

Debug2=Ca devrait SECOUER!

GetOut=GUIDEBOT: "Transfert réussi !  Suzuki doit avoir les données !"

PutTheCartridge=GUIDEBOT: "Placez la cartouche de données au milieu de la salle de transfert !"

