
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     27



// Message List

AccessDenied=ROBOT-GUIDA: "Accesso negato! Richiesto Pass."

Blank=

BossData=SOGGETTO: Assalto avanzato meccanico. STATO: rispettate scadenze di R&S. La produzione inizierà tra breve.  NOTE:  (riservate) Cifre della produzione raddoppiate come richiesto..  -SD

BothFireSwitches=ROBOT-GUIDA: "Camera di combustione disattivata."

CEDData=SOGGETTO: Contratto del Collettivo di Difesa Terrestre STATO:  Onorato contratto Intercettore Phoenix. Missile Squalo-nero in sviluppo. NOTE:  (riservate) Nuova spedizione arriverà come da programma.  -SD

ClassifiedAccessPass=Pass per accesso riservato

ConsoleCrash=ROBOT-GUIDA: "Il sistema presenta un errore non recuperabile."

DravisData=SOGGETTO: Dravis, Samuel, Direttore Junior della Gestione Crisi & Relazioni Pubbliche. STATO: impegnato nella conferenza stampa dello SRAD.  NOTE: (riservate) La promozione richiesta è stata negata.  -Suzuki

EmergencySwitch=ROBOT-GUIDA: "Interruttore attivatore emergenza al momento bloccato."

EmergencySwitchOpen=ROBOT-GUIDA: "Interruttore attivatore emergenza attivato."

EndLevel=

FirstForcefield=Campo di forza disattivato!

IntroMessage=Deimos - Centro Archiviazione Dati PTMC 

LeftConsoleSwitch=ROBOT-GUIDA: "Sto esaminando il database della programmazione di produzione..."

LockDown=ROBOT-GUIDA: "Il centro ha completato l'attivazione delle misure di sicurezza!"

MDData=SOGGETTO: ID Difensore della Materia N. 1032  STATO:  MIA in prossimità di Tycho Brahe.  NOTE: (riservate)  Sospettata avaria hardware del nucleo warp.  -SD

PrimaryLoginSwitch=ROBOT-GUIDA: "Sto esaminando il database del personale..."

PTMCdisconnected=ROBOT-GUIDA: "Sei stato SCOLLEGATO..."

RightConsoleSwitch=ROBOT-GUIDA: "Sto esaminando l'archivio dell'amministrazione..."

SECRETAREA=Hai trovato un'area segreta!

SecurityAlert=ROBOT-GUIDA: "Hanno individuato il mio accesso non autorizzato al database! Sono state attivate misure di sicurezza!"

ShipMessageLog=Dati trasferiti a Registro Messaggi della nave (MAIUSC- F8)

SingleFireSwitch=ROBOT-GUIDA: "Interruttore della camera di combustione azionato."

SRADLabData=NOTE: Ultimo incidente nel laboratorio SRAD ha provocato la morte di 17 importanti scienziati. L'incarico del dottor Sweitzer è stato annullato.  -SD

SweitzerData=SOGGETTO:  Dottor Sweitzer, Karl,  Direttore Ricerche laboratorio SRAD sul pianeta Tiris.  STATO: Cessato.  NOTE: Sconta la pena nella prigione aziendale di Novak su Phobos.  -SD

