//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     45

// Message List
BLANK=
CenterLavaCrank=GUIDEBOT: "Pompe à lave centrale enclenchée fonctionnement."
DravisDoor=Porte de la Forteressee la Place Forte Dravis ouverte !
End=
EnergyCenterBroken=GUIDEBOT: "Le Centre d'Energie ne fonctionne pas à cause d'un manque e coupure d'alimentation ."
EnergyCentersOnline=GUIDEBOT: "Tous les Centres d'Energie Connectés !"
FuseFound=Fusible Réacteur de Secoursoutien
HellionIntroduction=Mech d'Assaut Hellion
InnerDoorsDenied=GUIDEBOT: "Accès à laà la  Forteresseeresse Intérieuree refusé.  Passe nécessaire."
InnerDoorsUnlock=GUIDEBOT: "Vous avez maintenant accès à la Forteresse Intérieure."
InnerStrongholdKey=Clé Forteresse Intérieure
IntroCameraText=Vénus - Place ForteForteresse de Dravis
LeftLavaCrank=GUIDEBOT: "Pompe à lave gauche en fonctionnemenclenchéet."
MagicMatCenSwitches=GUIDEBOT: "Les CentMats robogènes dans les 5 cinq secteurs du périmétriquepérimètres ont été éteints. Accès à l'Armurerie l'armurerie autorisé."
MatCenSwitchAOff=GUIDEBOT: "Puissance des CentMats robogènes 1 et 5 réduite."
MatCenSwitchAOn=GUIDEBOT: "Puissance des robogènes CentMats 1 et 5 augmentée."
MatCenSwitchBOff=GUIDEBOT: "Puissance des robogènes CentMats 4 et 5 réduite. Robogène CentMat 3 de Sécurité activé."
MatCenSwitchBOn=GUIDEBOT: "Puissance des robogènes CentMats 4 et 5 augmentée. RCentMat obogène 3 de sSécurité désactivé."
MatCenSwitchCOff=GUIDEBOT: "Puissance du robogène CentMat 3 réduite. Robogène CentMat 2 de Sécurité activé."
MatCenSwitchCOn=GUIDEBOT: "Puissance du robogène CentMat 3 augmentée. Robogène CentMat 2 de Sécurité désactivé."
MatCenSwitchDOff=GUIDEBOT: "Robogène CentMat 5 de Sécurité activé."
MatCenSwitchDOn=GUIDEBOT: "Robogène CentMat 5 de Sécurité désactivé."
MatCenSwitchEOff=GUIDEBOT: "Puissance des robogènes CentMats 2 et 3 réduite. CentMat Robogène 1 de Sécurité sécurité activé."
MatCenSwitchEOn=GUIDEBOT: "Puissance des robogènes CentMats 2 et 3 augmentée. Robogène CentMat 1 de Sécurité désactivé."
MatCenSwitchFOff=GUIDEBOT: "Puissance des robogènes CentMats 2 et 4 réduite."
MatCenSwitchFOn=GUIDEBOT: "Puissance des robogènes CentMats 2 et 4 augmentée."
MatCenSwitchGOff=GUIDEBOT: "Puissance du robogène CentMat 5 réduite. robogène CentMat 4 de Sécurité activé."
MatCenSwitchGOn=GUIDEBOT: " Puissance du robogène CentMat 5 augmentée. robogène CentMat 4 de Sécurité désactivé."
PowerRestored=GUIDEBOT: "le vVieux Ffusible du rRéacteur de Soutien secours a été remplacé. Les cCentres d'Energie d'énergie sontalimentés à nouveau opérationnels."
ReactorBroken=GUIDEBOT: "Ce rRéacteur a besoin d'un nouveau fFusible. Le fFusible actuel du rRéacteur a fondu."
RightLavaCrank=GUIDEBOT: "Pompe à lave droite enclenchée fonctionnement."
TNTDispenserCenter=GUIDEBOT: "Production d'un dispositif explosif de sape à rendement moyen."
TNTDispenserLeft=GUIDEBOT: "Production d'un dispositif explosif de sape à rendement faible."
TNTDispenserLeftBroken=GUIDEBOT: "Le méchanismemécanisme est irréparable, tellement il est coinçécoincé."
TNTDispenserRight=GUIDEBOT: " Production d'un dispositif explosif de sape à rendement élevé."
TNTElevatorActivated=GUIDEBOT: "Ascenseur activé."
TNTRockWall=GUIDEBOT: "Vos armes ne feront pas bougeront pasont pas ces rochers d'un pouce !."
TNTRockwalldestroyed=GUIDEBOT: "Un passage a été ouvert."

