//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     73

// Message List
BaseAlertDisplay=Alert Level: %d
BaseAlertStatus=GUIDEBOT: "The Command Center is now on a Level %d Alert."
CannonHitPlayer=GUIDEBOT: "The surface cannon has fired!"
CrashedShipGame=Recon Pilot T. Murphy S.O.S!  My ship is burning.  All systems failing. Going down.  Repeat,...Going down.  The base is highly guarded.  Watch for guards alerting towers...should have used stealth to not be noticed!  Now it's too late.
CrashedShipHud=You found a Pilot's Logbook  (SHIFT-F8)
D1GuardSpotted=GUIDEBOT: "The mine guard spotted you!"
DataUplinkActivated=GUIDEBOT: "Uplink Docking Control activated."
Empty=
GuardTowerAlertedGG=GUIDEBOT: "The mine guard has alerted the tower!"
GuardTowerAlertedHG=GUIDEBOT: "The hangar guard has alerted the tower!"
HangerCamSawPlayer=GUIDEBOT: "The hangar security camera spotted you!"
HangerDoorUnlocked=GUIDEBOT: "The Hangar door has been unlocked."
HangerGuardSpotted=GUIDEBOT: "The hangar guard spotted you!"
HangerMsgGame=LOG: Yesterday the hangar security camera malfunctioned and misidentified a data delivery ship.  Turret defenses were activated and the ship was damaged beyond repair.  All remains of the ship have been dumped in the old mine according to protocol.
HangerMsgHUD=Hangar Security Log downloaded... (SHIFT-F8)
InitInterfaceCin=GUIDEBOT: "Initializing Data Interface..."
InterfaceAcquired=GUIDEBOT: "You have obtained a Data Interface, model P103Z."
InterfaceHasNoPower=GUIDEBOT: "The Data Uplink Control panel is currently without power."
InterfaceInitialized=GUIDEBOT: "Your ship's Data Interface has been initialized successfully."
InterfacePowerOff=GUIDEBOT: "The Uplink Control panel's power is now off."
InterfacePowerOn=GUIDEBOT: "The Uplink Control panel's power supply is now on."
InterfacePrepDenied=GUIDEBOT: "Error: Data Interface is incompatible or not present."
InterfacePrepInstHUD=Interface Prep instructions downloaded... (SHIFT-F8)
InterfacePrepInstrGame=INSTRUCTIONS: Welcome to the Data Interface Prep Room, Pilot.  Before uploading any information at the Data Uplink Center, your ship's Data Interface must be initialized.  To prep your ship, enter the Initialization Hub in the center of the room.
IntroText=The Moon - CED Lunar Command Center
JuggAlertedBase=GUIDEBOT: "The Juggernaut has alerted the Comm base!"
JuggAlertWarning=GUIDEBOT: "The Juggernaut is headed for the Comm base... stop it before it gets there!"
JuggSawPlayer=GUIDEBOT: "The Juggernaut spotted you!"
MatcenActivated=GUIDEBOT: "This Matcen is now active."
MatcenDeactivated=GUIDEBOT: "This Matcen has been deactivated."
MemPlasmaGame=INFO: Certain Data Interfaces may require a Memory Plasma Charge in order to connect successfully to the Main Uplink Center.  The device below will continually generate charges for this purpose (unless its generation has been disabled).
MemPlasmaHUD=Memory Plasma Charge Info received... (SHIFT-F8)
MemPlasmaLost=GUIDEBOT: "Your Memory Plasma charge has expired!"
MemPlasmaObtained=GUIDEBOT: "Memory Plasma charge obtained (lasts %d seconds)"
MemPlasmaOff=GUIDEBOT: "Memory Plasma generation has been deactivated."
MemPlasmaOn=GUIDEBOT: "Memory Plasma generation has been enabled."
NanoPlasmaDefOff=GUIDEBOT: "The Uplink's Nano Plasma defenses have been deactivated."
NanoPlasmaDefOn=GUIDEBOT: "The Uplink's Nano Plasma defenses are now active."
NoEntry=No entry beyond this point!
Secret1=You have found a secret area!
UplinkCenterGame=INFO: Welcome to the Data Uplink Center.  Once Uplink Control has authorized your upload, you may dock with the Data Uplink by positioning your ship directly between the plasma nodes.  If everything checks out, the transfer will begin automatically.
UplinkCenterHUD=Pilot Uplink Instructions received... (SHIFT-F8)
UplinkControlGame=DIRECTIVES: Uplink Control Operators are required to run all ships through a security check before granting upload authorization.  Once a ship has been deemed acceptable, Uplink Docking Control may be activated at the rear panel.
UplinkControlHUD=Uplink Control Directives received... (SHIFT-F8)
UplinkDocking=GUIDEBOT: "Connecting to Data Uplink..."
UplinkErrorNano=GUIDEBOT: "Error: Nano Plasma defenses are active.  Upload aborted."
UplinkErrorNoChg=GUIDEBOT: "Error: Insufficient memory plasma charge found on source ship."
UplinkErrorNoInit=GUIDEBOT: "Error: Source ship's Data Interface has not been initialized."
UplinkErrorNoInt=GUIDEBOT: "Error: The source ship is not fitted with a compatible Data Interface."
UplinkErrorNoPlasma=GUIDEBOT: "Error: Main Data Uplink plasma supply is not active."
UplinkErrorNotAct=GUIDEBOT: "Error: Uplink Docking Control has not been activated."
UplinkPlasmaOff=GUIDEBOT: "The Data Uplink Plasma Supply is now off."
UplinkPlasmaOn=GUIDEBOT: "The Data Uplink Plasma Supply is now on."
UploadingVirus=
VaultKeyAcquired=Data Vault Entry Key
ZCamMonitorOff=Security Camera Monitor Off
ZCamMonitorOn=Security Camera Monitor On
ZCamSpotted=GUIDEBOT: "Local Turret Defenses have been activated!"
ZCanyonAmbush=GUIDEBOT: "I don't like the looks of this..."
ZCanyonRun=GUIDEBOT: "The Canyon Guard's running away!  Get him!"
ZCBAlerted=GUIDEBOT: "The Command Base has been alerted!"
ZCBNoticed=GUIDEBOT: "The Command Base Guard noticed you!"
ZDVAlerted=GUIDEBOT: "The Data Vault has been alerted!"
ZDVSpotted=GUIDEBOT: "The Data Vault Guard has spotted you!"
ZGotCamMonitor=GUIDEBOT: "You found a Security Camera Monitor!"
ZMegaTrap=GUIDEBOT: "That Mega was wired... Look out!"
ZTurretHit=GUIDEBOT: "Local Turret Defenses have been activated!"
