
///////////////////////////////
///////////////

// D.A.L.L.A.S. Generated 
Message Table File

///////////////////////////////
///////////////



NEXT_MESSAGE_ID_NUMBER     45



// Message List

BLANK=

CenterLavaCrank=ROBOT-GUIDA: 
"Pompa centrale della lava in 
funzione.”

DravisDoor=Porta della fortezza 
di Dravis aperta!

End=

EnergyCenterBroken=ROBOT-GUIDA: 
"Centrale d’energia non 
operativa per mancanza di 
energia."

EnergyCentersOnline=ROBOT-
GUIDA: "Tutte le Centrali 
d’energia in funzione!"

FuseFound=Fusibile del reattore 
ausiliario

HellionIntroduction=Meccanoide 
d’assalto Hellion

InnerDoorsDenied=ROBOT-GUIDA: 
"Accesso alla fortezza interna 
negato. Necessario pass."

InnerDoorsUnlock=ROBOT-GUIDA: 
"Ora è possibile accedere alla 
fortezza interna."

InnerStrongholdKey=Chiave della 
fortezza interna

IntroCameraText=Venere. 
Fortezza di Dravis

LeftLavaCrank=ROBOT-GUIDA: 
"Pompa sinistra  della lava in 
funzione."

MagicMatCenSwitches=ROBOT-
GUIDA: "I MatCen di sicurezza 
sono stati disattivati in tutti 
i 5 settori del perimetro. 
Accesso all’Armeria 
autorizzato."

MatCenSwitchAOff=ROBOT-GUIDA: 
"Diminuita potenza dei MatCen 
di sicurezza 1 e 5."

MatCenSwitchAOn=ROBOT-GUIDA: 
"Aumentata potenza dei MatCen 
di sicurezza 1 e 5."

MatCenSwitchBOff=ROBOT-GUIDA: 
"Diminuita potenza dei MatCen 
di sicurezza 4 e 5. Attivato 
MatCen di sicurezza 3."

MatCenSwitchBOn=ROBOT-GUIDA: 
"Aumentata potenza dei MatCen 
di sicurezza 4 e 5. Disattivato 
MatCen di sicurezza 3."

MatCenSwitchCOff=ROBOT-GUIDA: 
"Diminuita potenza del MatCen 
di sicurezza 3. Attivato MatCen 
di sicurezza 2."

MatCenSwitchCOn=ROBOT-GUIDA: 
"Aumentata potenza del MatCen 
di sicurezza 3. Disattivato 
MatCen di sicurezza 2."

MatCenSwitchDOff=ROBOT-GUIDA: 
"Attivato MatCen di sicurezza 
5."

MatCenSwitchDOn=ROBOT-GUIDA: 
"Disattivato MatCen di 
sicurezza 5."

MatCenSwitchEOff=ROBOT-GUIDA: 
"Diminuita potenza dei MatCen 
di sicurezza 2 e 3. Attivato 
MatCen di sicurezza 1."

MatCenSwitchEOn=ROBOT-GUIDA: 
"Aumentata potenza dei MatCen 
di sicurezza 2 e 3. Disattivato 
MatCen di sicurezza 1."

MatCenSwitchFOff=ROBOT-GUIDA: 
"Diminuita potenza dei MatCen 
di sicurezza 2 e 4."

MatCenSwitchFOn=ROBOT-GUIDA: 
"Aumentata potenza dei MatCen 
di sicurezza 2 e 4."

MatCenSwitchGOff=ROBOT-GUIDA: 
"Diminuita potenza del MatCen 
di sicurezza 5. Attivato MatCen 
di sicurezza 4."

MatCenSwitchGOn=ROBOT-GUIDA: 
"Aumentata potenza dei MatCen 
di sicurezza 5. Disattivato 
MatCen di sicurezza 4."

PowerRestored=ROBOT-GUIDA: 
"Sostituito vecchio fusibile 
del reattore ausiliario.  
Ripristinata energia nei Centri 
d’energia."

ReactorBroken=ROBOT-GUIDA: 
"Questo reattore ha bisogno di 
un nuovo fusibile. L’attuale 
fusibile del reattore è 
saltato."

RightLavaCrank=ROBOT-GUIDA: 
"Pompa destra della lava in 
funzione."

TNTDispenserCenter=ROBOT-GUIDA: 
"Produzione di un dispositivo 
esplosivo minerario di media 
potenza."

TNTDispenserLeft=ROBOT-GUIDA: 
"Produzione di un dispositivo 
esplosivo minerario di bassa 
potenza."

TNTDispenserLeftBroken=ROBOT-
GUIDA: "Il meccanismo si è 
bloccato e non è riparabile."

TNTDispenserRight=ROBOT-GUIDA: 
"Produzione di un dispositivo 
esplosivo minerario di alta 
potenza."

TNTElevatorActivated=ROBOT-
GUIDA: "Ascensore attivato."

TNTRockWall=ROBOT-GUIDA: "Le 
tue armi non sono in grado di 
spostare questi massi."

TNTRockwalldestroyed=ROBOT-
GUIDA: "È stato aperto un 
varco."

