//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     27

// Message List
AccessDenied=ROBOGUÍA: "¡Acceso denegado! Es necesario un pase."
Blank=
BossData=ASUNTO: Mecanismo de asalto avanzado. ESTADO: Plazos I+D cumplidos. La producción se enviará en breve. NOTAS: (secreto) Cantidades producidas dobladas según la petición.  --SD
BothFireSwitches=ROBOGUÍA: "Cámara de combustión desactivada."
CEDData=ASUNTO: Contrato de la Defensa Colectiva Terrestre. ESTADO: Contrato de Interceptor Fénix cumplido. Misil Tiburón Negro en desarrollo.  NOTAS: (secreto)  El nuevo cargamento llegará dentro del plazo.  --SD
ClassifiedAccessPass=Pase de acceso restringido
ConsoleCrash=GUIDEBOT: "Parece que el sistema tiene un error no recuperable."
DravisData=ASUNTO:  Dravis, Samuel, Jr.  Director de gestión de crisis y relaciones públicas  ESTADO: de viaje en la gira de ruedas de prensa del SRAD. NOTAS: (secreto) Se ha denegado el ascenso solicitado.  -Suzuki
EmergencySwitch=ROBOGUÍA: "Conmutador de liberación de emergencia bloqueado."
EmergencySwitchOpen=ROBOGUÍA: "Conmutador de liberación de emergencia activado."
EndLevel=
FirstForcefield=Campo de fuerza desactivado.
IntroMessage=Deimos: Centro de retención de datos del PTMC
LeftConsoleSwitch=ROBOGUÍA: "Buscando base de datos de plazos de producción..."
LockDown=GUIDEBOT: "La instalación ha completado el bloqueo de seguridad."
MDData=ASUNTO:  Defensor. ID Nº 1032  ESTADO: Desaparecido en combate en las proximidades de Tycho Brahe.  NOTAS: (secreto) Probablemente un fallo de hardware del núcleo de propulsión.  --SD
PrimaryLoginSwitch=ROBOGUÍA: "Buscando base de datos de personal..."
PTMCdisconnected=ROBOGUÍA: "Has sido DESCONECTADO..."
RightConsoleSwitch=ROBOGUÍA: "Buscando archivos administrativos..."
SECRETAREA=¡Has encontrado una zona secreta!
SecurityAlert=ROBOGUÍA: "Se ha detectado mi acceso no autorizado a la base de datos. ¡Se han activado las medidas de seguridad!"
ShipMessageLog=Datos transferidos al registro de mensajes de la nave(MAYÚS+F8)
SingleFireSwitch=ROBOGUÍA: "Activado el conmutador de la cámara de combustión."
SRADLabData=NOTAS: Responsable del accidente del laboratorio del SRAD, causante de la muerte de 17 científicos. El Dr. Sweitzer fue despedido.  --SD
SweitzerData=ASUNTO:  Dr. Sweitzer, Karl  Investigador jefe del laboratorio del SRAD del planeta Tiris.  ESTADO:  CESADO.  NOTAS:  Cumple condena en la prisión corporativa de Novak, en Phobos.  --SD
