
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     48



// Message List

1stInvalidPassOffense=PUNTO DI CONTROLLO: "Impossibile concedere autorizzazione di sicurezza. Si prega di attendere assistenza."

2ndInvalidPassOffense=PUNTO DI CONTROLLO: "Autorizzazione di sicurezza negata! Forze di sicurezza in allerta!"

AnotherTurretGone=ROBOT-GUIDA: "Distrutta torretta di difesa del perimetro."

ChemicalReactionAlert=ROBOT-GUIDA: "PERICOLO!  Contaminazione vasca acidi! Allarme rischio biologico livello 4! Evacuare livello massima sicurezza!"

ChemicalReactionSwitches=ROBOT-GUIDA: "È stato attuato blocco di sicurezza chimica."

ComputerDestroyed=ROBOT-GUIDA: "Il supercomputer con la documentazione della prigione Novak è stato distrutto!"



DontShootMe=NAVETTA: "Andateci piano coi miei scudi!"
Empty=
EndLevel=

EscortShuttle=NAVETTA: "In questo momento mi servirebbe proprio una scorta."

ForcefieldDown=NAVETTA: "Il campo di forza è disattivato: vi copro le spalle mentre andate a prendere il dottor Sweitzer."

ForcefieldDownEarly=ROBOT-GUIDA: "Il campo di forza dell'hangar trasferimento prigionieri è stato disattivato."

G1MinSecurityPassB=Pass di Sicurezza G-1

IncomingMessage=Trasmissione in arrivo da navetta...  
(MAIUSC-F8)

InnerTowerForcefields=ROBOT-GUIDA: "Campi di forza disattivati."

IntroMessage=Phobos - Prigione aziendale Novak

LoadedSweitzer=NAVETTA:  "Sweitzer è a bordo. Possiamo squagliarcela. Coprimi!"

LoadingSweitzer=NAVETTA:  "Portiamo il dottore a bordo."

MaximumSecurityClearance=PUNTO DI CONTROLLO: "Concessa autorizzazione massimo livello di sicurezza."

MediumSecurityClearance=PUNTO DI CONTROLLO: "Concessa autorizzazione medio livello di sicurezza. "

MinimumSecurityClearance=PUNTO DI CONTROLLO: "Concessa autorizzazione minimo livello di sicurezza."

OneTurretDown=NAVETTA: "Bene, una torretta del perimetro è caduta. Ne mancano quattro. Rimarremo nascosti in un canalone fin quando la zona non sarà sicura. Buona fortuna."

R1MaxSecurityPassC=Pass di sicurezza R-1 

RecordsNodeDestroyed=ROBOT-GUIDA: "Distrutto il nodo ausiliario della documentazione della prigione Novak!"

SECRETAREA=Hai trovato un'area segreta!

SecurityPassNotUsableHere=ROBOT-GUIDA: "Questo pass di sicurezza non è utilizzabile."

SecurityPassReturned=ROBOT-GUIDA: "Il pass di sicurezza è stato restituito all'erogatore."

ShuttleMoveToTower=NAVETTA: "Le difese perimetrali sembrano abbassate e i campi di forza dell'hangar rifornimenti sono deboli. Mi dirigo verso la torre principale in attesa del segnale che Sweitzer è stato individuato. Sembra che l'hangar sia l'unico punto possibile per entrare."

ShuttleUnderAttack=NAVETTA: "Ah, qui c'è un problema, serve un fuoco di copertura! Ho le forze di sicurezza addosso!"

SPUDhasTheBall=MECCANOIDE MPS: "Trasporto di capsula chimica."

SPUDisBorn=ROBOT-GUIDA: "Chiamata di meccanoide per produzioni speciali. Devo produrre una capsula per la lavorazione chimica."

SPUDkilled=ROBOT-GUIDA: "Distruggo il meccanoide per produzioni speciali."

SPUDscores=ROBOT-GUIDA: "Il meccanoide per produzioni speciali ha lasciato la zona."

SupplyAlarm=ROBOT-GUIDA: "Uno dei robot ha azionato un allarme locale!"

SupplyAlarmPlayer=ROBOT-GUIDA: "Disattivare limitazioni a personale non autorizzato."

SweitzerMAX=NAVETTA:  "Splendido, hai trovato il dottor Sweitzer. Ma con questa vecchia bagnarola non si può penetrare nella zona di massima sicurezza. Devi trovare il modo di trasferire il dottore in un luogo più adatto... preferibilmente di minima sicurezza.."



SweitzerMINLockedOut=NAVETTA:  "Bel lavoro. Mi spiace insistere, ma qui c'è un altro problema. C'è un campo di forza in cima alla torre e posso entrare solo se sarà disattivato. Mi spiace."

WhatTheHell=NAVETTA: "Ehi, tutto bene laggiù?! Non so che cosa hai fatto, ma sembra che la prigione sia in allarme rosso. A giudicare dal traffico radio è in atto un'evacuazione di emergenza."

X1OldSecurityPassD=Pass di Sicurezza X-1

Y1MedSecurityPassA=Pass di Sicurezza Y-1

