//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     33

// Message List
All4Radio=GUIDEBOT: "Übertragung über Datlink-Kommunikator aktiviert!"
All4Radio2=GUIDEBOT: "Sie müssten jetzt Zugang zur Waffenkammer haben!"
DataFinal=GUIDEBOT: "Die Kassette enthält jetzt die Daten, die wir brauchen! Kehren Sie an die Oberfläche zurück, um Ihre Mission zu beenden!"
DataNodes=GUIDEBOT: "Plazieren Sie die Datenkassette zwischen den Upload-Knoten!"
DataOriginal=GUIDEBOT: "Die Kassette ist leer!  Suchen Sie die Upload-Knoten, und plazieren Sie die Kassette dazwischen!"
DestroyedSuper=GUIDEBOT: "SuperDieb zerstört!  Die Kassette sollte jetzt die Daten enthalten!"
DestroyedThief=GUIDEBOT: "SuperDieb zerstört!  Holen Sie die Datenkassette!"
EndLevel=Schweitzers Forschungsdaten erhalten
FalseTransfer=GUIDEBOT: "Es ist keine Kassette vorhanden, auf die die Daten übertragen werden könnten!"
ForceFieldDeactivated=Kraftfeld deaktiviert!
IntroMessage=Tiris - PTMC Piccu-Station| & SAFA Beta Ceti Labor
KillSuper=GUIDEBOT: "Zerstören Sie den SuperDieb, um die Datenkassette zurückzubekommen!"
LTSelfDestruct=GUIDEBOT: "Der Blitzturm kann sich nicht länger entladen und zerstört sich selbst!"
MainKeyCard=Sicherheitsschlüssel
PlaceCartridge=GUIDEBOT: "Die Datenkassette ist zum Laden der Daten bereit!  Finden Sie die Aktivierungssteuerung!"
RadioRoomFirst=GUIDEBOT: "Primäre Energiekoppelung eingeschaltet!"
RadioRoomUnlock=GUIDEBOT: "Hilfsenergie zum Datlink-System umgeleitet."
SecretArea=Sie haben einen geheimen Bereich gefunden!
SecurityDoor=Zugang verweigert!
SuperIntro=SuperDieb
TempGetData=GUIDEBOT: "Die Datenkassette ist irgendwo in diesem Labor!"
ThiefGotIt=GUIDEBOT: "Der SuperDieb hat die Datenkassette gestohlen!  Eliminieren Sie ihn, um sie zurückzubekommen!"
Uploading=GUIDEBOT: "Virusdaten auf Kassette laden!"
UploadNode=GUIDEBOT: "Diese Ladeknoten übertragen Daten auf alle Geräte, die zwischen ihnen plaziert werden."

