//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     37

// Message List
AllDone=ROBOGUÍA: "Todos los objetivos cumplidos. Escapa de la fábrica para completar tu misión."
AllStabsDone=ROBOGUÍA: "Se han averiado los cuatro estabilizadores."
Blank=
CovDamaged=NAVE DE TRANSPORTE: ¡Ayudadnos! Hemos sufrido fuertes daños.
CovDanger=NAVE DE TRANSPORTE: ¡Estamos en peligro!
CovDropOff=NAVE DE TRANSPORTE: Soltando componentes para la recogida.
CovEntering=NAVE DE TRANSPORTE: Entrando en la fábrica de naves espaciales
CovFFHelp=NAVE DE TRANSPORTE: Necesitamos tu ayuda para atravesar los campos de fuerza de la zona de almacenamiento. ¡Date prisa!
CovGettingPummeled=NAVE DE TRANSPORTE: Las fuerzas del PTMC nos están dando una paliza. ¡Ayudadnos!
CovInClear=NAVE DE TRANSPORTE: Por el momento estamos a descubierto.
CovLeaveMeAlone=NAVE DE TRANSPORTE: Ten cuidado al apuntar.
CovLeaving=NAVE DE TRANSPORTE: Ya hemos terminado nuestro trabajo. Gracias por la ayuda.
CovPickup=NAVE DE TRANSPORTE: Recogiendo componente de nave
CovRepaired=NAVE DE TRANSPORTE: Reparaciones completas. Reanudando la misión.
CovShutDown=NAVE DE TRANSPORTE: Hemos sufrido demasiados daños. Tenemos que efectuar reparaciones.
CovStillStuckFF=NAVE DE TRANSPORTE: Aún no podemos sortear ese campo de fuerza. ¡Ayudadnos!
CovThanksFF=NAVE DE TRANSPORTE: Gracias por la ayuda.
DestroyedAnt=ROBOGUÍA: "Antena de transmisión destruida."
DestroyedRadar=ROBOGUÍA: "Radar de vigilancia destruido."
Disruptor=Disruptor sísmico
DoStabs=ROBOGUÍA: "Avería los estabilizadores para completar tu misión."
EndLevel=
IntroCam=Mercurio - Fábrica de naves espaciales del PTMC
StabAssemblyDone=El estabilizador sísmico de la planta de montaje| ha sido averiado.
StabAssemblyPower=ROBOGUÍA:"El estabilizador sísmico de la planta de montaje está cambiando al modo pasivo."
StabControlDone=El estabilizador sísmico del centro de control| ha sido averiado.
StabControlPower=ROBOGUÍA: "El estabilizador sísmico del centro de control está cambiando al modo pasivo."
StabFactoryDone=El estabilizador sísmico de la fábrica principal| ha sido averiado.
StabFactoryPower=ROBOGUÍA: "El estabilizador sísmico de la fábrica principal está cambiando al modo pasivo."
StabStoreDone=El estabilizador sísmico del centro de almacenamiento| ha sido averiado.
StabStorePower=ROBOGUÍA: "El estabilizador sísmico del centro de almacenamiento está cambiando al modo pasivo."
TempGoal=ROBOGUÍA: "Avería los estabilizadores para crear una distracción mientras la nave de transporte encubierta recoge componentes."
Testing=Nivel de distracción: %f
Testing2=Nivel de escudo: %f
Transmitter=Recibiendo transmisión encriptada...
TransmitterHave=ROBOGUÍA: "Utiliza el transmisor secreto para recibir una transmisión de la nave de transporte."
