//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     51

// Message List
AftMatcenCheck=GUIDEBOT: "Untersuche hinteren Matcen-Auslöser."
AftSwCinema=Heck Matcen entschärfen
AuxCoreDoor=GUIDEBOT: "Zugang zum Hilfsmaschinenkern verweigert.  Finden Sie einen anderen Weg!"
Bay62Door=GUIDEBOT: "Die Zugangstür zu Rampe 62 wurde blockiert.  Finden Sie einen anderen Weg!"
Bay62Fuse=GUIDEBOT: "Rampe 62 Matcen entschärft."
Bay62Game=11:37.04.04.3750 VORFALLPROTOKOLL  ID-MARKE KAMPFGESCHWADER 62 KOMMANDANT M. KELLY: "Wir waren hier nicht erfolgreich. Wir wissen nun, dass sie die Kontrolle über mindestens zwei StarHawk-Jäger haben! Die Infektion hat sich bis auf die Arbeiterdrohnen ausgebreitet. Ich evakuiere meine Leute."
Bay62Hud=Rampe 62 Vorfallsprotokoll heruntergeladen... (SHIFT - F8)
Bay62Lance=GUIDEBOT: "Gefechtstürme entschärft."
BayInfoGame=07:02.04.04.3750: PTMC-DeepSpace-Lieferung 432178: "Matcen Teilebestellung an Bord eingeloggt."
BayInfoHud= Rampe 36 Vorfallsprotokoll heruntergeladen... (SHIFT - F8)
Cleanup=KEV-KOMMANDANT: "Alle übrigen StormTrooper ausmerzen."
CoreAccFF=GUIDEBOT: "Zugang zum Kern abgeschirmt. Finden Sie einen anderen Weg."
CoreInfo1=11:11:04.04.3750 Vorfallprotokoll heruntergeladen... (SHIFT - F8)
CoreInfo2=11:11.04.04.3750  INVASIONS-ALARM! "Maschinenkern-Zugangstür Nr. 79.287 durch Benutzer ID-MARKE NR. 80-84 funktionsunfähig gemacht."
CoreRads=GUIDEBOT: "Störung der kritischen Masse!"
DangerEngine=GUIDEBOT: "WARNUNG  -- Maschinenspannungsgebiet!"
EndCine=
EndMission=KEV-KOMMANDANT: "Sie haben alle StormTrooper ausgemerzt.  Gute Arbeit!"
EngineDown=GUIDEBOT: "Tertiäres Ziel abgeschlossen!  Maschinenkern abgeschaltet."
EngineMisfire=GUIDEBOT: "WARNUNG -- MASCHINENFEHLZÜNDUNG!!"
EngineTakover=KEV-KOMMANDANT: "StormTrooper haben die Maschinensteuerung erobert..."
GotReconInterface=Aufklärungs-Schnittstelle
IntroText=Mars-Orbit - KEV| Flaggschiff Expediator
JeffriesID=GUIDEBOT: "Hintere Jeffriesröhre.  Es gibt von hier aus einen Weg zum Heckbereich."
LandingDoor62=GUIDEBOT: "Hauptzugangstür zur Rampe 62 wurde blockiert. Finden Sie einen anderen Weg!"
LeaderCinema=Suchen und zerstören Sie den Kommandanten der siegreichen Legionstruppen
LeaderTaunt1=KEV-FUNK: "Hier spricht der siegreiche Kommandant der Legionstruppen..."
LeaderTaunt2=KEV-FUNK: "Wir haben die Expediator unter unserer Kontrolle."
LeaderTaunt3=KEV-FUNK: "Wir werden alle Einheiten, die sich nicht sofort ergeben, eliminieren."
LeaderTaunt4=KEV-FUNK: "Wir bluten nicht. Daher kennen wir kein Erbarmen."
LeaderTaunt5=KEV-FUNK: "Stop....!"
LevelObjA=GUIDEBOT: "Sie haben das hintere Matcen erfolgreich entschärft!"
LevelObjtives1=Hauptziele: | 1. HINTERES MATCEN ENTSCHÄRFEN | Manuellen Hauptschalter zerstören.
LevelObjtives2=2. Suchen und zerstören: | Kommandant der siegreichen Legionstruppen.
LevelObjtives3=Neutralisieren Sie die Bedrohung: | VERNICHTEN SIE | rote, grüne und weisse | STORMTROOPER-VERTEIDIGUNGSLEGIONEN.
MainDeckGame=11:22.04.04.3750 SCHIFFSSTATUSPROTOKOLL K.E.V. SCHLACHTSCHIFF EXPEDIATOR: "Unbekannter Virus verseuchte Schiffverteidigungssysteme mitsamt SR-Einheiten. Wir haben den gesamten hinteren Bereich des Schiffes isoliert. Hoffentlich kamen alle rechtzeitig heraus! Suchen nach durchführbaren Lösungen."
MainDeckHud=Schiffstatus-Vorfallsprotokoll heruntergeladen... (SHIFT - F8)
NoEntry=QUARANTÄNEBEREICH  -- Zugang verboten.
NoEntry62=Dieser Zugang zum Hangar wurde zugeschweisst.  Finden Sie einen anderen Weg.
PplDoors1=Personalzugang ist unter Quarantäne gestellt.
PrimaryObjB=KEV-Kommandant: "Glückwunsch!  Sie haben Ihr Nebenziel erreicht."
PrimerDamage=GUIDEBOT: "Plasmafeld!!  Schiff erlitt Schaden."
RobotCount=Es sind noch %d infizierte StormTrooper übrig!
SecondaryObjective=NOTFALL!!! | MASCHINENFEHLER...|
ShipInfo1=Schiffs-Vorfallsprotokoll heruntergeladen... (SHIFT - F8)
ShipInfo2=10:59.04.04.3750: "Dies ist eine Notfall-Sprachaufzeichnung des hinteren Meisteringenieurs Kalmer. Nach der Installation neuer Ersatzteile aus der Lieferung 47632-09 wurde das Matcen betriebsbereit übergeben.  Es produziert infizierte StormTrooper! Es gibt keine Möglichkeit, es abzuschalten!!! Reparaturteam wird evakuiert!"
SpyPlead=JÄGERDRONE: "Bitte - ich werde nichts tun, wenn Sie mich nicht erschiessen - Ich bin nicht so wie die anderen!"
StormtroopersCine=Erledigen Sie diese Kerle...| Bevor Sie selbst erledigt werden!

