//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     27

// Message List
AccessDenied=GUIDEBOT: "Zugang verweigert! Pass wird benötigt."
Blank=
BossData=THEMA:  Modernisierter Angriffsmech.  STATUS:  F&E Fristen eingehalten.  Produktion beginnt in Kürze.  ANMERKUNGEN:  (klassifiziert) Produktionanzahlen wie gewünscht verdoppelt.  --SD
BothFireSwitches=GUIDEBOT: "Brennkammer deaktiviert."
CEDData=THEMA:  Vertrag mit Kollektiver Erdverteidigung  STATUS:  Phoenix Abfangjäger Vertrag erfüllt. Blackshark Geschoss in Entwicklung.  ANMERKUNGEN:  (klassifiziert)  Neue Lieferung wird planmässig eintreffen.  --SD
ClassifiedAccessPass=Zugangsberechtigungsschlüssel
ConsoleCrash=GUIDEBOT: "Das System scheint einen nichtregenerierbaren Fehler erlitten zu haben."
DravisData=THEMA:  Dravis, Samuel, Jr.  Direktor für Krisenfall-Management und Öffentlichkeitsarbeit  STATUS:  auf SAFA-Presse Tour  ANMERKUNGEN:  (klassifiziert)  Erbetene Beförderung wurde abgelehnt.  --Suzuki
EmergencySwitch=GUIDEBOT: "Notfallauslöseschalter zur Zeit gesperrt."
EmergencySwitchOpen=GUIDEBOT: "Notfallauslöseschalter aktiviert."
EndLevel=
FirstForcefield=Kraftfeld deaktiviert!
IntroMessage=Deimos - PTMC Datenspeicherungszentrum
LeftConsoleSwitch=GUIDEBOT: "Durchsuche Produktionsplan-Datenbank ..."
LockDown=GUIDEBOT: "Die Anlage hat die Sicherheitssperrung abgeschlossen!"
MDData=THEMA:  Materialverteidiger ID Nr. 1032  STATUS:  In der Nähe von Tycho Brahe verschollen.  ANMERKUNGEN:  (klassifiziert)  Warpkern-Hardwarefehler vermutet.  --SD
PrimaryLoginSwitch=GUIDEBOT: "Durchsuche Personaldatenbank..."
PTMCdisconnected=GUIDEBOT: "Die Verbindung wurde GETRENNT..."
RightConsoleSwitch=GUIDEBOT: "Durchsuche Verwaltungsdateien..."
SECRETAREA=Sie haben einen geheimen Bereich gefunden!
SecurityAlert=GUIDEBOT: "Mein unbefugter Datenbankzugriff wurde entdeckt! Sicherheitsmassnahmen wurden aktiviert!"
ShipMessageLog=Daten wurden zum Schiffscomputerlogbuch übertragen (SHIFT- F8)
SingleFireSwitch=GUIDEBOT: "Brennkammerschalter ausgelöst."
SRADLabData=ANMERKUNGEN:  Jüngstes SAFA-Laborunglück kostete 17 Spitzenwissenschaftlern das Leben.  Dr. Schweitzers Beschäftigungsverhältnis beendet.  --SD
SweitzerData=THEMA:  Dr. Schweitzer, Karl  Forschungsleiter des SAFA Labors auf dem Planeten Tiris.  STATUS:  Entlassen.  ANMERKUNGEN:  Sitzt im Novak Firmengefängnis auf Phobos ein.  --SD

