
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     57



// Message List

BLANK=

BossIntroductionText=L'Homunculus|

BuilderCollectorsCorrectlyPlaced=ROBOT-GUIDA: "È stata sbloccata una porta."

Builders3secondsleft=ROBOT-GUIDA: "Rimangono 3 secondi!"

BuildersDoorMessage=ROBOT-GUIDA: "In qualità di agente dei Raccoglitori puoi passare"

BuildersPuzzhint=ROBOT-GUIDA: " Individuato Pozzetto di ventilazione "

BuildersPuzzMessage=ROBOT-GUIDA: "Vola veloce!"

BuildersPuzzMessage2=ROBOT-GUIDA: "L'icona dei Costruttori interrompe il percorso prescelto!"

BuildersTimerExpired=ROBOT-GUIDA: "Tempo scaduto!"

CollectorsDoorMessage=ROBOT-GUIDA: "In qualità di agente dei Costruttori puoi passare."

EndPath=ROBOT-GUIDA: "Fine del percorso!"

EnterPriestPuzzle=ROBOT-GUIDA: "Sei entrato nell'Enigma del Sacerdote."

ExitPriestPuzzle=ROBOT-GUIDA: "Hai lasciato l'Enigma del Sacerdote."

FirstPickupBuilder=L'icona dei Costruttori

FirstPickupCollector=L'icona dei Collezionisti

FirstPickupPriest=L'icona del Sacerdote

IntroLevelMessage=Marte - I canyon Noctis Labyrinthus|

InvGame=Puoi selezionare gli oggetti dell'inventario utilizzando i comandi di default, [ e ]. Per usare o mettere in campo un oggetto, il comando di default è \. 

InvHUD=ROBOT-GUIDA: "Ricordati di utilizzare l'inventario con le icone... MAIUSC-F8."

KeyAlreadyThere=ROBOT-GUIDA: "Due in uno non fa tre..."

PlaceBuildersKey=ROBOT-GUIDA: "Hai collocato l'icona dei Costruttori."

PlaceCollectorsKey=ROBOT-GUIDA: "Hai collocato l'icona dei Collezionisti."

PlacePriestKey=ROBOT-GUIDA: "Hai collocato l'icona del Sacerdote."

PriestGalleryDoorLocked=ROBOT-GUIDA: "Tu non sei degno."

PriestHallDoorLocked=ROBOT-GUIDA: "Il sommo sacerdote non ti farà entrare!"

PriestKeyCorrectlyPlaced=ROBOT-GUIDA: "L'Homunculus attende!"

PriestPuzzleEnter=ROBOT-GUIDA: "Il Sacerdote prescelto si aggira tra le colonne."

PriestPuzzleGoofed=ROBOT-GUIDA: "Tu non sei il prescelto!"

PriestPuzzleSolved=ROBOT-GUIDA: "Tu ti sei dimostrato degno!"

Test=Prova

Testing=

ThisDoorDoesNotAnswer=ROBOT-GUIDA: "Questa porta non ti risponde."

TugMessage1=RIMORCHIATORE: "Pare che abbiamo trovato il relitto. Da qui sembra in buone condizioni."

TugMessage2=RIMORCHIATORE: "Aspetteremo qui finché la zona non sarà sicura."

TugMessage3=RIMORCHIATORE: "C'è un campo di forza che ci blocca la strada: riesci a disattivarlo alla svelta?"

TugMessage4=RIMORCHIATORE: "Sembra che non hai ancora finito! Attento!"

TugMessage5=RIMORCHIATORE: "Sbrigati a distruggere quell'affare in modo che possiamo filare via di qui!"

TugMessage6=RIMORCHIATORE: "Bene, mettiamo in scena lo spettacolo."

TugMessageShipPickUp=RIMORCHIATORE: "Ricevuto. Il campo di forza è abbassato. Ci impadroniremo della nave."

TugMessageStart=RIMORCHIATORE: "Da qui in avanti dovrai sbrogliartela da solo, pilota..."

TugStartMessage2=RIMORCHIATORE: "Manterremo il silenzio radio fin quando non avvisteremo il luogo del disastro."

XsecsOntheClock=ROBOT-GUIDA: "%.0 secondi esatti!"

YoucantUseKeyHere=

