//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     37

// Message List
ALLHeatSinksDestroyed=GUIDEBOT: "Tous lesLes 3 trois pSiphons Puits de cChaleur  ontont tous été détruits !  La trappe de Secours de l'Accès de service Maintenance d'Urgence est maintenant déverrouillée !"
CenterClampDisengaged=GUIDEBOT: "Débrayage du bBCrampon ras d'aAmarrage Baie 2.  Frégate Médicale Rossignol présente et en position.  ATTENTION !  Défaillance Système !  Impossible de débrayer !"
ClampNotInUse=GUIDEBOT: Ce crampon bras d'amarrage n'est pas actuellement utilisé."
CoolFanDestroyed=GUIDEBOT: "Ventilateur d'admission due réseau primaire de refroidissement détruit !"
CoolFanInvulnerable=GUIDEBOT: "Vos armes n'ont aucun effet !"
CoolingSystemClock=GUIDEBOT: "L'horloge du Régulateur Thermique a été activée.  Accès impossible avant queque la fin due cycle de 32 heures soit achevé."
CoolingSystemEngaged=GUIDEBOT: "RegulateurRégulateur Thermique activé:  fermeture des Events conduits de vVapeur, et ouverture des pSiphons Puits de Cchaleur."
CoreTempAboveNormal=GUIDEBOT: "Sans le sSystème de RefroidissmentRefroidissement en état de marchemarche, la température du Coeœur de la Raffinerie montera indéfiniment."
CoreTempCritical=GUIDEBOT: "Maintenant que son ventilateur d'admission priamaireprimaire est détruit, la température du Coeœur de la Rraffinerie vava monter  doucement lentement vers son point critique."
DoorUnlocked=GUIDEBOT: "Porte voisine déverouilléedéverrouillée à proximité !"
ElevatorAlreadyDown=GUIDEBOT: "L'Ascenseur du Hangar est déjà en bas."
ElevatorDOWN=GUIDEBOT: "L'Ascenseur du Hangar descend."
ElevatorNeedsDown=FRIGATE:  "Nous n'allons pas nous en sortir avec cet Ascenseur là-haut ! Allez au Centre de Contrôle et en vitesse !"
EndLevel=
EngagingCenterClamp=GUIDEBOT: " Embrayage Crampon Bras d'Amarrage Baie 2.  Frégate Médicale Rossignol [E1]présenteen position.  ATTENTION !  Défaillance Système !  Impossible d'embrayer !"
FanReverseSwitch=GUIDEBOT: "Ventilateur d'Admission de Refroidissement inversé."
ForcefieldDisabled=GUIDEBOT: "Champ de Force Désactivé !"
FoundSecretData=RECUPERE:  Cartouche de données endommagée... (SHIFT +F8)
FrigateSaved=FRIGATE:  "Merci d'avoir ouvert ce cramponbras.  Pas le temps de discuteré... Cet endroit n'a pas l'air trèsop stable !"
HangarForcefieldDown=GUIDEBOT: "Autorisation Sécurité accordée. Champ de force Hangar désactivé.   Vous avez l'autorisation de décoller."
HangarForcefieldUp=GUIDEBOT: "Autorisation Sécurité refusée.  Passe d'Autorisation nécessaire pour désactivation manuelle du champ de force."
HeatSinkDestroyed=GUIDEBOT: "PSiphon uits de Chaleur du Système de RefroissementRefroidissement détruit !"
IntroCamera=Europa - Raffinerie PTMC de Carburant Dol Ammad du PTMC
Mayday=FREGATE:  "Contrôle Hangar pour Frégate Médicale Rossignol, demande autorisation de débrayage du crampon bras d'amarrage. Je répète : Crampon Bras d'aAmarrage 2 toujours verrouillé. Demande assistance pour départ immédiat."
MessageFromFrigate=Transmission de Données en pProvenance de la FégateFrégate Médicale...  SHIFT-+F8
Passkey=Passe Sécurité Hangar
WeaponsPlantData=La cartouche est en eassez mauvais état, mais votre Guidebot arrive à extraire des informations qui pourraient être utiles.  Les données font référence à une Usine SRAD d'Armement de la DARSu SRAD qui n'est sur aucune carte de navigation de lau PTMC.  Il va falloir aller y faire un tour plus tard, ça c'est sûr.

[E1]Assurer cohérence avec traduction retenue (audio)
[E2]Assurer cohérence avec traduction retenue (audio)
[E3]Assurer cohérence avec traduction retenue (audio)
[E4]Assurer cohérence avec traduction retenue (audio)
