//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     14

// Message List
Area1=GUIDEBOT: "Bereich 1"
Area2=GUIDEBOT: "Bereich 2"
Area3=GUIDEBOT: "Bereich 3"
EndLevelMessage=BEAGLE: Materialverteidiger... Wir verlieren Ihr Signal! Ist dort unten irgendwas nicht in Ordnung?
EntranceDoorMessage=GUIDEBOT: "Testprotokoll aktiviert!"
IntroBriefingMessage=BEAGLE: Ich bin mir nicht sicher, was Sie an diesem Ort finden werden. Erforschen Sie den Bereich und melden Sie sich in der Basis zurück.
IntroHUDmessage=Eingehende Übertragung von der Beagle... (SHIFT- F8)
Nothing=
