//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     37

// Message List
ALLHeatSinksDestroyed=GUIDEBOT: "Alle 3 Kühlsysteme wurden zerstört!  Die Notfall-Zugangsluke ist jetzt entriegelt!"
CenterClampDisengaged=GUIDEBOT: "Andockklammmer an Bucht 2 wird gelöst.  Krankenfregatte Nightingale anwesend.  WARNUNG!  Systemfehler!  Ausführung nicht möglich!"
ClampNotInUse=GUIDEBOT: "Diese Andockklammmer ist zur Zeit nicht in Gebrauch."
CoolFanDestroyed=GUIDEBOT: "Ansaugventilator des primären Kühlnetzwerks zerstört!"
CoolFanInvulnerable=GUIDEBOT: "Ihre Waffen haben keine Wirkung!"
CoolingSystemClock=GUIDEBOT: "Wärmeregler-Uhr wurde aktiviert.  Zugang nicht möglich, bis 32-Stunden-Zyklus abgeschlossen ist."
CoolingSystemEngaged=GUIDEBOT: "Wärmeregler aktiviert:  Dampfentlüftung wird abgeschaltet und Kühlsystemschlitze geöffnet."
CoreTempAboveNormal=GUIDEBOT: "Ohne intaktes Kühlsystem wird die Raffineriekerntemperatur unbegrenzt ansteigen."
CoreTempCritical=GUIDEBOT: "Durch das Zerstören des Hauptansaugventilators steigt die Raffineriekerntemperatur langsam bis zum kritischen Punkt an."
DoorUnlocked=GUIDEBOT: "Nahgelegene Tür entriegelt!"
ElevatorAlreadyDown=GUIDEBOT: "Der Hangarfahrstuhl ist bereits unten."
ElevatorDOWN=GUIDEBOT: "Hangarfahrstuhl fährt abwärts."
ElevatorNeedsDown=FREGATTE:  "Wir werden es nicht schaffen, hier herauszukommen, wenn der Fahrstuhl oben ist!  Ab zum Kontrollzentrum, pronto!"
EndLevel=
EngagingCenterClamp=GUIDEBOT: "Bucht 2 Andockklammmer rastet ein. Krankenfregatte Nightingale anwesend.  WARNUNG!  Systemfehler!  Ausführung nicht möglich!"
FanReverseSwitch=GUIDEBOT: "Laufrichtung des Ansaugventilators umgekehrt."
ForcefieldDisabled=GUIDEBOT: "Kraftfeld deaktiviert!"
FoundSecretData=WIEDERGEFUNDEN:  Beschädigte Datenkassette... (SHIFT F8)
FrigateSaved=FREGATTE:  "Danke für das Öffnen der Klammmer.  Keine Zeit für Plaudereien... dieser Ort scheint nicht sehr stabil zu sein!"
HangarForcefieldDown=GUIDEBOT: "Sicherheitsbefugnis gewährt. Hangarkraftfeld deaktiviert.  Sie haben Starterlaubnis."
HangarForcefieldUp=GUIDEBOT: "Sicherheitsbefugnis verwehrt.  Befugnispass für manuelle Kraftfelddeaktivierung wird benötigt."
HeatSinkDestroyed=GUIDEBOT: "Kühlungssystem zerstört!"
IntroCamera=Europa - PTMC Kraftstoffraffinerie Dol Ammad
Mayday=FREGATTE:  "Krankenfregatte Nightingale an Hangar Control, bitte um Loslösung der Ankockklammmer.  Wiederhole:  Andockklampe 2 ist noch immer angeschlossen.  Benötige Unterstützung für sofortigen Abflug."
MessageFromFrigate=Eingehende Datenübertragungen von Krankenfregatte...  (SHIFT-F8)
Passkey=Hangar-Sicherheitspass
WeaponsPlantData=Die Kassette ist in ziemlich schlechtem Zustand, aber Ihr Guidebot schafft es, einige Dateneinheiten zu extrahieren, die möglicherweise nützlich sind.  Die Daten beziehen sich auf ein SAFA-Waffenwerk, welches auf keiner der gewöhnlichen PTMC-Navigationskarten zu finden ist.  Könnte später auf jeden Fall einen Besuch wert sein.
