
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     48



// Message List

1stInvalidPassOffense=CONTROLE: "Impossible d'accorder l'Accès Sécurité.  Veuillez patienter."

2ndInvalidPassOffense= CONTROLE: "Accès Sécurité refusée !  Forces de Sécurité alertés !"

AnotherTurretGone=GUIDEBOT: "Tourelle de défense du périmètre détruite."

ChemicalReactionAlert=GUIDEBOT: "DANGER !  Contamination à l'acide !  Alerte danger biologique au niveau 4 !  Evacuez le niveau à haute sécurité !"

ChemicalReactionSwitches=GUIDEBOT: "Verrouillage Sécurité Chimique engagé."

ComputerDestroyed=GUIDEBOT: "Le Super-Ordinateur contenant les dossiers de la Prison Novak a été détruit !"



DontShootMe=SHUTTLE: "On se calme sur mes boucliers !"
Empty=

EndLevel=

EscortShuttle=NAVETTE:  "Une escorte serait la bienvenue !"

ForcefieldDown=NAVETTE: "Le champ de force est désactivé ! Escortez-moi jusqu'à Sweitzer !"

ForcefieldDownEarly=GUIDEBOT: "Champ de force du Hangar de Transfert des Prisonniers désactivé."

G1MinSecurityPassB=Passe Sécurité G-1

IncomingMessage=Transmission en provenance de la navette... (SHIFT-F8)

InnerTowerForcefields=GUIDEBOT: "Champs de force désactivés."

IntroMessage=Phobos - Prison de la Novak Corporate

LoadedSweitzer=NAVETTE:  "Nous pouvons partir, Sweitzer est à bord. Couvrez-moi !"

LoadingSweitzer=NAVETTE:  "Que le Docteur monte à bord."

MaximumSecurityClearance=CONTROLE: "Autorisation Niveau Sécurité Maximum Accordée."

MediumSecurityClearance= CONTROLE: "Autorisation Niveau Sécurité Niveau Intermédiaire Accordée."

MinimumSecurityClearance= CONTROLE: "Autorisation Niveau Sécurité Minimum Accordée."

OneTurretDown=NAVETTE: "Parfait, ça fait une tourelle du périmètre de détruite, et il en reste quatre. Nous nous cacherons dans un ravin pendant que vous nettoyez la zone.  Bonne chance."

R1MaxSecurityPassC=Passe de Sécurité R-1

RecordsNodeDestroyed=GUIDEBOT: "Noeud de Sauvegarde des dossiers de la Novak détruit !"

SECRETAREA=Vous avez trouvé une zone secrète !

SecurityPassNotUsableHere=GUIDEBOT: "Ce Passe Sécurité n'est pas utilisable ici."

SecurityPassReturned=GUIDEBOT: "Le Passe de Sécurité a été rendu à son distributeur."

ShuttleMoveToTower=NAVETTE: "Ce périmètre a l'air de ne plus être défendu et les champs de force du Hangar de Ravitaillement sont coupés. Je vais vers la Tour Principale. Appelez-moi dès que vous aurez localisé Sweitzer. A mon avis, votre seule chance d'entrer, c'est le Hangar de Ravitaillement."

ShuttleUnderAttack=NAVETTE: "Dites, on a un petit inconvénient ici, et un peu d'appui-feu ne ferait pas de mal ! Les robots de sécurité ne vont pas me faire de cadeaux !"

SPUDhasTheBall=DRONE UPS: "Transport capsule chimique."

SPUDisBorn=GUIDEBOT: "Assignation au Drone Utilitaire de Production Spéciale.  Fabrication capsule de traitement chimique."

SPUDkilled=GUIDEBOT: "Drone Utilitaire de Production Spéciale éliminé."

SPUDscores=GUIDEBOT: "Le Drone Utilitaire de Production Spéciale a quitté les lieux."

SupplyAlarm=GUIDEBOT: "Un des robots a déclenché une alarme locale !"

SupplyAlarmPlayer=GUIDEBOT: "Levée de l'interdiction au personnel non autorisé."

SweitzerMAX=SHUTTLE:  "Super, vous avez trouvé le Dr Sweitzer. Mais il est hors de question que j'aille dans une zone placée sous haute Sécurité avec cette vieille caisse ! Il vous faudra trouver un moyen pour le faire transférer dans une zone plus sûre - de préférence dans une zone à sécurité minimum."



SweitzerMINLockedOut=SHUTTLE:  "Désolé mais je vais encore avoir besoin de vous... Il y a un champ de force en haut de la tour qui doit être désactivé avant que je puisse entrer..."

WhatTheHell=SHUTTLE: "Hé, ça va en bas ?! Je ne sais pas ce que vous avez fait, mais on dirait que la prison est en alerte totale ! A en juger par le trafic radio, ils ont commencé une sorte d'évacuation d'urgence..."

X1OldSecurityPassD=Passe Sécurité X-1 

Y1MedSecurityPassA= Passe Sécurité Y-1

