//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     45

// Message List
BLANK=
CenterLavaCrank=GUIDEBOT: "Die Lavapumpe des Zentrums ist eingeschaltet."
DravisDoor=Dravis'Festungstür hat sich geöffnet!
End=
EnergyCenterBroken=GUIDEBOT: "Energiezentrum nicht betriebsbereit aufgrund von Strommangel."
EnergyCentersOnline=GUIDEBOT: "Alle Energiezentren am Netz!"
FuseFound=Ersatzsicherung des Reaktors
HellionIntroduction=Hellion-Angriffsmechanismus
InnerDoorsDenied=GUIDEBOT: "Zugang zur Festung verweigert.  Schlüssel wird benötigt."
InnerDoorsUnlock=GUIDEBOT: "Sie haben jetzt Zugang zur inneren Festung."
InnerStrongholdKey=Schlüssel zur inneren Festung
IntroCameraText=Venus - Dravis' Festung
LeftLavaCrank=GUIDEBOT: "Linke Lavapumpe ist eingeschaltet."
MagicMatCenSwitches=GUIDEBOT: "Sicherheits-Matcen in allen 5 Sektoren im Umkreis wurden abgeschaltet. Zugang zur Waffenkammer wird gewährt."
MatCenSwitchAOff=GUIDEBOT: "Sicherheits-Matcen 1 und 5 Energie herabgesetzt."
MatCenSwitchAOn=GUIDEBOT: "Sicherheits-Matcen 1 und 5 Energie erhöht."
MatCenSwitchBOff=GUIDEBOT: "Sicherheits-Matcen 4 und 5 Energie herabgesetzt.  Sicherheits-Matcen 3 eingeschaltet."
MatCenSwitchBOn=GUIDEBOT: "Sicherheits-Matcen 4 und 5 Energie erhöht.  Sicherheits-Matcen 3 abgeschaltet."
MatCenSwitchCOff=GUIDEBOT: "Sicherheits-Matcen 3 Energie herabgesetzt. Sicherheits-Matcen 2 eingeschaltet."
MatCenSwitchCOn=GUIDEBOT: "Sicherheits-Matcen 3 Energie erhöht. Sicherheits-Matcen 2 abgeschaltet."
MatCenSwitchDOff=GUIDEBOT: "Sicherheits-Matcen 5 eingeschaltet."
MatCenSwitchDOn=GUIDEBOT: "Sicherheits-Matcen 5 abgeschaltet."
MatCenSwitchEOff=GUIDEBOT: "Sicherheits-Matcen 2 und 3 Energie herabgesetzt. Sicherheits-Matcen 1 eingeschaltet."
MatCenSwitchEOn=GUIDEBOT: "Sicherheits-Matcen 2 und 3 Energie erhöht. Sicherheits-Matcen 1 abgeschaltet."
MatCenSwitchFOff=GUIDEBOT: "Sicherheits-Matcen 2 und 4 Energie herabgesetzt."
MatCenSwitchFOn=GUIDEBOT: "Sicherheits-Matcen 2 und 4 Energie erhöht."
MatCenSwitchGOff=GUIDEBOT: "Sicherheits-Matce 5 Energie herabgesetzt. Sicherheits-Matcen 4 eingeschaltet."
MatCenSwitchGOn=GUIDEBOT: "Sicherheits-Matcen 5 Energie erhöht. Sicherheits-Matcen 4 abgeschaltet."
PowerRestored=GUIDEBOT: "Alte Reaktorsicherung ersetzt.  Energie an Energiezentren wiederhergestellt."
ReactorBroken=GUIDEBOT: "Dieser Reaktor braucht eine neue Sicherung.  Die gegenwärtige Sicherung des Reaktors ist durchgebrannt."
RightLavaCrank=GUIDEBOT: "Rechte Lavapumpe ist eingeschaltet."
TNTDispenserCenter=GUIDEBOT: "Produziere normalexplosiven Minensprengstoff."
TNTDispenserLeft=GUIDEBOT: "Produziere leichtexplosiveen Minensprengstoff."
TNTDispenserLeftBroken=GUIDEBOT: "Der Mechanismus ist vollkommen blockiert."
TNTDispenserRight=GUIDEBOT: "Produziere hochexplosiven Minensprengstoff."
TNTElevatorActivated=GUIDEBOT: "Fahrstuhl aktiviert."
TNTRockWall=GUIDEBOT: "Ihre Waffen werden diese Felsbrocken nicht bewegen."
TNTRockwalldestroyed=GUIDEBOT: "Ein Eingang wurde geöffnet."

