//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     34

// Message List
AirlockActive=GUIDEBOT: "The airlock is currently active..."
AirlockCompStarted=GUIDEBOT: "Airlock re-compression has begun."
AirlockDecompStarted=GUIDEBOT: "Airlock decompression has begun."
AirlockMalfunction=GUIDEBOT: "The airlock is malfunctioning!"
AirlockPowerNotOn=GUIDEBOT: "The airlock power is off."
AirlockPowerOn=GUIDEBOT: "The airlock's power is now on."
BadDoorBumped=GUIDEBOT: "That door isn't going to open... we'll have to find another teleporter."
BossIntro=Alien Queen
BurnIgnited=GUIDEBOT: "Ok, now this thruster should be ready for action."
CruiserFuseAcquired=Cruiser Fuse
CruiserFuseNoUse=GUIDEBOT: "You can't place the fuse here!"
CruiserFusePlaced=GUIDEBOT: "You replaced the ship's main fuse!"
DA1Game=RESULTS: Preliminary testing on the creatures is complete.  Do not let their size fool you; these things are dangerous.  Many of our weapons were useless against them.  They did, however, seem to exhibit a weakness for both fire and mass weapons.
DA1Hud=Weapon Testing Results Downloaded... (SHIFT-F8)
DA2Game=STUDY: The creatures harvest energy in a similar way that bees collect pollen. They land and deposit energy into the hive, where it can be withdrawn for healing or self-defense.  When doing so, they appear to be extremely vulnerable to energy attacks.
DA2Hud=Behavioral Study Downloaded... (SHIFT-F8)
Empty=
FFMessage=GUIDEBOT: "There must be a way to deactivate those forcefields..."
FuseRoom=GUIDEBOT: "This must be the ship's fuse room... it doesn't appear to be working."
GetOuttaHere=GUIDEBOT: "Let's get out of here!"
IgniterFailed1=GUIDEBOT: "The igniter must have failed!"
IgniterFailed2=GUIDEBOT: "You'll have to go in there and ignite the burn manually!"
IntroText=Unidentified Planetoid|Zeta Aquilae System
NoBurnIgnited=GUIDEBOT: "You need to manually ignite the burn first."
NoPowerAvail=GUIDEBOT: "You need to restore the ship's power first."
QueenLeft=GUIDEBOT: "It looks like the alien queen is on the move again..."
RechargeThruster1=GUIDEBOT: "Now the thruster is recharging..."
RechargeThruster2=GUIDEBOT: "The thruster is done charging."
ThrusterBurnFailed=GUIDEBOT: "That didn't seem to do the trick... There must be some way to force the queen back to its nest!"
UseThruster=GUIDEBOT: "The thruster on that derelict ship could prove useful..."
