//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     22

// Message List
ActivateBomb=GUIDEBOT: "Detonating bomb remotely..."
BombDropFail=GUIDEBOT: "You must place the bomb on the Delivery Pad"
BombDropSuccess=GUIDEBOT: "Placed bomb on Delivery Pad"
BombInventory=Remote Bomb
BombPadFull=GUIDEBOT: "Delivery pad already has a package on it"
BombTimerStarted=GUIDEBOT: "Return to the elevators and get out!"
BossDoorUnlock=Door unlocked!
BossName=PTMC Gattling MP-1|
DeliveryReady=GUIDEBOT: "The bomb is being delivered.  Get to a safe distance and it'll detonate automatically."
DroidOnlyDoor=GUIDEBOT: "Door can be opened by Droids only!"
EmptyMessage=
FiremenDone=Fire extinguished!
FiremenSummoning=Fire in chemical storage!  Summoning droids!
IntroMessage=Earth|PTMC Corporate Headquarters
NotSafeFromBomb=You've within the blast radius.  Get out!
SafeFromBomb=You're now outside the bomb's blast area!
SuzukiDead=GUIDEBOT: "Suzuki is dead.  Let's get out of here!"
TestMessage=Generating New Lifter!
