//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     21

// Message List
BlankMessage=
BombName=Nuclear Disruptor
CityAccessDoors=GUIDEBOT: "Colony Access Doors Unlocked!"
FCAbandoned=CED: Thanks for your assistance!  Unfortunately, we can't have any surviving eye witnesses!  Your contract is hereby terminated!
FCFindBombShelter=GUIDEBOT: "The Waste Disposal System's blast doors should survive the explosion!  It's located at the deepest point in the colony!"
FCGetOut=GUIDEBOT: "Return to the surface for extraction!"
FCNoContact=GUIDEBOT: "We're not receiving a signal from CED.  Attempting to circumvent any jamming..."
FCOneMinute=GUIDEBOT: "One minute until the whole colony is destroyed!  Get to the Waste Disposal System quickly!"
GameGetToWasteDisposal=Abandoned by CED: Get to Waste Disposal System!
GetAwayFromExit=GUIDEBOT: "Get back to the Waste Disposal!  It's your only chance of surviving!"
ICU1=I see you!
ICU2=It's getting closer!
IntroCam1=PTMC Mars Colony|
Last1=GUIDEBOT: "Rerouting door controls!  One more switch to go!"
Last2=GUIDEBOT: "Rerouting complete!  Door locks overridden!"
NuclearDisruption=GUIDEBOT: "Initiating Nuclear Disruption!"
NuclearDisruptorFail=Use the Nuclear Disruptor on the primary reactor beam!
Test=YOU SUCK!
Trap=GUIDEBOT: "It's a trap!"
WallHint=GUIDEBOT: "Slide along the walls to counter the wind!"
