//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     49

// Message List
Ambush1=GUIDEBOT: "It looks like we've got more company..."
Ambush2=GUIDEBOT: "Enemy bots sighted... and they're heading for the cargo!"
Ambush3=GUIDEBOT: "Enemy fighter spotted!"
Backup1=GUIDEBOT: "Here comes the first wave of reinforcements..."
Backup2=GUIDEBOT: "Here comes the second wave of reinforcements..."
Backup3=GUIDEBOT: "Here comes the third wave of reinforcements.."
Backup4=GUIDEBOT: "Here comes the final wave of reinforcements!"
BackupDeployed=GUIDEBOT: "They are opening the outer reactor door!  Let's get in there!"
CargoAtBase=GUIDEBOT: "The cargo has made it into the base..."
CargoAtTT=GUIDEBOT: "The cargo is ready to be loaded on the turn table!"
CargoDestroyed=GUIDEBOT: "One of the crates has been destroyed!"
CargoDestroyed2=GUIDEBOT: "Another crate has been destroyed!"
CargoDestroyed3=GUIDEBOT: "All of the cargo has been destroyed!  This mission is over..."
CargoLoaded=GUIDEBOT: "The cargo is loaded and ready to go!"
CargoNotLoaded=GUIDEBOT: "The cargo needs to be loaded first."
CargoOnTT=GUIDEBOT: "The cargo is in position on the turn table."
CEDBaseFFDown=GUIDEBOT: "The CED Base's forcefield just went down... and here comes trouble!"
ControlFFDown=GUIDEBOT: "The control tower's forcefield just went down!"
DravisDoor=GUIDEBOT: Sealed Under Dravis Authorization, #327--1138
Empty=
HangarMatcen=GUIDEBOT: "The cargo loading program has started..."
IntroText=PTMC Cesium Mine|Io, Moon of Jupiter|
Killwelders=GUIDEBOT: "Time to go welder hunting... and get those access cards."
LetsRock=GUIDEBOT: "Ok... let's see what those things can do!"
Maintenance=Maintenance  Access Card
NoCargoOnTT=GUIDEBOT: There isn't any cargo on the turn table!"
NOTFINISHED=This Level is not finished|
NoTTCargo=GUIDEBOT: "There isn't any cargo waiting to be loaded!"
OutOfAlign=GUIDEBOT: "The turn table is now out of alignment!"
ProtectCargo=GUIDEBOT: "Stay close to that cargo.  If anything happens to it, this mission is over!"
ProtectCargo2=GUIDEBOT: "The cargo is under attack!"
ProtectCargo3=GUIDEBOT: "The cargo is taking damage!"
PTMCForcefieldUp=GUIDEBOT: Forcefield Enabled!
PTMCforcefiledDown=GUIDEBOT: Forcefield Disabled !
PTMCminedoor=GUIDEBOT: "Maintenance Access Granted, Door Unlocked"
PTMCMineDoorLocked=GUIDEBOT: Maintenance Protocol Enabled, Door Locked
ReactorBlownMessage=GUIDEBOT: "Reactor Destroyed, Evacuate Immediately!"
ReactorDoorOpening=GUIDEBOT: "The diagnostic program is opening the reactor door!"
ReactorSwitchHit=GUIDEBOT: "The reactor diagnostics program has started..."
SwitchHitFromOutside=GUIDEBOT: "The control switches can only be activated from within the tower."
TTLoading=GUIDEBOT: "The cargo is now being loaded onto the turn table."
TTUnloading=GUIDEBOT: "The cargo is being unloaded from the turn table."
WrongWheelPos=GUIDEBOT: "Cargo cannot be unloaded at this turn table position!"
