//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     37

// Message List
ArmoryDoorUnlocked=GUIDEBOT: "The armory door is now unlocked."
CentralFFDown=GUIDEBOT: "That should take care of the central forcefield."
DataCartridgeName=Failsafe Data
DataCartridgeStillThere=GUIDEBOT: "First you need to pick up the cartridge containing the Failsafe data."
DataCartridgeUsed=GUIDEBOT: "No, you need to hold onto this one!"
Empty=
EndGuards=GUIDEBOT: "My guess is that these guys aren't going to let us leave without a fight..."
EscapeTime=GUIDEBOT: "I think now would be a good time to get out of here..."
ExitDoor=GUIDEBOT: "The exit door is opening!"
FoundBackDoor=GUIDEBOT: "Who needs to FIND a door when you can make your own?"
GateSecurityAlerted=GUIDEBOT: "Now we'll need to find another way to get that door open!"
GeneralDead=GUIDEBOT: "I guess the turret defense system didn't like the General much either..."
InfectedDataCartridgeName=Infected Cartridge
InfectedDataPlaced=GUIDEBOT: "Let's see how Mr. Computer likes that..."
IntroText=CED Special Operations|Central Europe|
LaserBeamTriggered=GUIDEBOT: "You just tripped a security beam!"
MainGateOpening=GUIDEBOT: "The main entrance gate is unlocking!"
NeedAWeapon=GUIDEBOT: "I bet those explosive barrels would punch a hole through the floor... if we had a way to set them off."
ResAreaEntrance=GUIDEBOT: "I sure hope there is some other way to get inside the restricted area."
ScanAborted=GUIDEBOT: "The tower scanning process was just aborted  You need to wait until it finishes."
ScanStarted=GUIDEBOT: "The tower scanning process just started..."
ScanTowerEntered=GUIDEBOT: "Just wait between these monitors until they are done scanning us..."
SecCamSpottedUs=GUIDEBOT: "A Security Camera spotted us!"
TooFarFromDataPosition=GUIDEBOT: "You can't place the infected data cartridge here!"
TurretControlDown=GUIDEBOT: "That should mess things up..."
WeaponCheckAborted=GUIDEBOT: "You are supposed to wait between the monitors..."
WeaponGuardHit=GUIDEBOT: "I don't like the looks of this..."
WeaponsChecked=GUIDEBOT: "We're unarmed, but at least we're in..."
WeaponsRemoved=GUIDEBOT: "The guard just removed all of our weapons..."
WorkerMessage=GUIDEBOT: "Those guys should be more careful next time."
WpnCheckEntered=GUIDEBOT: "Wait directly between the scan monitors to check your weapons..."
WpnCheckStarted=GUIDEBOT: "Ok, stay right here... a guard should be along soon."
