//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     22

// Message List
10Seconds=10 Seconds before the system reboots!  Get out quickly!
DeactivateFail=GUIDEBOT: "Cannot deactivate power while subnodes are active!"
DeactivateSucceed=GUIDEBOT: "Main power station deactivated!"
DoorUnlocked=Door unlocked!
EmptyMessage=
FleeMine=Warning, station reactor malfunction.  Critical mass imminent!
GetToPower=Both Computer Hubs infected!  Get to the Power Station to reboot the system!
IntroMessage=Tiris PTMC Secret Laboratory|
LabDoorUnlocked=Lab door unlocked!
LeftLabInfected=GUIDEBOT: "Computer Hub Delta infected with virus data!"
LeftLabInitData=GUIDEBOT: "Initializing data interface!"
LeftLabNotReady=GUIDEBOT: "Place the virus before activating the data upload"
LeftLabVirusPlaced=GUIDEBOT: "Virus placed in data interface!"
RechargeFail=GUIDEBOT: "Cannot recharge power while system is active!"
RechargeSucceed=GUIDEBOT: "Recharging system power!  Full reboot in 60 seconds!"
RightLabInfected=GUIDEBOT: "Computer Hub Gamma infected with virus data!"
VirusDeviceName=Virus Data
VirusInfectFail=Place the virus in an inactive data interface!
Watchout=GUIDEBOT: "Watch out behind you!"
