//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     38

// Message List
AllDone=Grossartige Leistung! Fliegen Sie jetzt durch den geöffneten Durchgang, um Ihr Training zu beenden. Gut gemacht, Rekrut!
AllRotateIntro=Ihre Rotationssteuerung ist jetzt komplett aktiviert. Probieren Sie sie aus.
AlmostDoneDodge=Sie sind fast fertig! Machen Sie weiter so!
BankIntro=Ihre Querneigungssteuerung ist jetzt aktiviert. Probieren Sie sie durch Neigen nach links und rechts aus.
CanSeeBot=Sie können den Tailbot sehen!
CantSeeBot=Sie können den Roboter nicht sehen!
ContinueToCourse=Gleiten Sie weiter nach unten, um mit der nächsten Trainingsstufe zu beginnen.
CourseInstructions=Manövrieren Sie Ihr Schiff jetzt durch diesen Tunnel unter Verwendung der gerade gelernten Gleitfunktionen.
DestroyFollowbot=Zerstören Sie jetzt den Roboter.
Dodge30=Um diese Übung erfolgreich zu beenden, müssen Sie dem Geschützturmfeuer 20 Sekunden lang ausweichen.
DodgeIntro=Als nächstes werden Sie das Ausweichen üben.
ExitManuveur=Fliegen Sie jetzt durch den geöffneten Durchgang in den nächsten Raum.
FinalSessionIntro=Nun zu Ihrer letzten und schwierigsten Aufgabe. Suchen und zerstören Sie die verbleibenden 5 Roboter.
FollowInstructions=Um diese Übung erfolgreich zu beenden, müssen Sie einen der Roboter 20 Sekunden lang in Ihrem Sichtfenster behalten, indem Sie nur die Rotationssteuerung verwenden.
FollowIntro=Jetzt werden Sie die gerade gelernten Rotationsfertigkeiten anwenden, um einen der zwei Roboter zu verfolgen, die in diesem Raum kreisen.
GalleryIntro=Ihre Bewegungssteuerung wurde deaktiviert. Zerstören Sie schnell die Roboter, wenn sie auf Sie zukommen.
GalleryStage2Intro=Sie können Ihr Schiff jetzt voll bewegen. Zerstören Sie die übrigen 2 Roboter.
GBExtra=Rufen Sie den Guide-Bot jetzt zurück durch Drücken von F4 and Auswählen von "Zurück zum Schiff". Fliegen Sie dann in den nächsten Bereich.
GBIntro=Ihr Schiff ist mit einem Mehrzweckroboter, dem Guide-Bot, ausgerüstet. Kuppeln Sie ihn jetzt mit F4 aus.
GBReturned=Gut gemacht!
GetCameraMonitor=Lassen Sie sich jetzt vom Guide-Bot helfen. Drücken Sie F4 und wählen Sie Punkt 1.  Fliegen Sie in den Gegenstand zu dem Sie der GB führt.
GoBackwards=Verwenden Sie jetzt die Rückschub-Taste, um zu Ihrer Ausgangsposition zurückzukehren!
GoDown=Gleiten Sie jetzt nach unten, bis Sie zu Ihrer Startposition zurückgekehrt sind.
GoForward=Bewegen Sie sich vorwärts, bis zum Stop.
GoLeft=Bewegen Sie sich jetzt nach rechts, bis zum Stop.
GoodJob=Hervorragend!
GoRight=Gleiten Sie nun nach rechts, bis Sie auf Ihre Startposition zurückgekehrt sind.
GoUp=Gleiten Sie jetzt nach oben, bis zum Stop.
HeadingIntro=Ihre Richtungssteuerung ist jetzt aktiviert. Probieren Sie sie durch Drehen nach rechts und links aus.
KeepDodging=Ups, Sie wurden getroffen! Bleiben Sie in Bewegung!
KeepMovingOutofDodging=Bewegen Sie Ihr Schiff jetzt vorwärts in den nächsten Raum.
KillBotIntro=In diesem Raum sind Sie nun auf sich allein gestellt. Hier gibt es 4 Roboter und 2 Powerups. Sammeln Sie die Powerups ein und zerstören Sie die Roboter.
KillBot2=Dieser Bereich ist teilweise sehr dunkel.  Verwenden Sie daher Ihre Scheinwerfer oder Leuchtgeschosse. Der Guide-Bot kann Ihnen beim Auffinden von Robotern und Powerups helfen.
LeaveDodge=Verwenden Sie jetzt Ihre Gleitsteuerung, und fliegen Sie auf das blinkende grüne Licht zu.
ManuverIntro=Sie werden jetzt die anderen Steuerungsfunktionen kennenlernen: Richtungssteuerung, Längs- und Querneigung.
Movingbotintro=Zerstören Sie jetzt 2 weitere Roboter. Dieses Mal werden sie sich bewegen.
PitchIntro=Ihre Längsneigungssteuerung ist jetzt aktiviert. Probieren Sie sie durch Neigen nach oben und unten aus.
PowerupIntro=Sie werden jetzt etwas über Powerups lernen. In diesem Raum befinden sich zwei Powerups. Finden Sie sie und nehmen Sie sie auf, indem Sie in die Powerups hineinfliegen.
ProceedtoLastRoom=Fliegen Sie jetzt durch den gerade geöffneten Durchgang, um die letzte Stufe Ihres Trainings zu beginnen.
Repeat=Lassen Sie uns die vorhergehende Übung noch einmal wiederholen.
UseCameraMonitor=Gut!  Sie haben jetzt den Kameramonitor.  Um ihn zu aktivieren, drücken Sie die Taste: Gegenstand benutzen
WeaponsEnabled=Ihre Waffen wurden aktiviert. Es gibt Primär- und Sekundärwaffen.
Welcome=Willkommen zum Descent 3 - Grundlagentraining.
