
//////////////////////////////////////////////

// D.A.L.L.A.S. Generated Message Table File

//////////////////////////////////////////////



NEXT_MESSAGE_ID_NUMBER     38



// Message List

AllDone=Bel lavoro! Adesso vola attraverso la porta aperta per terminare l'addestramento. Bel lavoro, recluta!

AllRotateIntro=Tutti i controlli di rotazione sono attivati. Testali.

AlmostDoneDodge=Hai quasi finito! Continua così che vai bene!

BankIntro=I comandi di virata sono attivati. Testali virando a sinistra e a destra.

CanSeeBot=Puoi vedere il tailbot!

CantSeeBot= Il robot non si vede!

ContinueToCourse=Prosegui l'imbardata in basso per iniziare la nuova fase.

CourseInstructions=Ora esercitati nel tunnel usando al meglio le tue capacità.

DestroyFollowbot=Via, distruggi il robot.

Dodge30=Per completare questa fase evita il fuoco della torretta per 20 secondi.

DodgeIntro=Ora dovrai imparare a evitare il nemico.

ExitManuveur=Passa da quella porta aperta e entra nella sala accanto.

FinalSessionIntro=Ora passa all'ultima e più impegnativa prova. Trova e distruggi gli ultimi cinque robot.

FollowInstructions=Mantieni uno dei robot sullo schermo per 20 secondi e completa questa fase utilizzando solo i comandi di rotazione.

FollowIntro=Ora usa le funzioni di rotazione appena apprese per inseguire uno dei due robot che girano per la stanza.

GalleryIntro=Ora i comandi di movimento sono disattivati. Distruggi rapidamente i robot che ti vengono incontro.

GalleryStage2Intro=Ora hai la completa manovrabilità dell'astronave. Distruggi i 2 robot superstiti.

GBExtra=Richiamare il Robot-Guida premendo F4 e selezionando "Ritorna alla nave". Andare alla zona successiva al suo ritorno.

GBIntro=La tua nave contiene un robot utilie chiamato Robot-Guida.  Premere F4 per liberarlo.

GBReturned=Ottimo lavoro!

GetCameraMonitor=Premere F4 e selezionare il articolo 1.  Volare sopra il oggetto a che il ti conduce.

GoBackwards=Usa la chiave reverse per tornare al punto di partenza!

GoDown=Ora plana in basso finché non sarai tornato nella posizione di partenza..

GoForward=Avanza finché non ti fermi.

GoLeft=Ora va a sinistra finché non ti fermi.

GoodJob=Ottimo!

GoRight=Ora plana a destra fino a tornare nella posizione iniziale.

GoUp=Ora scivola in alto finché non ti fermi.

HeadingIntro=Ora sono attivati i comandi direzionali. Provali ruotando a sinistra e destra.

KeepDodging=Ahi, sei stato colpito! Continua a muoverti!

KeepMovingOutofDodging=Ora continua ad avanzare nella sala accanto!

KillBotIntro=Puoi contare solo sulle tue forze in questa sala. Ci sono 4 robot e 2 energizzanti. Impadronisciti degli energizzanti e uccidi i robot.

KillBot2=Alcune parti di questa zona sono molto buie. Accendi le luci o spara dei razzi per vedere. Usa il Robot-Guida se ti serve aiuto per trovare un robot o un potenziamento.

LeaveDodge=Ora utilizza la tua abilità di volo per procedere fino alla luce verde lampeggiante.

ManuverIntro=Ora imparerai gli altri comandi: beccheggio, impostazione dell'angolo di rotta e virata..

Movingbotintro=Ora distruggi altri due robot. Questa volta saranno in movimento.

PitchIntro=Ora sono attivati i comandi per il beccheggio. Provali beccheggiando su e giù

PowerupIntro=Ora apprenderai l'uso degli energizzanti. In questa sala ce ne sono due. Trovali e raccoglili passandoci sopra..

ProceedtoLastRoom=Ora procedi attraverso la porta che si è aperta per iniziare l'ultima fase dell'addestramento.

Repeat=Ripetiamo l'esercizio appena fatto.

UseCameraMonitor=Benissimo! Ora hai il monitor della telecamera. Premi il tasto Usa Inventario per azionarlo!

WeaponsEnabled=Ora sono state attivate le tue armi. Ce ne sono una primaria e una secondaria.

Welcome=Benvenuto alla lezione d'addestramento di Descent 3.

