//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     38

// Message List
AllDone=Bravo ! Maintenant, franchissez la porte qui vient de s'ouvrir. Votre entraînement est terminé.
AllRotateIntro=Toutes vos commandes de rotation sont désormais activées. Essayez-les !
AlmostDoneDodge=Continuez comme ça, vous y êtes presque !
BankIntro=Vos commandes de rotation en oblique sont maintenant activées. Essayez-les en virant de droite et de gauche.
CanSeeBot=Vous pouvez voir le Tailbot !
CantSeeBot=Vous ne pouvez pas voir le Tailbot !
ContinueToCourse=Continuez votre descente ; nous passons à la phase suivante.
CourseInstructions=Manoeuvrez à travers ce tunnel en utilisant les techniques de navigation que vous venez d'apprendre.
DestroyFollowbot=Maintenant, détruisez le robot.
Dodge30=Pour réussir cet exercice, vous devez esquiver les tirs de la tourelle pendant 20 secondes
DodgeIntro=Vous allez maintenant travailler l'esquive.
ExitManuveur=Allez maintenant dans la pièce d'à côté.
FinalSessionIntro=Votre dernière tâche est la plus difficile : localisez et détruisez cinq robots.
FollowInstructions=Pour réussir cet exercice, vous devez garder un des robots sur votre écran pendant 20 secondes en utilisant uniquement vos commandes de rotation.
FollowIntro=Utilisez à présent les techniques de rotation que vous venez d'apprendre pour suivre un des deux robots qui font le tour de cette salle.
GalleryIntro=Vos commandes de mouvement sont maintenant désengagées. Détruisez rapidement les robots qui viennent sur vous.
GBExtra=Rappelez le guidebot en appuyant sur F4 et en selectionnant la commande de retour au vaisseau. Passez à la zone suivante des que vous aurez recuperez le guidebot.
GBIntro=Votre vaisseau est equipe d'un robot utilitaire appele le guidebot. Relachez-le en appuyant sur la touche F4.
GBReturned=Tres bien.
GetCameraMonitor=Demandez au guidebot de vous aider a reussir un objectif. Appuyez sur F4 et selectionnez la premiere commande. Suivez-le.
GalleryStage2Intro=Vous avez désormais le contrôle total du vaisseau. Détruisez les deux robots restants.
GoBackwards=Utilisez la touche de marche arrière pour revenir là où vous avez commencé.
GoDown=Continuez à descendre et retournez à votre position de départ.
GoForward=Avancez droit devant vous jusqu'à ce que vous vous arrêtiez.
GoLeft=Maintenant, allez à gauche jusqu'à ce que vous vous arrêtiez.
GoodJob=Bravo !
GoRight= Glissez maintenant vers la droite pour revenir à votre position de départ.
GoUp=Changez d'altitude pour revenir à votre position de départ.
HeadingIntro=Vos commandes de cap sont maintenant engagées. Entraînez-vous à tourner à gauche et à droite.
KeepDodging=Aïe, vous avez été touché ! Ne vous arrêtez pas !
KeepMovingOutofDodging=Maintenant, continuez à avancer jusqu'à la pièce suivante.
KillBotIntro=Vous êtes maintenant livré à vous-même. Il y a quatre robots et deux recharges dans cette salle. Ramassez les recharges et tuez les robots.
KillBot2=Certains parties de cette zone sont extrêmement sombres. Activez vos phares ou vos torches pour vous diriger. Utilisez votre GuideBot si vous avez besoin d'aide pour trouver un robot ou un élément de bonus.
LeaveDodge= Dirigez-vous vers la lumière verte qui clignote en face de vous.
ManuverIntro=Nous allons maintenant étudier les autres commandes, à savoir le tangage, le cap et le virage incliné.
Movingbotintro=Détruisez maintenant deux autres robots mobiles. 
PitchIntro=Vos commandes de tangage sont activées. Essayez de tourner sur le plan vertical.
PowerupIntro=Passons maintenant à l'utilisation des recharges. Dans cette salle, il y en a deux. Trouvez-les et ramassez-les en volant à travers.
ProceedtoLastRoom= Franchissez maintenant la porte qui vient de s'ouvrir. Nous passons au dernier exercice de l'entraînement.
Repeat=Reprenons cet exercice.
UseCameraMonitor=Formidable. Vous êtes à présent en possession des unités de caméra. Appuyez sur la touche d'inventaire pour l'activer !
WeaponsEnabled=Vos armes sont maintenant opérationnelles. Vous disposez de l'arme primaire et de l'arme secondaire.
Welcome=Bienvenue au centre d'entraînement de Descent 3.

