//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     45

// Message List
AllDone=Great Job! Now fly through the opened doorway to end your training. Good job Recruit!
AllRotateIntro=Now all your rotational controls are enabled. Try them out.
AlmostDoneDodge=You are almost done! Keep up the good work!
BankIntro=Now your bank controls are enabled. Try them out by banking to the left and right.
CanSeeBot=You can see the tailbot!
CantSeeBot=You Can't see the bot!
ContinueToCourse=Continue Sliding down to start the next step.
CourseInstructions=Now, manuever through this tunnel using the sliding skills you just learned.
DestroyFollowbot=Now, destroy the robot.
Dodge30=To complete this step, dodge the turrett fire for 20 seconds.
DodgeIntro=Next you are going to practice dodging.
ExitManuveur=Now go through the open doorway, and into the next room.
FinalSessionIntro=Now for your final and most difficult task. Locate and destroy the last 5 robots.
FollowInstructions=Keep one of the robots on your screen for 20 seconds using only your rotational controls to complete this step.
FollowIntro=Now you will use the rotational skills you just learned to follow one of the two robots that are circling this room
GalleryIntro=Now your movement controls have been disabled. Quickly destroy the robots as they come towards you.
GalleryStage2Intro=Now you have full ship movement. Destroy the remaining 2 robots.
GBExtra=Now recall the Guidebot by pressing F4 and selecting "Return to Ship".  Move to the next area when he returns.
GBIntro=Your ship is equipped with a utility robot called a Guidebot.  Release him now with F4.
GBReturned=Good job!
GetCameraMonitor=Have the Guidebot help you complete a goal.  Press F4 and select item 1.  Fly over the object he leads you to.
GoBackwards=Now use the reverse Key to return to where you started!
GoDown=Now Slide down until you return to the start position.
GoForward=Move forward until you stop.
GoLeft=Now Go Left until you stop.
GoodJob=Excellent!
GoRight=Now Slide right until you return to the start position.
GoUp=Now Slide up  until you stop.
HeadingIntro=Now your heading controls are enabled. Try them out by rotating to the left and right.
KeepDodging=Oops, you were hit! Keep moving!
KeepMovingOutofDodging=Now keep moving forward into the next room.
KillBot2=Some parts of this area are very dark.  Turn on your headlight or fire flares to see.  Use your guidebot if you need help finding a robot or powerup.
KillBotIntro=Now you are on your own in this room. There are 4 robots and 2 powerups. Get the powerups and kill the robots.
LeaveDodge=Now using your sliding skills, proceed forward to the flashing green light.
ManuverIntro=Now you are going to learn the other controls, which are pitch, heading and bank.
Movingbotintro=Now destroy 2 more robots. This time they will be moving.
PitchIntro=Now your pitch controls are enabled. Try them out by pitching up and down.
PowerupIntro=Now you are going to learn about powerups. In this room are two powerups. Find them and pick them up by running over them.
ProceedtoLastRoom=Now proceed through the doorway that just opened to begin the last stage of your training.
Repeat=Let's repeat the exercise we just did.
UseCameraMonitor=Excellent.  You now have the Camera Monitor.  Press the Use Inventory key to activate it!
WeaponsEnabled=Now your weapons have been enabled. There is a primary and a secondary.
Welcome=Welcome to the Descent 3 Training session.
