//////////////////////////////////////////////
// D.A.L.L.A.S. Generated Message Table File
//////////////////////////////////////////////

NEXT_MESSAGE_ID_NUMBER     38

// Message List
AllDone=¡Excelente trabajo! Ahora atraviesa la puerta abierta para poner fin a tu entrenamiento. ¡Buen trabajo, recluta!
AllRotateIntro=Ahora tienes activados todos los controles de rotación. Pruébalos.
AlmostDoneDodge=Ya casi has terminado. ¡Sigue haciéndolo así!
BankIntro=Ahora tienes activados los controles de alabeo. Para probarlos, balancéate a izquierda y derecha.
CanSeeBot=Puedes ver el Tailbot.
CantSeeBot=No puedes ver el robot.
ContinueToCourse=Sigue deslizándote hacia abajo para comenzar el siguiente paso.
CourseInstructions=Ahora pasa por este túnel utilizando las técnicas de deslizamiento que acabas de aprender.
DestroyFollowbot=Ahora, destruye el robot.
Dodge30=Para completar este paso, esquiva el fuego de la torreta durante 20 segundos.
DodgeIntro=Ahora vas a practicar la forma de esquivar.
ExitManuveur=Pasa por la puerta abierta y entra en la sala siguiente.
FinalSessionIntro=Prepárate para la última tarea, que es la más difícil. Busca y destruye los cinco últimos robots.
FollowInstructions=Para completar este paso, mantén uno de los robots en la pantalla durante 20 segundos utilizando sólo los controles de rotación.
FollowIntro=Ahora vas a utilizar las técnicas de rotación que acabas de aprender para seguir a uno de los dos robots que rodean esta sala.
GalleryIntro=Ahora tienes desactivados los controles de movimiento. Destruye los robots rápidamente a medida que se te acerquen.
GalleryStage2Intro=Ahora tienes el control pleno del movimiento de la nave. Destruye los dos últimos robots.
GBExtra=Ahora mande volver el Roboguía apretando F4 y seleccionando "Volver a la nave".  Muévase a la proxima zona cuando él vuelva.
GBIntro=Su nave esta equipado con un robot utilitario llamado un Roboguía.  Ahora suéltelo apretando F4.
GBReturned=¡Excelente!
GetCameraMonitor=Haga que el Roboguía le ayude alcanzar una meta.  Apriete F4 y seleccione el ítem 1.  Vuele sobre el objeto a que le conduce.
GoBackwards=Ahora pulsa la tecla de retroceso para volver al principio.
GoDown=Ahora, deslízate hasta volver a la posición inicial.
GoForward=Desplázate hacia delante hasta detenerte.
GoLeft=Ahora dirígete a la izquierda hasta detenerte.
GoodJob=¡Excelente!
GoRight=Ahora, deslízate a la derecha hasta volver a la posición inicial.
GoUp=Ahora deslízate hacia arriba hasta detenerte.
HeadingIntro=Ahora tienes activados los controles de rumbo. Para probarlos, vira a izquierda y derecha.
KeepDodging=¡Vaya! ¡Te han dado! ¡No te pares!
KeepMovingOutofDodging=Sigue avanzando hasta llegar a la sala siguiente.
KillBotIntro=Ahora estás a solas en esta sala. Hay cuatro robots y dos potenciadores. Consigue los potenciadores y mata a los robots.
KillBot2=Algunas partes de esta area son muy oscuras. Enciende los faros o lanza una bengala para ver. Usa al roboguía para encontrar a robots o bonificadores.
LeaveDodge=Ahora utiliza las técnicas de deslizamiento para avanzar hasta la luz verde intermitente.
ManuverIntro=Ahora vas a aprender a utilizar los otros controles, que son el cabeceo, el rumbo y el alabeo.
Movingbotintro=Ahora destruye otros dos robots. Esta vez se encuentran en movimiento.
PitchIntro=Ahora tienes activados los controles de cabeceo. Pruébalos subiendo y bajando.
PowerupIntro=Ahora vas a aprender a utilizar los potenciadores. En esta sala hay dos potenciadores. Búscalos y recógelos pasando por encima de ellos.
ProceedtoLastRoom=Ahora atraviesa la puerta que se acaba de abrir para pasar a la última fase de tu entrenamiento.
Repeat=Vamos a repetir este ejercicio.
UseCameraMonitor=Excelente. Ahora tienes el monitor de camara. Pulsa la tecla de Usar Inventario para activarlo.
WeaponsEnabled=Ahora tienes activadas las armas. Una es la principal y la otra la secundaria.
Welcome=Bienvenido al programa de entrenamiento de Descent 3.
