name: Continuous Integration


on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'


jobs:

  build:
    name: Build for PR
    uses: ./.github/workflows/build.yml
    # explicitly not passing secrets into the build
