name: Release source tarball
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate git hash and tarball
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake g++ libsdl2-dev zlib1g-dev
          cmake --preset linux
          cmake --build --preset linux -t get_git_hash
          cmake --build --preset linux -t package_source

      - name: Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "builds/linux/Descent3-*-Source.tar.xz"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
